// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_user_states.sql

package sqlitegen

import (
	"context"
	"strings"
)

const getChannelUserState = `-- name: GetChannelUserState :one
SELECT user_id, broadcaster_id, favorite, created_at, updated_at FROM channel_user_states WHERE user_id = ? AND broadcaster_id = ?
`

type GetChannelUserStateParams struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
}

func (q *Queries) GetChannelUserState(ctx context.Context, arg GetChannelUserStateParams) (ChannelUserState, error) {
	row := q.db.QueryRowContext(ctx, getChannelUserState, arg.UserID, arg.BroadcasterID)
	var i ChannelUserState
	err := row.Scan(
		&i.UserID,
		&i.BroadcasterID,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelUserStatesForChannels = `-- name: ListChannelUserStatesForChannels :many
SELECT user_id, broadcaster_id, favorite, created_at, updated_at FROM channel_user_states
WHERE user_id = ? AND broadcaster_id IN (/*SLICE:broadcaster_ids*/?)
`

type ListChannelUserStatesForChannelsParams struct {
	UserID         string   `json:"user_id"`
	BroadcasterIds []string `json:"broadcaster_ids"`
}

func (q *Queries) ListChannelUserStatesForChannels(ctx context.Context, arg ListChannelUserStatesForChannelsParams) ([]ChannelUserState, error) {
	query := listChannelUserStatesForChannels
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.BroadcasterIds) > 0 {
		for _, v := range arg.BroadcasterIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:broadcaster_ids*/?", strings.Repeat(",?", len(arg.BroadcasterIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:broadcaster_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelUserState{}
	for rows.Next() {
		var i ChannelUserState
		if err := rows.Scan(
			&i.UserID,
			&i.BroadcasterID,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelFavorite = `-- name: SetChannelFavorite :one
INSERT INTO channel_user_states (user_id, broadcaster_id, favorite, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(user_id, broadcaster_id) DO UPDATE SET
    favorite = excluded.favorite,
    updated_at = datetime('now')
RETURNING user_id, broadcaster_id, favorite, created_at, updated_at
`

type SetChannelFavoriteParams struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
	Favorite      int64  `json:"favorite"`
}

func (q *Queries) SetChannelFavorite(ctx context.Context, arg SetChannelFavoriteParams) (ChannelUserState, error) {
	row := q.db.QueryRowContext(ctx, setChannelFavorite, arg.UserID, arg.BroadcasterID, arg.Favorite)
	var i ChannelUserState
	err := row.Scan(
		&i.UserID,
		&i.BroadcasterID,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
