// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlitegen

import (
	"context"
	"database/sql"
	"strings"

	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitetype"
)

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE broadcaster_id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, broadcasterID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, broadcasterID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_id = ?
`

func (q *Queries) GetChannel(ctx context.Context, broadcasterID string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, broadcasterID)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByLogin = `-- name: GetChannelByLogin :one
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_login = ?
`

func (q *Queries) GetChannelByLogin(ctx context.Context, broadcasterLogin string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByLogin, broadcasterLogin)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels ORDER BY broadcaster_login
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByIDs = `-- name: ListChannelsByIDs :many
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListChannelsByIDs(ctx context.Context, ids []string) ([]Channel, error) {
	query := listChannelsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsPageAsc = `-- name: ListChannelsPageAsc :many
WITH params AS (
    SELECT CAST(?1 AS integer) AS live_only,
           CAST(?2 AS text) AS cursor_name,
           CAST(?3 AS text) AS cursor_id,
           CAST(?4 AS integer) AS row_limit
)
SELECT c.broadcaster_id, c.broadcaster_login, c.broadcaster_name, c.broadcaster_language, c.profile_image_url, c.offline_image_url, c.description, c.broadcaster_type, c.view_count, c.created_at, c.updated_at FROM channels c
CROSS JOIN params
WHERE (
    params.live_only = 0
    OR EXISTS (
        SELECT 1 FROM streams s
        WHERE s.broadcaster_id = c.broadcaster_id AND s.ended_at IS NULL
    )
)
  AND (
    params.cursor_name IS NULL
    OR lower(c.broadcaster_name) > lower(params.cursor_name)
    OR (lower(c.broadcaster_name) = lower(params.cursor_name) AND c.broadcaster_id > params.cursor_id)
  )
ORDER BY lower(c.broadcaster_name) ASC, c.broadcaster_id ASC
LIMIT (SELECT row_limit FROM params)
`

type ListChannelsPageAscParams struct {
	LiveOnly   int64          `json:"live_only"`
	CursorName sql.NullString `json:"cursor_name"`
	CursorID   string         `json:"cursor_id"`
	RowLimit   int64          `json:"row_limit"`
}

func (q *Queries) ListChannelsPageAsc(ctx context.Context, arg ListChannelsPageAscParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsPageAsc,
		arg.LiveOnly,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsPageDesc = `-- name: ListChannelsPageDesc :many
WITH params AS (
    SELECT CAST(?1 AS integer) AS live_only,
           CAST(?2 AS text) AS cursor_name,
           CAST(?3 AS text) AS cursor_id,
           CAST(?4 AS integer) AS row_limit
)
SELECT c.broadcaster_id, c.broadcaster_login, c.broadcaster_name, c.broadcaster_language, c.profile_image_url, c.offline_image_url, c.description, c.broadcaster_type, c.view_count, c.created_at, c.updated_at FROM channels c
CROSS JOIN params
WHERE (
    params.live_only = 0
    OR EXISTS (
        SELECT 1 FROM streams s
        WHERE s.broadcaster_id = c.broadcaster_id AND s.ended_at IS NULL
    )
)
  AND (
    params.cursor_name IS NULL
    OR lower(c.broadcaster_name) < lower(params.cursor_name)
    OR (lower(c.broadcaster_name) = lower(params.cursor_name) AND c.broadcaster_id < params.cursor_id)
  )
ORDER BY lower(c.broadcaster_name) DESC, c.broadcaster_id DESC
LIMIT (SELECT row_limit FROM params)
`

type ListChannelsPageDescParams struct {
	LiveOnly   int64          `json:"live_only"`
	CursorName sql.NullString `json:"cursor_name"`
	CursorID   string         `json:"cursor_id"`
	RowLimit   int64          `json:"row_limit"`
}

func (q *Queries) ListChannelsPageDesc(ctx context.Context, arg ListChannelsPageDescParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsPageDesc,
		arg.LiveOnly,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFollows = `-- name: ListUserFollows :many
SELECT c.broadcaster_id, c.broadcaster_login, c.broadcaster_name, c.broadcaster_language, c.profile_image_url, c.offline_image_url, c.description, c.broadcaster_type, c.view_count, c.created_at, c.updated_at FROM channels c
INNER JOIN user_followed_channels ufc ON ufc.broadcaster_id = c.broadcaster_id
WHERE ufc.user_id = ? AND ufc.followed = 1
ORDER BY c.broadcaster_login
`

func (q *Queries) ListUserFollows(ctx context.Context, userID string) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChannels = `-- name: SearchChannels :many
WITH params AS (
    SELECT CAST(?1 AS text) AS search_query,
           CAST(?2 AS integer) AS row_limit
)
SELECT c.broadcaster_id, c.broadcaster_login, c.broadcaster_name, c.broadcaster_language, c.profile_image_url, c.offline_image_url, c.description, c.broadcaster_type, c.view_count, c.created_at, c.updated_at FROM channels c
CROSS JOIN params
WHERE params.search_query = ''
   OR lower(c.broadcaster_login) LIKE '%' || lower(params.search_query) || '%'
   OR lower(c.broadcaster_name)  LIKE '%' || lower(params.search_query) || '%'
ORDER BY
    CASE
        WHEN params.search_query = '' THEN 3
        WHEN lower(c.broadcaster_login) = lower(params.search_query) THEN 0
        WHEN lower(c.broadcaster_login) LIKE lower(params.search_query) || '%' THEN 1
        WHEN lower(c.broadcaster_name)  LIKE lower(params.search_query) || '%' THEN 1
        ELSE 2
    END,
    c.broadcaster_login
LIMIT (SELECT row_limit FROM params)
`

type SearchChannelsParams struct {
	Query    string `json:"query"`
	RowLimit int64  `json:"row_limit"`
}

// Case-insensitive substring match on login + display name. Ranks exact
// login match first, then prefix match, then substring match, then
// alphabetical. Bind params once in a CTE with explicit casts so sqlc's
// SQLite output stays typed through the repeated CASE/LIKE expressions.
func (q *Queries) SearchChannels(ctx context.Context, arg SearchChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, searchChannels, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowChannel = `-- name: UnfollowChannel :exec
UPDATE user_followed_channels SET followed = 0 WHERE user_id = ? AND broadcaster_id = ?
`

type UnfollowChannelParams struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
}

func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) error {
	_, err := q.db.ExecContext(ctx, unfollowChannel, arg.UserID, arg.BroadcasterID)
	return err
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (
    broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language,
    profile_image_url, offline_image_url, description, broadcaster_type, view_count
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (broadcaster_id) DO UPDATE SET
    broadcaster_login = excluded.broadcaster_login,
    broadcaster_name = excluded.broadcaster_name,
    broadcaster_language = excluded.broadcaster_language,
    profile_image_url = excluded.profile_image_url,
    offline_image_url = excluded.offline_image_url,
    description = excluded.description,
    broadcaster_type = excluded.broadcaster_type,
    view_count = excluded.view_count,
    updated_at = datetime('now')
RETURNING broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at
`

type UpsertChannelParams struct {
	BroadcasterID       string         `json:"broadcaster_id"`
	BroadcasterLogin    string         `json:"broadcaster_login"`
	BroadcasterName     string         `json:"broadcaster_name"`
	BroadcasterLanguage sql.NullString `json:"broadcaster_language"`
	ProfileImageUrl     sql.NullString `json:"profile_image_url"`
	OfflineImageUrl     sql.NullString `json:"offline_image_url"`
	Description         sql.NullString `json:"description"`
	BroadcasterType     sql.NullString `json:"broadcaster_type"`
	ViewCount           int64          `json:"view_count"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, upsertChannel,
		arg.BroadcasterID,
		arg.BroadcasterLogin,
		arg.BroadcasterName,
		arg.BroadcasterLanguage,
		arg.ProfileImageUrl,
		arg.OfflineImageUrl,
		arg.Description,
		arg.BroadcasterType,
		arg.ViewCount,
	)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFollow = `-- name: UpsertUserFollow :exec
INSERT INTO user_followed_channels (user_id, broadcaster_id, followed_at, followed)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, broadcaster_id) DO UPDATE SET
    followed_at = excluded.followed_at,
    followed = excluded.followed
`

type UpsertUserFollowParams struct {
	UserID        string          `json:"user_id"`
	BroadcasterID string          `json:"broadcaster_id"`
	FollowedAt    sqlitetype.Time `json:"followed_at"`
	Followed      int64           `json:"followed"`
}

func (q *Queries) UpsertUserFollow(ctx context.Context, arg UpsertUserFollowParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserFollow,
		arg.UserID,
		arg.BroadcasterID,
		arg.FollowedAt,
		arg.Followed,
	)
	return err
}
