// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_logs.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const countEventLogs = `-- name: CountEventLogs :one
SELECT COUNT(*) FROM event_logs
`

func (q *Queries) CountEventLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventLogsByDomain = `-- name: CountEventLogsByDomain :one
SELECT COUNT(*) FROM event_logs WHERE domain = ?
`

func (q *Queries) CountEventLogsByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventLogsByDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_logs (domain, event_type, severity, message, actor_user_id, data)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, domain, event_type, severity, message, actor_user_id, data, created_at
`

type CreateEventLogParams struct {
	Domain      string         `json:"domain"`
	EventType   string         `json:"event_type"`
	Severity    string         `json:"severity"`
	Message     string         `json:"message"`
	ActorUserID sql.NullString `json:"actor_user_id"`
	Data        sql.NullString `json:"data"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRowContext(ctx, createEventLog,
		arg.Domain,
		arg.EventType,
		arg.Severity,
		arg.Message,
		arg.ActorUserID,
		arg.Data,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.EventType,
		&i.Severity,
		&i.Message,
		&i.ActorUserID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldEventLogs = `-- name: DeleteOldEventLogs :exec
DELETE FROM event_logs
WHERE created_at < ?
  AND severity IN ('debug', 'info')
`

func (q *Queries) DeleteOldEventLogs(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, deleteOldEventLogs, createdAt)
	return err
}

const listEventLogs = `-- name: ListEventLogs :many
SELECT id, domain, event_type, severity, message, actor_user_id, data, created_at FROM event_logs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEventLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEventLogs(ctx context.Context, arg ListEventLogsParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.ActorUserID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLogsByDomain = `-- name: ListEventLogsByDomain :many
SELECT id, domain, event_type, severity, message, actor_user_id, data, created_at FROM event_logs
WHERE domain = ?1
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListEventLogsByDomainParams struct {
	Domain string `json:"domain"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListEventLogsByDomain(ctx context.Context, arg ListEventLogsByDomainParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogsByDomain, arg.Domain, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.ActorUserID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLogsBySeverity = `-- name: ListEventLogsBySeverity :many
SELECT id, domain, event_type, severity, message, actor_user_id, data, created_at FROM event_logs
WHERE severity = ?1
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListEventLogsBySeverityParams struct {
	Severity string `json:"severity"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListEventLogsBySeverity(ctx context.Context, arg ListEventLogsBySeverityParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.ActorUserID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
