// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fetch_logs.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const countFetchLogs = `-- name: CountFetchLogs :one
SELECT COUNT(*) FROM fetch_logs
`

func (q *Queries) CountFetchLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFetchLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFetchLogsByType = `-- name: CountFetchLogsByType :one
SELECT COUNT(*) FROM fetch_logs WHERE fetch_type = ?
`

func (q *Queries) CountFetchLogsByType(ctx context.Context, fetchType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFetchLogsByType, fetchType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFetchLog = `-- name: CreateFetchLog :exec
INSERT INTO fetch_logs (user_id, fetch_type, broadcaster_id, status, error, duration_ms)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateFetchLogParams struct {
	UserID        sql.NullString `json:"user_id"`
	FetchType     string         `json:"fetch_type"`
	BroadcasterID sql.NullString `json:"broadcaster_id"`
	Status        int64          `json:"status"`
	Error         sql.NullString `json:"error"`
	DurationMs    int64          `json:"duration_ms"`
}

func (q *Queries) CreateFetchLog(ctx context.Context, arg CreateFetchLogParams) error {
	_, err := q.db.ExecContext(ctx, createFetchLog,
		arg.UserID,
		arg.FetchType,
		arg.BroadcasterID,
		arg.Status,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const deleteOldFetchLogs = `-- name: DeleteOldFetchLogs :exec
DELETE FROM fetch_logs WHERE fetched_at < ?
`

func (q *Queries) DeleteOldFetchLogs(ctx context.Context, fetchedAt string) error {
	_, err := q.db.ExecContext(ctx, deleteOldFetchLogs, fetchedAt)
	return err
}

const listFetchLogs = `-- name: ListFetchLogs :many
SELECT id, user_id, fetch_type, broadcaster_id, status, error, duration_ms, fetched_at FROM fetch_logs ORDER BY fetched_at DESC LIMIT ? OFFSET ?
`

type ListFetchLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListFetchLogs(ctx context.Context, arg ListFetchLogsParams) ([]FetchLog, error) {
	rows, err := q.db.QueryContext(ctx, listFetchLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchLog{}
	for rows.Next() {
		var i FetchLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FetchType,
			&i.BroadcasterID,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchLogsByType = `-- name: ListFetchLogsByType :many
SELECT id, user_id, fetch_type, broadcaster_id, status, error, duration_ms, fetched_at FROM fetch_logs WHERE fetch_type = ? ORDER BY fetched_at DESC LIMIT ? OFFSET ?
`

type ListFetchLogsByTypeParams struct {
	FetchType string `json:"fetch_type"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListFetchLogsByType(ctx context.Context, arg ListFetchLogsByTypeParams) ([]FetchLog, error) {
	rows, err := q.db.QueryContext(ctx, listFetchLogsByType, arg.FetchType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchLog{}
	for rows.Next() {
		var i FetchLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FetchType,
			&i.BroadcasterID,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
