// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlitegen

import (
	"context"
	"database/sql"

	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitetype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (token_hash, role, note, created_by, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token_hash, role, note, created_by, expires_at, redeemed_at, redeemed_by, created_at
`

type CreateInviteParams struct {
	TokenHash string          `json:"token_hash"`
	Role      string          `json:"role"`
	Note      sql.NullString  `json:"note"`
	CreatedBy string          `json:"created_by"`
	ExpiresAt sqlitetype.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.TokenHash,
		arg.Role,
		arg.Note,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.Note,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = ? AND redeemed_at IS NULL
`

func (q *Queries) DeleteInvite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, token_hash, role, note, created_by, expires_at, redeemed_at, redeemed_by, created_at FROM invites WHERE token_hash = ?
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.Note,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, token_hash, role, note, created_by, expires_at, redeemed_at, redeemed_by, created_at FROM invites ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Role,
			&i.Note,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RedeemedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvite = `-- name: RedeemInvite :execrows
UPDATE invites
SET redeemed_at = datetime('now'), redeemed_by = ?
WHERE token_hash = ? AND redeemed_at IS NULL AND expires_at > datetime('now')
`

type RedeemInviteParams struct {
	RedeemedBy sql.NullString `json:"redeemed_by"`
	TokenHash  string         `json:"token_hash"`
}

func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, redeemInvite, arg.RedeemedBy, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
