// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, video_id, broadcaster_id, status, resume_state)
VALUES (?, ?, ?, 'PENDING', ?)
RETURNING id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at
`

type CreateJobParams struct {
	ID            string `json:"id"`
	VideoID       int64  `json:"video_id"`
	BroadcasterID string `json:"broadcaster_id"`
	ResumeState   string `json:"resume_state"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.VideoID,
		arg.BroadcasterID,
		arg.ResumeState,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.BroadcasterID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.ResumeState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveJobByBroadcaster = `-- name: GetActiveJobByBroadcaster :one
SELECT id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at FROM jobs
WHERE broadcaster_id = ? AND status IN ('PENDING', 'RUNNING')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveJobByBroadcaster(ctx context.Context, broadcasterID string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getActiveJobByBroadcaster, broadcasterID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.BroadcasterID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.ResumeState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.BroadcasterID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.ResumeState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByVideoID = `-- name: GetJobByVideoID :one
SELECT id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at FROM jobs WHERE video_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetJobByVideoID(ctx context.Context, videoID int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByVideoID, videoID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.BroadcasterID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.ResumeState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFailedJobsForRetry = `-- name: ListFailedJobsForRetry :many
SELECT id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at FROM jobs
WHERE status = 'FAILED' AND finished_at IS NOT NULL AND finished_at < ?
ORDER BY finished_at ASC LIMIT ?
`

type ListFailedJobsForRetryParams struct {
	FinishedAt sql.NullString `json:"finished_at"`
	Limit      int64          `json:"limit"`
}

func (q *Queries) ListFailedJobsForRetry(ctx context.Context, arg ListFailedJobsForRetryParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listFailedJobsForRetry, arg.FinishedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.BroadcasterID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.ResumeState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningJobs = `-- name: ListRunningJobs :many
SELECT id, video_id, broadcaster_id, status, started_at, finished_at, error, resume_state, created_at, updated_at FROM jobs WHERE status = 'RUNNING' ORDER BY started_at ASC
`

func (q *Queries) ListRunningJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.BroadcasterID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.ResumeState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE jobs SET
    status = 'DONE',
    finished_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkJobDone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markJobDone, id)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs SET
    status = 'FAILED',
    finished_at = datetime('now'),
    error = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type MarkJobFailedParams struct {
	Error sql.NullString `json:"error"`
	ID    string         `json:"id"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markJobFailed, arg.Error, arg.ID)
	return err
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE jobs SET status = 'RUNNING', started_at = datetime('now'), updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkJobRunning(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markJobRunning, id)
	return err
}

const updateJobResumeState = `-- name: UpdateJobResumeState :exec
UPDATE jobs SET resume_state = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateJobResumeStateParams struct {
	ResumeState string `json:"resume_state"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateJobResumeState(ctx context.Context, arg UpdateJobResumeStateParams) error {
	_, err := q.db.ExecContext(ctx, updateJobResumeState, arg.ResumeState, arg.ID)
	return err
}
