// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_publications.sql

package sqlitegen

import (
	"context"
)

const beginMediaPublication = `-- name: BeginMediaPublication :one
INSERT INTO media_publications (key, video_id, digest, size_bytes, unresolved)
VALUES (?1, ?2, ?3, ?4, 1)
ON CONFLICT (key) DO UPDATE SET unresolved = 1
WHERE media_publications.video_id = EXCLUDED.video_id AND media_publications.digest = EXCLUDED.digest
  AND media_publications.delete_requested = 0
RETURNING "key", video_id, digest, size_bytes, unresolved, delete_requested
`

type BeginMediaPublicationParams struct {
	Key       string `json:"key"`
	VideoID   int64  `json:"video_id"`
	Digest    string `json:"digest"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) BeginMediaPublication(ctx context.Context, arg BeginMediaPublicationParams) (MediaPublication, error) {
	row := q.db.QueryRowContext(ctx, beginMediaPublication,
		arg.Key,
		arg.VideoID,
		arg.Digest,
		arg.SizeBytes,
	)
	var i MediaPublication
	err := row.Scan(
		&i.Key,
		&i.VideoID,
		&i.Digest,
		&i.SizeBytes,
		&i.Unresolved,
		&i.DeleteRequested,
	)
	return i, err
}

const confirmMediaPublication = `-- name: ConfirmMediaPublication :exec
UPDATE media_publications SET unresolved = 0 WHERE key = ?1 AND digest = ?2
`

type ConfirmMediaPublicationParams struct {
	Key    string `json:"key"`
	Digest string `json:"digest"`
}

func (q *Queries) ConfirmMediaPublication(ctx context.Context, arg ConfirmMediaPublicationParams) error {
	_, err := q.db.ExecContext(ctx, confirmMediaPublication, arg.Key, arg.Digest)
	return err
}

const deleteMediaPublication = `-- name: DeleteMediaPublication :exec
DELETE FROM media_publications WHERE key = ?1 AND unresolved = 0
`

func (q *Queries) DeleteMediaPublication(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaPublication, key)
	return err
}

const getMediaPublication = `-- name: GetMediaPublication :one
SELECT "key", video_id, digest, size_bytes, unresolved, delete_requested FROM media_publications WHERE key = ?1
`

func (q *Queries) GetMediaPublication(ctx context.Context, key string) (MediaPublication, error) {
	row := q.db.QueryRowContext(ctx, getMediaPublication, key)
	var i MediaPublication
	err := row.Scan(
		&i.Key,
		&i.VideoID,
		&i.Digest,
		&i.SizeBytes,
		&i.Unresolved,
		&i.DeleteRequested,
	)
	return i, err
}

const listMediaPublications = `-- name: ListMediaPublications :many
SELECT "key", video_id, digest, size_bytes, unresolved, delete_requested FROM media_publications WHERE key > ?1 ORDER BY key LIMIT ?2
`

type ListMediaPublicationsParams struct {
	After string `json:"after"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListMediaPublications(ctx context.Context, arg ListMediaPublicationsParams) ([]MediaPublication, error) {
	rows, err := q.db.QueryContext(ctx, listMediaPublications, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaPublication{}
	for rows.Next() {
		var i MediaPublication
		if err := rows.Scan(
			&i.Key,
			&i.VideoID,
			&i.Digest,
			&i.SizeBytes,
			&i.Unresolved,
			&i.DeleteRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingPublications = `-- name: ListRecordingPublications :many
SELECT "key", video_id, digest, size_bytes, unresolved, delete_requested FROM media_publications WHERE video_id = ?1 AND key > ?2 ORDER BY key LIMIT ?3
`

type ListRecordingPublicationsParams struct {
	VideoID int64  `json:"video_id"`
	After   string `json:"after"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListRecordingPublications(ctx context.Context, arg ListRecordingPublicationsParams) ([]MediaPublication, error) {
	rows, err := q.db.QueryContext(ctx, listRecordingPublications, arg.VideoID, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaPublication{}
	for rows.Next() {
		var i MediaPublication
		if err := rows.Scan(
			&i.Key,
			&i.VideoID,
			&i.Digest,
			&i.SizeBytes,
			&i.Unresolved,
			&i.DeleteRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestMediaPublicationDelete = `-- name: RequestMediaPublicationDelete :exec
UPDATE media_publications SET delete_requested = 1 WHERE key = ?1
`

func (q *Queries) RequestMediaPublicationDelete(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, requestMediaPublicationDelete, key)
	return err
}
