// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

import (
	"database/sql"
)

type AppAccessToken struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type Category struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	BoxArtUrl sql.NullString `json:"box_art_url"`
	IgdbID    sql.NullString `json:"igdb_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Channel struct {
	BroadcasterID       string         `json:"broadcaster_id"`
	BroadcasterLogin    string         `json:"broadcaster_login"`
	BroadcasterName     string         `json:"broadcaster_name"`
	BroadcasterLanguage sql.NullString `json:"broadcaster_language"`
	ProfileImageUrl     sql.NullString `json:"profile_image_url"`
	OfflineImageUrl     sql.NullString `json:"offline_image_url"`
	Description         sql.NullString `json:"description"`
	BroadcasterType     sql.NullString `json:"broadcaster_type"`
	ViewCount           int64          `json:"view_count"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type FetchLog struct {
	ID            int64          `json:"id"`
	UserID        sql.NullString `json:"user_id"`
	FetchType     string         `json:"fetch_type"`
	BroadcasterID sql.NullString `json:"broadcaster_id"`
	Status        int64          `json:"status"`
	Error         sql.NullString `json:"error"`
	DurationMs    int64          `json:"duration_ms"`
	FetchedAt     string         `json:"fetched_at"`
}

type Session struct {
	HashedID        string         `json:"hashed_id"`
	UserID          string         `json:"user_id"`
	EncryptedTokens []byte         `json:"encrypted_tokens"`
	ExpiresAt       string         `json:"expires_at"`
	LastActiveAt    string         `json:"last_active_at"`
	UserAgent       sql.NullString `json:"user_agent"`
	IpAddress       sql.NullString `json:"ip_address"`
	CreatedAt       string         `json:"created_at"`
}

type Tag struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type User struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	DisplayName     string         `json:"display_name"`
	Email           sql.NullString `json:"email"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
	Role            string         `json:"role"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type UserFollowedChannel struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
	FollowedAt    string `json:"followed_at"`
	Followed      int64  `json:"followed"`
}

type Whitelist struct {
	TwitchUserID string `json:"twitch_user_id"`
	AddedAt      string `json:"added_at"`
}
