// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

import (
	"database/sql"
)

type AppAccessToken struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type Category struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	BoxArtUrl sql.NullString `json:"box_art_url"`
	IgdbID    sql.NullString `json:"igdb_id"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Channel struct {
	BroadcasterID       string         `json:"broadcaster_id"`
	BroadcasterLogin    string         `json:"broadcaster_login"`
	BroadcasterName     string         `json:"broadcaster_name"`
	BroadcasterLanguage sql.NullString `json:"broadcaster_language"`
	ProfileImageUrl     sql.NullString `json:"profile_image_url"`
	OfflineImageUrl     sql.NullString `json:"offline_image_url"`
	Description         sql.NullString `json:"description"`
	BroadcasterType     sql.NullString `json:"broadcaster_type"`
	ViewCount           int64          `json:"view_count"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type FetchLog struct {
	ID            int64          `json:"id"`
	UserID        sql.NullString `json:"user_id"`
	FetchType     string         `json:"fetch_type"`
	BroadcasterID sql.NullString `json:"broadcaster_id"`
	Status        int64          `json:"status"`
	Error         sql.NullString `json:"error"`
	DurationMs    int64          `json:"duration_ms"`
	FetchedAt     string         `json:"fetched_at"`
}

type Session struct {
	HashedID        string         `json:"hashed_id"`
	UserID          string         `json:"user_id"`
	EncryptedTokens []byte         `json:"encrypted_tokens"`
	ExpiresAt       string         `json:"expires_at"`
	LastActiveAt    string         `json:"last_active_at"`
	UserAgent       sql.NullString `json:"user_agent"`
	IpAddress       sql.NullString `json:"ip_address"`
	CreatedAt       string         `json:"created_at"`
}

type Stream struct {
	ID            string         `json:"id"`
	BroadcasterID string         `json:"broadcaster_id"`
	Type          string         `json:"type"`
	Language      string         `json:"language"`
	ThumbnailUrl  sql.NullString `json:"thumbnail_url"`
	ViewerCount   int64          `json:"viewer_count"`
	IsMature      sql.NullInt64  `json:"is_mature"`
	StartedAt     string         `json:"started_at"`
	EndedAt       sql.NullString `json:"ended_at"`
	CreatedAt     string         `json:"created_at"`
}

type StreamCategory struct {
	StreamID   string `json:"stream_id"`
	CategoryID string `json:"category_id"`
}

type StreamTag struct {
	StreamID string `json:"stream_id"`
	TagID    int64  `json:"tag_id"`
}

type StreamTitle struct {
	StreamID string `json:"stream_id"`
	TitleID  int64  `json:"title_id"`
}

type Tag struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type Title struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type User struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	DisplayName     string         `json:"display_name"`
	Email           sql.NullString `json:"email"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
	Role            string         `json:"role"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type UserFollowedChannel struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
	FollowedAt    string `json:"followed_at"`
	Followed      int64  `json:"followed"`
}

type Video struct {
	ID              int64           `json:"id"`
	JobID           string          `json:"job_id"`
	Filename        string          `json:"filename"`
	DisplayName     string          `json:"display_name"`
	Status          string          `json:"status"`
	Quality         string          `json:"quality"`
	BroadcasterID   string          `json:"broadcaster_id"`
	StreamID        sql.NullString  `json:"stream_id"`
	ViewerCount     int64           `json:"viewer_count"`
	Language        string          `json:"language"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	SizeBytes       sql.NullInt64   `json:"size_bytes"`
	Thumbnail       sql.NullString  `json:"thumbnail"`
	Error           sql.NullString  `json:"error"`
	StartDownloadAt string          `json:"start_download_at"`
	DownloadedAt    sql.NullString  `json:"downloaded_at"`
	DeletedAt       sql.NullString  `json:"deleted_at"`
}

type VideoCategory struct {
	VideoID    int64  `json:"video_id"`
	CategoryID string `json:"category_id"`
}

type VideoRequest struct {
	VideoID     int64  `json:"video_id"`
	UserID      string `json:"user_id"`
	RequestedAt string `json:"requested_at"`
}

type VideoTag struct {
	VideoID int64 `json:"video_id"`
	TagID   int64 `json:"tag_id"`
}

type VideoTitle struct {
	VideoID int64 `json:"video_id"`
	TitleID int64 `json:"title_id"`
}

type Whitelist struct {
	TwitchUserID string `json:"twitch_user_id"`
	AddedAt      string `json:"added_at"`
}
