// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

import (
	"context"
	"database/sql"

	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitetype"
)

type Querier interface {
	AddToWhitelist(ctx context.Context, twitchUserID string) error
	AddVideoRequest(ctx context.Context, arg AddVideoRequestParams) error
	ClaimDueRecordingWebhookDelivery(ctx context.Context, now *sqlitetype.Time) (RecordingWebhookDelivery, error)
	ClearScheduleCategories(ctx context.Context, scheduleID int64) error
	ClearScheduleTags(ctx context.Context, scheduleID int64) error
	ClearWebhookEventPayload(ctx context.Context, receivedAt sqlitetype.Time) error
	CloseOpenVideoCategorySpans(ctx context.Context, arg CloseOpenVideoCategorySpansParams) error
	CloseOpenVideoTitleSpans(ctx context.Context, arg CloseOpenVideoTitleSpansParams) error
	// Paired with InsertVideoCategorySpan to emulate pg's CTE-driven
	// upsert. Called first inside the same tx as InsertVideoCategorySpan;
	// closes only the spans whose category_id differs from the new one.
	CloseOtherOpenVideoCategorySpans(ctx context.Context, arg CloseOtherOpenVideoCategorySpansParams) error
	// Paired with InsertVideoTitleSpan to emulate pg's CTE-driven upsert.
	// Called first inside the same tx as InsertVideoTitleSpan; closes only
	// the spans whose title_id differs from the new one.
	//
	// @at_time is sqlitetype.Time so its Valuer emits the shape SQLite's
	// julianday() accepts. Some native time.Time bindings format to RFC3339,
	// which julianday() can treat as NULL and corrupt duration sums.
	CloseOtherOpenVideoTitleSpans(ctx context.Context, arg CloseOtherOpenVideoTitleSpansParams) error
	CountActiveSubscriptions(ctx context.Context) (int64, error)
	CountEventLogs(ctx context.Context) (int64, error)
	CountEventLogsByDomain(ctx context.Context, domain string) (int64, error)
	CountFetchLogs(ctx context.Context) (int64, error)
	CountFetchLogsByType(ctx context.Context, fetchType string) (int64, error)
	CountVideoParts(ctx context.Context, videoID int64) (int64, error)
	CountVideosByStatus(ctx context.Context, status string) (int64, error)
	CountWebhookEvents(ctx context.Context) (int64, error)
	CountWebhookEventsByType(ctx context.Context, eventType sql.NullString) (int64, error)
	CreateAppToken(ctx context.Context, arg CreateAppTokenParams) (AppAccessToken, error)
	// Insert a delivery already CLAIMED (status 'delivering', one attempt counted)
	// for the synchronous send path (SendTest). Not 'pending', so the poller's
	// ClaimDueRecordingWebhookDelivery never selects it and cannot double-send it;
	// ResetStaleRecordingWebhookDeliveries recovers it if the caller crashes.
	CreateClaimedRecordingWebhookDelivery(ctx context.Context, arg CreateClaimedRecordingWebhookDeliveryParams) (RecordingWebhookDelivery, error)
	CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error)
	CreateFetchLog(ctx context.Context, arg CreateFetchLogParams) error
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateRecordingWebhookDelivery(ctx context.Context, arg CreateRecordingWebhookDeliveryParams) (RecordingWebhookDelivery, error)
	CreateRecordingWebhookDeliveryIfEnabled(ctx context.Context, arg CreateRecordingWebhookDeliveryIfEnabledParams) (RecordingWebhookDelivery, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (DownloadSchedule, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (EventsubSnapshot, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoPart(ctx context.Context, arg CreateVideoPartParams) (VideoPart, error)
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	DeleteChannel(ctx context.Context, broadcasterID string) error
	DeleteExpiredAppTokens(ctx context.Context) error
	DeleteExpiredCategorySearchCache(ctx context.Context, expiresAt sqlitetype.Time) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldEventLogs(ctx context.Context, createdAt sqlitetype.Time) error
	DeleteOldFetchLogs(ctx context.Context, fetchedAt sqlitetype.Time) error
	// Retention sweep: prune TERMINAL deliveries (delivered/rejected/failed) whose
	// latest terminal update is before the cutoff. pending/delivering rows are never
	// deleted regardless of age so a queued or in-flight delivery is never lost.
	// Uses updated_at instead of created_at so a long-retrying row keeps a recent
	// outcome.
	DeleteOldRecordingWebhookDeliveries(ctx context.Context, cutoff sqlitetype.Time) error
	DeleteOldSnapshots(ctx context.Context, fetchedAt sqlitetype.Time) error
	DeleteSchedule(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, hashedID string) error
	DeleteSubscription(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DeleteVideoParts(ctx context.Context, videoID int64) error
	DeleteVideoPlaybackAsset(ctx context.Context, videoID int64) error
	EndStream(ctx context.Context, arg EndStreamParams) error
	// EnsureRecordingWebhookSecret seeds the signing secret only when none is stored
	// yet (compare-and-swap on the empty string), exactly like EnsureServerHMACSecret.
	// The config service calls it when the webhook is first enabled, so an
	// already-set key is never overwritten and concurrent saves converge.
	EnsureRecordingWebhookSecret(ctx context.Context, recordingWebhookSecret string) error
	// EnsureServerHMACSecret persists secret only when none is stored yet
	// (compare-and-swap on the empty string), so concurrent boots converge on a
	// single value and an already-set secret is never overwritten. It also creates
	// the row if EventSub config has not been saved yet.
	EnsureServerHMACSecret(ctx context.Context, hmacSecret string) error
	FinalizeVideoPart(ctx context.Context, arg FinalizeVideoPartParams) error
	GetActiveJobByBroadcaster(ctx context.Context, broadcasterID string) (Job, error)
	GetActiveSubscriptionForBroadcasterType(ctx context.Context, arg GetActiveSubscriptionForBroadcasterTypeParams) (Subscription, error)
	GetCategory(ctx context.Context, id string) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetCategoryDetail(ctx context.Context, id string) (GetCategoryDetailRow, error)
	GetCategorySearchCache(ctx context.Context, normalizedQuery string) (CategorySearchCache, error)
	GetChannel(ctx context.Context, broadcasterID string) (Channel, error)
	GetChannelByLogin(ctx context.Context, broadcasterLogin string) (Channel, error)
	GetChannelUserState(ctx context.Context, arg GetChannelUserStateParams) (ChannelUserState, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetJobByVideoID(ctx context.Context, videoID int64) (Job, error)
	GetLastLiveStream(ctx context.Context, broadcasterID string) (Stream, error)
	GetLatestAppToken(ctx context.Context) (AppAccessToken, error)
	GetLatestSnapshot(ctx context.Context) (EventsubSnapshot, error)
	GetSchedule(ctx context.Context, id int64) (DownloadSchedule, error)
	GetScheduleForUserChannel(ctx context.Context, arg GetScheduleForUserChannelParams) (DownloadSchedule, error)
	GetServerHMACSecret(ctx context.Context) (string, error)
	GetServerSettings(ctx context.Context) (ServerSetting, error)
	GetSession(ctx context.Context, hashedID string) (Session, error)
	GetSettings(ctx context.Context, userID string) (Setting, error)
	GetStream(ctx context.Context, id string) (Stream, error)
	GetSubscription(ctx context.Context, id string) (Subscription, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTask(ctx context.Context, name string) (Task, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetVideo(ctx context.Context, id int64) (Video, error)
	GetVideoByJobID(ctx context.Context, jobID string) (Video, error)
	GetVideoPart(ctx context.Context, id int64) (VideoPart, error)
	GetVideoPartByIndex(ctx context.Context, arg GetVideoPartByIndexParams) (VideoPart, error)
	GetVideoPlaybackAsset(ctx context.Context, videoID int64) (VideoPlaybackAsset, error)
	GetVideoUserState(ctx context.Context, arg GetVideoUserStateParams) (VideoUserState, error)
	GetWebhookEvent(ctx context.Context, id int64) (WebhookEvent, error)
	GetWebhookEventByEventID(ctx context.Context, eventID string) (WebhookEvent, error)
	// True when at least one part for this video has been remuxed and
	// persisted (size_bytes > 0). Mirrors the postgres query — see
	// queries/postgres/video_parts.sql for the rationale.
	//
	// Single-line SELECT EXISTS form: sqlc-sqlite's engine miscompiles
	// multi-line EXISTS bodies, corrupting the const literal AND the
	// next query in the file (we hit both: a truncated `has_finalized`
	// alias and a clobbered DeleteVideoParts). One-line form sidesteps
	// the parser bug.
	HasFinalizedVideoParts(ctx context.Context, videoID int64) (int64, error)
	// @at_time: see CloseOtherOpenVideoTitleSpans for the timestamp Valuer.
	InsertVideoCategorySpan(ctx context.Context, arg InsertVideoCategorySpanParams) error
	InsertVideoMetadataChange(ctx context.Context, arg InsertVideoMetadataChangeParams) (int64, error)
	// The INSERT half of the upsert. The partial unique index on
	// (video_id, title_id) WHERE ended_at IS NULL keeps the same-title
	// re-enter case a no-op.
	InsertVideoTitleSpan(ctx context.Context, arg InsertVideoTitleSpanParams) error
	IsWhitelisted(ctx context.Context, twitchUserID string) (bool, error)
	LinkScheduleCategory(ctx context.Context, arg LinkScheduleCategoryParams) error
	LinkScheduleTag(ctx context.Context, arg LinkScheduleTagParams) error
	LinkSnapshotSubscription(ctx context.Context, arg LinkSnapshotSubscriptionParams) error
	LinkStreamCategory(ctx context.Context, arg LinkStreamCategoryParams) error
	LinkStreamTag(ctx context.Context, arg LinkStreamTagParams) error
	LinkStreamTitle(ctx context.Context, arg LinkStreamTitleParams) error
	LinkVideoCategory(ctx context.Context, arg LinkVideoCategoryParams) error
	LinkVideoTag(ctx context.Context, arg LinkVideoTagParams) error
	LinkVideoTitle(ctx context.Context, arg LinkVideoTitleParams) error
	ListActiveSchedulesForBroadcaster(ctx context.Context, broadcasterID string) ([]DownloadSchedule, error)
	ListActiveStreams(ctx context.Context) ([]Stream, error)
	ListActiveSubscriptions(ctx context.Context, arg ListActiveSubscriptionsParams) ([]Subscription, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByIDs(ctx context.Context, ids []string) ([]Category, error)
	// IGDB descriptions need a numeric igdb_id. Rows without one are left to the
	// Helix metadata sync first.
	ListCategoriesMissingDescription(ctx context.Context, descriptionCheckedAt *sqlitetype.Time) ([]Category, error)
	// Helix /games is the source for both box_art_url and igdb_id. Keep this
	// broader than the historical box-art-only query so categories that already
	// have art but still lack igdb_id can become eligible for IGDB enrichment.
	ListCategoriesMissingGameMetadata(ctx context.Context, gameMetadataCheckedAt *sqlitetype.Time) ([]Category, error)
	// Browse/library list: categories must be linked to at least one visible
	// recording. Twitch search can mirror catalog-only rows into categories; those
	// should stay out of the category page until a video actually references them.
	ListCategoriesWithVideos(ctx context.Context) ([]Category, error)
	ListCategoriesWithVideosPageLatestDesc(ctx context.Context, arg ListCategoriesWithVideosPageLatestDescParams) ([]ListCategoriesWithVideosPageLatestDescRow, error)
	// Cursor-paginated browse list for the default category order. This mirrors
	// ListCategoriesWithVideos' visibility predicate while over-fetching at the
	// adapter layer to discover the next cursor.
	ListCategoriesWithVideosPageNameAsc(ctx context.Context, arg ListCategoriesWithVideosPageNameAscParams) ([]Category, error)
	ListCategoriesWithVideosPageVideoCountDesc(ctx context.Context, arg ListCategoriesWithVideosPageVideoCountDescParams) ([]ListCategoriesWithVideosPageVideoCountDescRow, error)
	ListCategorySpansForVideo(ctx context.Context, videoID int64) ([]ListCategorySpansForVideoRow, error)
	ListChannelUserStatesForChannels(ctx context.Context, arg ListChannelUserStatesForChannelsParams) ([]ChannelUserState, error)
	ListChannels(ctx context.Context) ([]Channel, error)
	ListChannelsByIDs(ctx context.Context, ids []string) ([]Channel, error)
	ListChannelsPageAsc(ctx context.Context, arg ListChannelsPageAscParams) ([]Channel, error)
	ListChannelsPageDesc(ctx context.Context, arg ListChannelsPageDescParams) ([]Channel, error)
	ListDueTasks(ctx context.Context) ([]Task, error)
	ListEventLogs(ctx context.Context, arg ListEventLogsParams) ([]EventLog, error)
	ListEventLogsByDomain(ctx context.Context, arg ListEventLogsByDomainParams) ([]EventLog, error)
	ListEventLogsBySeverity(ctx context.Context, arg ListEventLogsBySeverityParams) ([]EventLog, error)
	ListFailedJobsForRetry(ctx context.Context, arg ListFailedJobsForRetryParams) ([]Job, error)
	ListFetchLogs(ctx context.Context, arg ListFetchLogsParams) ([]FetchLog, error)
	ListFetchLogsByType(ctx context.Context, arg ListFetchLogsByTypeParams) ([]FetchLog, error)
	// Terminal, not-yet-tombstoned recordings whose creation-time retention policy
	// snapshot is due at @now. DONE rows own watchable artifacts; FAILED
	// partial/cancelled rows may own finalized parts, thumbnails, strips, and
	// snapshots. FAILED rows without salvage are excluded so retention does not
	// erase error-only diagnostics. Recordings without retention_window_hours are
	// explicitly outside retention, even if the same broadcaster currently has a
	// delete schedule. The strict due boundary mirrors retention.expiredVideoIDs;
	// keep both comparisons in lockstep so the SQL prefilter and Go invariant check
	// agree on "exactly at the deadline is still retained".
	ListFinishedVideosForRetention(ctx context.Context, now *sqlitetype.Time) ([]ListFinishedVideosForRetentionRow, error)
	// SQLite has no DISTINCT ON; use ROW_NUMBER() to pick the most recent
	// stream per broadcaster, then filter to rn=1. Joined with channels so
	// the caller gets display metadata in one round-trip.
	ListLatestLivePerChannel(ctx context.Context, limit int64) ([]ListLatestLivePerChannelRow, error)
	// For each requested video, group spans by category and return the
	// aggregate rows ordered so the first row per video_id is the
	// "primary" category (most total duration, earliest first-seen,
	// then name). The adapter takes the first row per video_id since
	// SQLite lacks DISTINCT ON. Scanning first_seen_at keeps malformed
	// started_at values on the returned row's hard-fail path.
	ListPrimaryCategoriesForVideos(ctx context.Context, videoIds []int64) ([]ListPrimaryCategoriesForVideosRow, error)
	ListReadyVideoPlaybackAssets(ctx context.Context) ([]VideoPlaybackAsset, error)
	ListRecordingWebhookDeliveries(ctx context.Context, rowLimit int64) ([]RecordingWebhookDelivery, error)
	ListRunningJobs(ctx context.Context) ([]Job, error)
	ListScheduleCategories(ctx context.Context, scheduleID int64) ([]Category, error)
	ListScheduleTags(ctx context.Context, scheduleID int64) ([]Tag, error)
	ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]DownloadSchedule, error)
	ListSchedulesForUser(ctx context.Context, arg ListSchedulesForUserParams) ([]DownloadSchedule, error)
	ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]EventsubSnapshot, error)
	ListStreamsByBroadcaster(ctx context.Context, arg ListStreamsByBroadcasterParams) ([]Stream, error)
	ListStuckWebhookEvents(ctx context.Context, arg ListStuckWebhookEventsParams) ([]WebhookEvent, error)
	ListSubscriptionsByBroadcaster(ctx context.Context, broadcasterID sql.NullString) ([]Subscription, error)
	ListSubscriptionsByType(ctx context.Context, type_ string) ([]Subscription, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForVideo(ctx context.Context, videoID int64) ([]Tag, error)
	ListTasks(ctx context.Context) ([]Task, error)
	// julianday('now') is UTC per SQLite docs; matches pg's NOW() at UTC,
	// which the adapter forces in its connection setup. The
	// duration_seconds expression ends up typed `interface{}` in the
	// generated code because sqlc can't infer a REAL through the CASE
	// branches (a CAST(... AS REAL) wrapper here crashes sqlc-sqlite's
	// parser when another query in this file uses sqlc.slice). The
	// adapter asserts the scan value to float64.
	ListTitleSpansForVideo(ctx context.Context, videoID int64) ([]ListTitleSpansForVideoRow, error)
	ListTitlesForStream(ctx context.Context, streamID string) ([]Title, error)
	ListUserFollows(ctx context.Context, userID string) ([]Channel, error)
	ListUserSessions(ctx context.Context, userID string) ([]ListUserSessionsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVideoMetadataChangesForVideo(ctx context.Context, videoID int64) ([]ListVideoMetadataChangesForVideoRow, error)
	ListVideoParts(ctx context.Context, videoID int64) ([]VideoPart, error)
	ListVideoPartsForVideos(ctx context.Context, videoIds []int64) ([]VideoPart, error)
	ListVideoRequestsForUser(ctx context.Context, arg ListVideoRequestsForUserParams) ([]Video, error)
	ListVideoUserStatesForVideos(ctx context.Context, arg ListVideoUserStatesForVideosParams) ([]VideoUserState, error)
	// Unified list query with optional status filter and enum-driven sort.
	// Bind params once in a CTE with explicit casts so sqlc's SQLite output stays
	// typed through the repeated CASE expressions.
	ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error)
	ListVideosByBroadcasterPage(ctx context.Context, arg ListVideosByBroadcasterPageParams) ([]Video, error)
	ListVideosByCategoryPage(ctx context.Context, arg ListVideosByCategoryPageParams) ([]Video, error)
	ListVideosByJobIDs(ctx context.Context, jobIds []string) ([]Video, error)
	ListVideosMissingThumbnail(ctx context.Context) ([]Video, error)
	// Operator-requested deletions that are safe for the background worker to
	// finalize. The webhook frozen-parts guard mirrors retention: do not delete
	// video_parts until any pending/delivering delivery has captured them.
	ListVideosPendingManualDelete(ctx context.Context, rowLimit int64) ([]Video, error)
	ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error)
	ListWebhookEventsByBroadcaster(ctx context.Context, arg ListWebhookEventsByBroadcasterParams) ([]WebhookEvent, error)
	ListWebhookEventsByType(ctx context.Context, arg ListWebhookEventsByTypeParams) ([]WebhookEvent, error)
	ListWhitelist(ctx context.Context) ([]Whitelist, error)
	MarkCategoryDescriptionChecked(ctx context.Context, id string) error
	MarkCategoryGameMetadataChecked(ctx context.Context, id string) error
	MarkJobDone(ctx context.Context, id string) error
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error
	MarkJobRunning(ctx context.Context, id string) error
	MarkRecordingWebhookDeliveryDelivered(ctx context.Context, arg MarkRecordingWebhookDeliveryDeliveredParams) error
	MarkRecordingWebhookDeliveryFinal(ctx context.Context, arg MarkRecordingWebhookDeliveryFinalParams) error
	MarkSubscriptionRevoked(ctx context.Context, arg MarkSubscriptionRevokedParams) error
	MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) error
	MarkTaskRunning(ctx context.Context, name string) error
	MarkTaskSuccess(ctx context.Context, arg MarkTaskSuccessParams) error
	// See postgres/videos.sql MarkVideoDone for the completion_kind /
	// truncated rationale.
	MarkVideoDone(ctx context.Context, arg MarkVideoDoneParams) error
	// See postgres/videos.sql MarkVideoFailed for the completion_kind /
	// truncated rationale.
	MarkVideoFailed(ctx context.Context, arg MarkVideoFailedParams) error
	MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) error
	MarkWebhookEventProcessed(ctx context.Context, id int64) error
	PruneCategorySearchCache(ctx context.Context, offset int64) error
	RecordScheduleTrigger(ctx context.Context, id int64) error
	RemoveFromWhitelist(ctx context.Context, twitchUserID string) error
	// Queue an operator-requested deletion. Idempotent for already-queued live
	// terminal rows; active recordings must be cancelled first.
	RequestVideoDelete(ctx context.Context, id int64) (Video, error)
	ResetStaleRecordingWebhookDeliveries(ctx context.Context, arg ResetStaleRecordingWebhookDeliveriesParams) error
	// See queries/sqlite/titles.sql ResumeVideoTitleSpan for why this
	// uses positional ?1/?2 instead of @video_id/@at_time.
	ResumeVideoCategorySpan(ctx context.Context, arg ResumeVideoCategorySpanParams) error
	// sqlc-sqlite's @-rewriter misses some @video_id occurrences when
	// the param is referenced from three clauses in the same statement,
	// leaving literal "@video_id" tokens for the driver to choke on.
	// Use positional ?1 / ?2 here to force sqlc to bind uniformly.
	ResumeVideoTitleSpan(ctx context.Context, arg ResumeVideoTitleSpanParams) error
	// Manual re-queue of a terminal delivery, constrained to failed/rejected (a
	// pending row is already queued; resetting a delivered/delivering row would
	// duplicate-send). attempts is reset for a fresh budget. A non-matching id
	// returns no row, which the adapter maps to ErrNotFound.
	RetryRecordingWebhookDelivery(ctx context.Context, arg RetryRecordingWebhookDeliveryParams) (RecordingWebhookDelivery, error)
	// Case-insensitive substring match on name. unicode_lower is registered by the
	// SQLite adapter so SQLite matches Go/Postgres Unicode case folding for category
	// search. Bind params once in a CTE with explicit casts so sqlc's SQLite output
	// stays typed through the repeated CASE/LIKE expressions.
	SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error)
	// Same ranking contract as SearchCategories, restricted to categories linked to
	// at least one visible recording. unicode_lower is registered by the SQLite
	// adapter so SQLite matches Go/Postgres Unicode case folding for category search.
	// Bind params once in a CTE with explicit casts: this keeps sqlc's SQLite output
	// typed while avoiding missed @param rewrites in repeated CASE/LIKE expressions.
	SearchCategoriesWithVideos(ctx context.Context, arg SearchCategoriesWithVideosParams) ([]Category, error)
	// Case-insensitive substring match on login + display name. Ranks exact
	// login match first, then prefix match, then substring match, then
	// alphabetical. Bind params once in a CTE with explicit casts so sqlc's
	// SQLite output stays typed through the repeated CASE/LIKE expressions.
	SearchChannels(ctx context.Context, arg SearchChannelsParams) ([]Channel, error)
	SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error)
	SetChannelFavorite(ctx context.Context, arg SetChannelFavoriteParams) (ChannelUserState, error)
	// Freeze the part metadata on the first delivery build, while the video's parts
	// still exist, so a later retry rebuilds the real part list even after retention
	// has deleted those parts. Signed download URLs are re-minted per attempt and
	// capped by retention, not stored here. See
	// dispatcher.bodyForDelivery.
	SetRecordingWebhookDeliveryFrozenParts(ctx context.Context, arg SetRecordingWebhookDeliveryFrozenPartsParams) error
	// SetRecordingWebhookSecret rotates the signing secret unconditionally, for the
	// owner's explicit "regenerate secret" action.
	SetRecordingWebhookSecret(ctx context.Context, recordingWebhookSecret string) error
	// SetSchedulesPaused writes only the global auto-download pause flag, leaving
	// every other server setting untouched. The schedule processor reads it on each
	// stream.online to decide whether to skip auto-downloads; individual schedule
	// is_disabled flags are never modified, so resuming restores prior state exactly.
	SetSchedulesPaused(ctx context.Context, schedulesPaused int64) (ServerSetting, error)
	SetTaskEnabled(ctx context.Context, arg SetTaskEnabledParams) (Task, error)
	SetTaskNextRun(ctx context.Context, name string) (Task, error)
	SetVideoThumbnail(ctx context.Context, arg SetVideoThumbnailParams) error
	SetVideoWatchLater(ctx context.Context, arg SetVideoWatchLaterParams) (VideoUserState, error)
	// Tombstone a recording. deletion_kind records why ('retention' | 'manual').
	SoftDeleteVideo(ctx context.Context, arg SoftDeleteVideoParams) error
	StatisticsByStatus(ctx context.Context) ([]StatisticsByStatusRow, error)
	StatisticsChannels(ctx context.Context) (int64, error)
	StatisticsIncomplete(ctx context.Context) (int64, error)
	// Count of tombstoned (removed) recordings; powers the History "Removed" tab.
	StatisticsRemoved(ctx context.Context) (int64, error)
	StatisticsThisWeek(ctx context.Context) (int64, error)
	// Per-channel rollup of finished recordings: count + summed bytes +
	// summed duration. Mirrors StatisticsTotals scoped to one broadcaster
	// so the watch page can render a "N recordings · X GB" line under the
	// channel name without paginating the full library client-side.
	StatisticsTotalsByBroadcaster(ctx context.Context, broadcasterID string) (StatisticsTotalsByBroadcasterRow, error)
	// StatisticsTotals is split across four atomic queries instead of
	// one combined SELECT. The combined form (with CASE WHEN aggregates
	// in a multi-column SELECT list) triggers a sqlc-on-SQLite codegen
	// bug that truncates trailing chars off subsequent query consts
	// (StatisticsTotalsByBroadcaster ends up with `IS NUL` instead of
	// `IS NULL`). Splitting keeps each query small enough that the
	// parser doesn't trip; the adapter combines them into a single
	// VideoStatsTotals struct. Postgres still uses the single-query
	// form; see queries/postgres/videos.sql.
	StatisticsTotalsDoneOnly(ctx context.Context) (StatisticsTotalsDoneOnlyRow, error)
	StatisticsUnwatched(ctx context.Context, userID string) (int64, error)
	StatisticsWatchLater(ctx context.Context, userID string) (int64, error)
	// SQLite stores booleans as INTEGER; "NOT is_disabled" works but flips
	// between 0/1 explicitly via CASE for clarity on non-boolean-ish values.
	ToggleSchedule(ctx context.Context, id int64) (DownloadSchedule, error)
	TouchCategorySearchCache(ctx context.Context, arg TouchCategorySearchCacheParams) error
	TouchVideoPlaybackAsset(ctx context.Context, videoID int64) error
	UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) error
	UnlinkScheduleCategory(ctx context.Context, arg UnlinkScheduleCategoryParams) error
	UnlinkScheduleTag(ctx context.Context, arg UnlinkScheduleTagParams) error
	UpdateCategoryDescription(ctx context.Context, arg UpdateCategoryDescriptionParams) error
	// Refresh the Twitch-side category metadata returned by Helix /games.
	// Empty inputs preserve the existing value so callers can safely write
	// whichever subset Twitch returned.
	UpdateCategoryGameMetadata(ctx context.Context, arg UpdateCategoryGameMetadataParams) error
	UpdateJobResumeState(ctx context.Context, arg UpdateJobResumeStateParams) error
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (DownloadSchedule, error)
	UpdateSessionActivity(ctx context.Context, hashedID string) error
	UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error
	UpdateStreamViewers(ctx context.Context, arg UpdateStreamViewersParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateVideoSelectedVariant(ctx context.Context, arg UpdateVideoSelectedVariantParams) error
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
	UpdateVideoWatchProgress(ctx context.Context, arg UpdateVideoWatchProgressParams) (VideoUserState, error)
	// Preserves box_art_url, igdb_id, and description on ordinary webhook-path
	// upserts that only know (id, name). When a non-empty incoming igdb_id changes
	// the mapped IGDB game, the existing description cache is cleared so it can be
	// re-enriched for the new game.
	UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (Category, error)
	UpsertCategorySearchCache(ctx context.Context, arg UpsertCategorySearchCacheParams) (CategorySearchCache, error)
	UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error)
	// UpsertPlaybackCacheConfig writes only the continuous-playback cache knobs.
	// Artifacts are generated asynchronously after downloads, so these settings
	// must be mutable at runtime without touching EventSub or webhook config.
	UpsertPlaybackCacheConfig(ctx context.Context, arg UpsertPlaybackCacheConfigParams) (ServerSetting, error)
	// UpsertRecordingWebhookConfig writes ONLY the recording-webhook config columns
	// (enabled, url, events), leaving server_mode, the EventSub URLs, hmac_secret,
	// AND the recording webhook secret untouched. The secret is managed by its own
	// two queries below so this config write can never clobber, truncate, or race
	// the signing key. Mirrors EnsureServerHMACSecret's single-concern style.
	UpsertRecordingWebhookConfig(ctx context.Context, arg UpsertRecordingWebhookConfigParams) (ServerSetting, error)
	UpsertServerSettings(ctx context.Context, arg UpsertServerSettingsParams) (ServerSetting, error)
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error)
	UpsertStream(ctx context.Context, arg UpsertStreamParams) (Stream, error)
	// Self-heal path; see postgres variant.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
	UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error)
	UpsertTitle(ctx context.Context, name string) (Title, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UpsertUserFollow(ctx context.Context, arg UpsertUserFollowParams) error
	UpsertVideoPlaybackAsset(ctx context.Context, arg UpsertVideoPlaybackAssetParams) (VideoPlaybackAsset, error)
}

var _ Querier = (*Queries)(nil)
