// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_requests.sql

package sqlitegen

import (
	"context"
	"database/sql"

	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitetype"
)

const createScheduleRequest = `-- name: CreateScheduleRequest :one
INSERT INTO schedule_requests (broadcaster_id, requested_by, note)
VALUES (?, ?, ?)
RETURNING id, broadcaster_id, requested_by, note, status, decided_by, decided_at, schedule_id, created_at
`

type CreateScheduleRequestParams struct {
	BroadcasterID string         `json:"broadcaster_id"`
	RequestedBy   string         `json:"requested_by"`
	Note          sql.NullString `json:"note"`
}

func (q *Queries) CreateScheduleRequest(ctx context.Context, arg CreateScheduleRequestParams) (ScheduleRequest, error) {
	row := q.db.QueryRowContext(ctx, createScheduleRequest, arg.BroadcasterID, arg.RequestedBy, arg.Note)
	var i ScheduleRequest
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Note,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ScheduleID,
		&i.CreatedAt,
	)
	return i, err
}

const decideScheduleRequest = `-- name: DecideScheduleRequest :execrows
UPDATE schedule_requests
SET status = ?, decided_by = ?, decided_at = datetime('now'), schedule_id = ?
WHERE id = ? AND status = 'PENDING'
`

type DecideScheduleRequestParams struct {
	Status     string         `json:"status"`
	DecidedBy  sql.NullString `json:"decided_by"`
	ScheduleID sql.NullInt64  `json:"schedule_id"`
	ID         int64          `json:"id"`
}

func (q *Queries) DecideScheduleRequest(ctx context.Context, arg DecideScheduleRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideScheduleRequest,
		arg.Status,
		arg.DecidedBy,
		arg.ScheduleID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteScheduleRequest = `-- name: DeleteScheduleRequest :execrows
DELETE FROM schedule_requests
WHERE id = ? AND requested_by = ? AND status = 'PENDING'
`

type DeleteScheduleRequestParams struct {
	ID          int64  `json:"id"`
	RequestedBy string `json:"requested_by"`
}

func (q *Queries) DeleteScheduleRequest(ctx context.Context, arg DeleteScheduleRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScheduleRequest, arg.ID, arg.RequestedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScheduleRequest = `-- name: GetScheduleRequest :one
SELECT id, broadcaster_id, requested_by, note, status, decided_by, decided_at, schedule_id, created_at FROM schedule_requests WHERE id = ?
`

func (q *Queries) GetScheduleRequest(ctx context.Context, id int64) (ScheduleRequest, error) {
	row := q.db.QueryRowContext(ctx, getScheduleRequest, id)
	var i ScheduleRequest
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Note,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ScheduleID,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleRequests = `-- name: ListScheduleRequests :many
SELECT sr.id, sr.broadcaster_id, sr.requested_by, sr.note, sr.status, sr.decided_by, sr.decided_at, sr.schedule_id, sr.created_at, c.broadcaster_login, c.broadcaster_name, c.profile_image_url,
       u.login AS requested_by_login, u.display_name AS requested_by_name
FROM schedule_requests sr
INNER JOIN channels c ON c.broadcaster_id = sr.broadcaster_id
INNER JOIN users u ON u.id = sr.requested_by
WHERE (sr.created_at, sr.id) < (?1, CAST(?2 AS INTEGER))
ORDER BY sr.created_at DESC, sr.id DESC
LIMIT ?3
`

type ListScheduleRequestsParams struct {
	BeforeCreatedAt sqlitetype.Time `json:"before_created_at"`
	BeforeID        int64           `json:"before_id"`
	PageLimit       int64           `json:"page_limit"`
}

type ListScheduleRequestsRow struct {
	ID               int64            `json:"id"`
	BroadcasterID    string           `json:"broadcaster_id"`
	RequestedBy      string           `json:"requested_by"`
	Note             sql.NullString   `json:"note"`
	Status           string           `json:"status"`
	DecidedBy        sql.NullString   `json:"decided_by"`
	DecidedAt        *sqlitetype.Time `json:"decided_at"`
	ScheduleID       sql.NullInt64    `json:"schedule_id"`
	CreatedAt        sqlitetype.Time  `json:"created_at"`
	BroadcasterLogin string           `json:"broadcaster_login"`
	BroadcasterName  string           `json:"broadcaster_name"`
	ProfileImageUrl  sql.NullString   `json:"profile_image_url"`
	RequestedByLogin string           `json:"requested_by_login"`
	RequestedByName  string           `json:"requested_by_name"`
}

func (q *Queries) ListScheduleRequests(ctx context.Context, arg ListScheduleRequestsParams) ([]ListScheduleRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRequests, arg.BeforeCreatedAt, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRequestsRow{}
	for rows.Next() {
		var i ListScheduleRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Note,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.ProfileImageUrl,
			&i.RequestedByLogin,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRequestsForUser = `-- name: ListScheduleRequestsForUser :many
SELECT sr.id, sr.broadcaster_id, sr.requested_by, sr.note, sr.status, sr.decided_by, sr.decided_at, sr.schedule_id, sr.created_at, c.broadcaster_login, c.broadcaster_name, c.profile_image_url,
       u.login AS requested_by_login, u.display_name AS requested_by_name
FROM schedule_requests sr
INNER JOIN channels c ON c.broadcaster_id = sr.broadcaster_id
INNER JOIN users u ON u.id = sr.requested_by
WHERE sr.requested_by = ?1 AND (sr.created_at, sr.id) < (?2, CAST(?3 AS INTEGER))
ORDER BY sr.created_at DESC, sr.id DESC
LIMIT ?4
`

type ListScheduleRequestsForUserParams struct {
	RequestedBy     string          `json:"requested_by"`
	BeforeCreatedAt sqlitetype.Time `json:"before_created_at"`
	BeforeID        int64           `json:"before_id"`
	PageLimit       int64           `json:"page_limit"`
}

type ListScheduleRequestsForUserRow struct {
	ID               int64            `json:"id"`
	BroadcasterID    string           `json:"broadcaster_id"`
	RequestedBy      string           `json:"requested_by"`
	Note             sql.NullString   `json:"note"`
	Status           string           `json:"status"`
	DecidedBy        sql.NullString   `json:"decided_by"`
	DecidedAt        *sqlitetype.Time `json:"decided_at"`
	ScheduleID       sql.NullInt64    `json:"schedule_id"`
	CreatedAt        sqlitetype.Time  `json:"created_at"`
	BroadcasterLogin string           `json:"broadcaster_login"`
	BroadcasterName  string           `json:"broadcaster_name"`
	ProfileImageUrl  sql.NullString   `json:"profile_image_url"`
	RequestedByLogin string           `json:"requested_by_login"`
	RequestedByName  string           `json:"requested_by_name"`
}

func (q *Queries) ListScheduleRequestsForUser(ctx context.Context, arg ListScheduleRequestsForUserParams) ([]ListScheduleRequestsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRequestsForUser,
		arg.RequestedBy,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRequestsForUserRow{}
	for rows.Next() {
		var i ListScheduleRequestsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Note,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.ProfileImageUrl,
			&i.RequestedByLogin,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
