// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const clearScheduleCategories = `-- name: ClearScheduleCategories :exec
DELETE FROM download_schedule_categories WHERE schedule_id = ?
`

func (q *Queries) ClearScheduleCategories(ctx context.Context, scheduleID int64) error {
	_, err := q.db.ExecContext(ctx, clearScheduleCategories, scheduleID)
	return err
}

const clearScheduleTags = `-- name: ClearScheduleTags :exec
DELETE FROM download_schedule_tags WHERE schedule_id = ?
`

func (q *Queries) ClearScheduleTags(ctx context.Context, scheduleID int64) error {
	_, err := q.db.ExecContext(ctx, clearScheduleTags, scheduleID)
	return err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO download_schedules (
    broadcaster_id, requested_by, quality,
    has_min_viewers, min_viewers,
    has_categories, has_tags,
    is_delete_rediff, time_before_delete,
    is_disabled
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

type CreateScheduleParams struct {
	BroadcasterID    string        `json:"broadcaster_id"`
	RequestedBy      string        `json:"requested_by"`
	Quality          string        `json:"quality"`
	HasMinViewers    int64         `json:"has_min_viewers"`
	MinViewers       sql.NullInt64 `json:"min_viewers"`
	HasCategories    int64         `json:"has_categories"`
	HasTags          int64         `json:"has_tags"`
	IsDeleteRediff   int64         `json:"is_delete_rediff"`
	TimeBeforeDelete sql.NullInt64 `json:"time_before_delete"`
	IsDisabled       int64         `json:"is_disabled"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (DownloadSchedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.BroadcasterID,
		arg.RequestedBy,
		arg.Quality,
		arg.HasMinViewers,
		arg.MinViewers,
		arg.HasCategories,
		arg.HasTags,
		arg.IsDeleteRediff,
		arg.TimeBeforeDelete,
		arg.IsDisabled,
	)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM download_schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (DownloadSchedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleForUserChannel = `-- name: GetScheduleForUserChannel :one
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE broadcaster_id = ? AND requested_by = ?
`

type GetScheduleForUserChannelParams struct {
	BroadcasterID string `json:"broadcaster_id"`
	RequestedBy   string `json:"requested_by"`
}

func (q *Queries) GetScheduleForUserChannel(ctx context.Context, arg GetScheduleForUserChannelParams) (DownloadSchedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleForUserChannel, arg.BroadcasterID, arg.RequestedBy)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkScheduleCategory = `-- name: LinkScheduleCategory :exec
INSERT INTO download_schedule_categories (schedule_id, category_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type LinkScheduleCategoryParams struct {
	ScheduleID int64  `json:"schedule_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) LinkScheduleCategory(ctx context.Context, arg LinkScheduleCategoryParams) error {
	_, err := q.db.ExecContext(ctx, linkScheduleCategory, arg.ScheduleID, arg.CategoryID)
	return err
}

const linkScheduleTag = `-- name: LinkScheduleTag :exec
INSERT INTO download_schedule_tags (schedule_id, tag_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type LinkScheduleTagParams struct {
	ScheduleID int64 `json:"schedule_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) LinkScheduleTag(ctx context.Context, arg LinkScheduleTagParams) error {
	_, err := q.db.ExecContext(ctx, linkScheduleTag, arg.ScheduleID, arg.TagID)
	return err
}

const listActiveSchedulesForBroadcaster = `-- name: ListActiveSchedulesForBroadcaster :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE broadcaster_id = ? AND is_disabled = 0
`

func (q *Queries) ListActiveSchedulesForBroadcaster(ctx context.Context, broadcasterID string) ([]DownloadSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSchedulesForBroadcaster, broadcasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleCategories = `-- name: ListScheduleCategories :many
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at FROM categories c
INNER JOIN download_schedule_categories dsc ON dsc.category_id = c.id
WHERE dsc.schedule_id = ?
ORDER BY c.name
`

func (q *Queries) ListScheduleCategories(ctx context.Context, scheduleID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleCategories, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTags = `-- name: ListScheduleTags :many
SELECT t.id, t.name, t.created_at FROM tags t
INNER JOIN download_schedule_tags dst ON dst.tag_id = t.id
WHERE dst.schedule_id = ?
ORDER BY t.name
`

func (q *Queries) ListScheduleTags(ctx context.Context, scheduleID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleTags, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListSchedulesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]DownloadSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForUser = `-- name: ListSchedulesForUser :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE requested_by = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSchedulesForUserParams struct {
	RequestedBy string `json:"requested_by"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListSchedulesForUser(ctx context.Context, arg ListSchedulesForUserParams) ([]DownloadSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesForUser, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleTrigger = `-- name: RecordScheduleTrigger :exec
UPDATE download_schedules SET
    last_triggered_at = datetime('now'),
    trigger_count = trigger_count + 1
WHERE id = ?
`

func (q *Queries) RecordScheduleTrigger(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, recordScheduleTrigger, id)
	return err
}

const toggleSchedule = `-- name: ToggleSchedule :one
UPDATE download_schedules SET
    is_disabled = CASE WHEN is_disabled = 0 THEN 1 ELSE 0 END,
    updated_at  = datetime('now')
WHERE id = ?
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

// SQLite stores booleans as INTEGER; "NOT is_disabled" works but flips
// between 0/1 explicitly via CASE for clarity on non-boolean-ish values.
func (q *Queries) ToggleSchedule(ctx context.Context, id int64) (DownloadSchedule, error) {
	row := q.db.QueryRowContext(ctx, toggleSchedule, id)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkScheduleCategory = `-- name: UnlinkScheduleCategory :exec
DELETE FROM download_schedule_categories
WHERE schedule_id = ? AND category_id = ?
`

type UnlinkScheduleCategoryParams struct {
	ScheduleID int64  `json:"schedule_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) UnlinkScheduleCategory(ctx context.Context, arg UnlinkScheduleCategoryParams) error {
	_, err := q.db.ExecContext(ctx, unlinkScheduleCategory, arg.ScheduleID, arg.CategoryID)
	return err
}

const unlinkScheduleTag = `-- name: UnlinkScheduleTag :exec
DELETE FROM download_schedule_tags
WHERE schedule_id = ? AND tag_id = ?
`

type UnlinkScheduleTagParams struct {
	ScheduleID int64 `json:"schedule_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) UnlinkScheduleTag(ctx context.Context, arg UnlinkScheduleTagParams) error {
	_, err := q.db.ExecContext(ctx, unlinkScheduleTag, arg.ScheduleID, arg.TagID)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE download_schedules SET
    quality             = ?,
    has_min_viewers     = ?,
    min_viewers         = ?,
    has_categories      = ?,
    has_tags            = ?,
    is_delete_rediff    = ?,
    time_before_delete  = ?,
    is_disabled         = ?,
    updated_at          = datetime('now')
WHERE id = ?
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

type UpdateScheduleParams struct {
	Quality          string        `json:"quality"`
	HasMinViewers    int64         `json:"has_min_viewers"`
	MinViewers       sql.NullInt64 `json:"min_viewers"`
	HasCategories    int64         `json:"has_categories"`
	HasTags          int64         `json:"has_tags"`
	IsDeleteRediff   int64         `json:"is_delete_rediff"`
	TimeBeforeDelete sql.NullInt64 `json:"time_before_delete"`
	IsDisabled       int64         `json:"is_disabled"`
	ID               int64         `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (DownloadSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateSchedule,
		arg.Quality,
		arg.HasMinViewers,
		arg.MinViewers,
		arg.HasCategories,
		arg.HasTags,
		arg.IsDeleteRediff,
		arg.TimeBeforeDelete,
		arg.IsDisabled,
		arg.ID,
	)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
