// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlitegen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT user_id, timezone, datetime_format, language, created_at, updated_at FROM settings WHERE user_id = ?
`

func (q *Queries) GetSettings(ctx context.Context, userID string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings, userID)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.DatetimeFormat,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (user_id, timezone, datetime_format, language)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE
SET timezone        = excluded.timezone,
    datetime_format = excluded.datetime_format,
    language        = excluded.language,
    updated_at      = datetime('now')
RETURNING user_id, timezone, datetime_format, language, created_at, updated_at
`

type UpsertSettingsParams struct {
	UserID         string `json:"user_id"`
	Timezone       string `json:"timezone"`
	DatetimeFormat string `json:"datetime_format"`
	Language       string `json:"language"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertSettings,
		arg.UserID,
		arg.Timezone,
		arg.DatetimeFormat,
		arg.Language,
	)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.DatetimeFormat,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
