// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_execution.sql

package sqlitegen

import (
	"context"
)

const claimTask = `-- name: ClaimTask :execrows
UPDATE tasks SET execution_id = ?2, last_status = 'running', last_run_at = datetime('now'),
    next_run_at = NULL, last_error = NULL, updated_at = datetime('now')
WHERE name = ?1 AND execution_id <> ?2 AND is_available = 1 AND is_enabled = 1 AND (interval_seconds > 0 OR next_run_at IS NOT NULL)
  AND last_status <> 'running'
  AND (next_run_at IS NULL OR next_run_at <= datetime('now'))
`

type ClaimTaskParams struct {
	Name        string `json:"name"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimTask, arg.Name, arg.ExecutionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoverInterruptedTasks = `-- name: RecoverInterruptedTasks :exec
UPDATE tasks SET last_status = 'interrupted',
    next_run_at = ifnull(next_run_at, datetime('now')), updated_at = datetime('now')
WHERE last_status = 'running'
`

// Startup owns abandoned executions, including paused or unavailable one-shots.
func (q *Queries) RecoverInterruptedTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverInterruptedTasks)
	return err
}

const resetTaskAvailability = `-- name: ResetTaskAvailability :exec
UPDATE tasks SET is_available = 0
`

func (q *Queries) ResetTaskAvailability(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTaskAvailability)
	return err
}

const settleTask = `-- name: SettleTask :execrows
UPDATE tasks SET last_status = ?3, last_duration_ms = ?4, last_error = NULLIF(?5, ''),
    next_run_at = CASE
      WHEN ?3 = 'interrupted' THEN ifnull(next_run_at, datetime('now'))
      WHEN interval_seconds > 0 THEN ifnull(next_run_at, datetime('now', '+' || interval_seconds || ' seconds'))
      ELSE next_run_at END,
    updated_at = datetime('now')
WHERE name = ?1 AND execution_id = ?2 AND last_status = 'running'
`

type SettleTaskParams struct {
	Name           string      `json:"name"`
	ExecutionID    string      `json:"execution_id"`
	LastStatus     string      `json:"last_status"`
	LastDurationMs int64       `json:"last_duration_ms"`
	NULLIF         interface{} `json:"NULLIF"`
}

func (q *Queries) SettleTask(ctx context.Context, arg SettleTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, settleTask,
		arg.Name,
		arg.ExecutionID,
		arg.LastStatus,
		arg.LastDurationMs,
		arg.NULLIF,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
