// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: twitch_playback_sessions.sql

package sqlitegen

import (
	"context"
)

const deleteTwitchPlaybackSession = `-- name: DeleteTwitchPlaybackSession :exec
DELETE FROM twitch_playback_sessions WHERE id = 1
`

func (q *Queries) DeleteTwitchPlaybackSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTwitchPlaybackSession)
	return err
}

const getTwitchPlaybackSession = `-- name: GetTwitchPlaybackSession :one
SELECT id, twitch_user_id, twitch_login, encrypted_token, expires_at, checked_at, needs_reconnect FROM twitch_playback_sessions WHERE id = 1
`

func (q *Queries) GetTwitchPlaybackSession(ctx context.Context) (TwitchPlaybackSession, error) {
	row := q.db.QueryRowContext(ctx, getTwitchPlaybackSession)
	var i TwitchPlaybackSession
	err := row.Scan(
		&i.ID,
		&i.TwitchUserID,
		&i.TwitchLogin,
		&i.EncryptedToken,
		&i.ExpiresAt,
		&i.CheckedAt,
		&i.NeedsReconnect,
	)
	return i, err
}

const saveTwitchPlaybackSession = `-- name: SaveTwitchPlaybackSession :exec
INSERT INTO twitch_playback_sessions (id, twitch_user_id, twitch_login, encrypted_token, expires_at, checked_at)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET twitch_user_id = excluded.twitch_user_id,
    twitch_login = excluded.twitch_login, encrypted_token = excluded.encrypted_token,
    expires_at = excluded.expires_at, checked_at = excluded.checked_at, needs_reconnect = 0
`

type SaveTwitchPlaybackSessionParams struct {
	TwitchUserID   string `json:"twitch_user_id"`
	TwitchLogin    string `json:"twitch_login"`
	EncryptedToken []byte `json:"encrypted_token"`
	ExpiresAt      int64  `json:"expires_at"`
	CheckedAt      int64  `json:"checked_at"`
}

func (q *Queries) SaveTwitchPlaybackSession(ctx context.Context, arg SaveTwitchPlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveTwitchPlaybackSession,
		arg.TwitchUserID,
		arg.TwitchLogin,
		arg.EncryptedToken,
		arg.ExpiresAt,
		arg.CheckedAt,
	)
	return err
}

const updateTwitchPlaybackSessionValidation = `-- name: UpdateTwitchPlaybackSessionValidation :exec
UPDATE twitch_playback_sessions SET checked_at = ?, expires_at = ?, needs_reconnect = ?
WHERE id = 1 AND encrypted_token = ? AND needs_reconnect = 0
`

type UpdateTwitchPlaybackSessionValidationParams struct {
	CheckedAt      int64  `json:"checked_at"`
	ExpiresAt      int64  `json:"expires_at"`
	NeedsReconnect int64  `json:"needs_reconnect"`
	EncryptedToken []byte `json:"encrypted_token"`
}

func (q *Queries) UpdateTwitchPlaybackSessionValidation(ctx context.Context, arg UpdateTwitchPlaybackSessionValidationParams) error {
	_, err := q.db.ExecContext(ctx, updateTwitchPlaybackSessionValidation,
		arg.CheckedAt,
		arg.ExpiresAt,
		arg.NeedsReconnect,
		arg.EncryptedToken,
	)
	return err
}
