// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const getUser = `-- name: GetUser :one
SELECT id, login, display_name, email, profile_image_url, role, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, display_name, email, profile_image_url, role, created_at, updated_at FROM users WHERE login = ?
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, display_name, email, profile_image_url, role, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.DisplayName,
			&i.Email,
			&i.ProfileImageUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, login, display_name, email, profile_image_url, role)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    login = excluded.login,
    display_name = excluded.display_name,
    email = excluded.email,
    profile_image_url = excluded.profile_image_url,
    updated_at = datetime('now')
RETURNING id, login, display_name, email, profile_image_url, role, created_at, updated_at
`

type UpsertUserParams struct {
	ID              string         `json:"id"`
	Login           string         `json:"login"`
	DisplayName     string         `json:"display_name"`
	Email           sql.NullString `json:"email"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
	Role            string         `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.Login,
		arg.DisplayName,
		arg.Email,
		arg.ProfileImageUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
