// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlitegen

import (
	"context"
	"database/sql"
	"strings"

	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitetype"
)

const countVideosByStatus = `-- name: CountVideosByStatus :one
SELECT COUNT(*) FROM videos WHERE status = ? AND deleted_at IS NULL
`

func (q *Queries) CountVideosByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideosByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    job_id, filename, display_name, title, status, quality,
    broadcaster_id, stream_id, viewer_count, language, recording_type,
    force_h264, trigger_schedule_id, retention_source_schedule_id,
    retention_window_hours
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at
`

type CreateVideoParams struct {
	JobID                     string         `json:"job_id"`
	Filename                  string         `json:"filename"`
	DisplayName               string         `json:"display_name"`
	Title                     string         `json:"title"`
	Status                    string         `json:"status"`
	Quality                   string         `json:"quality"`
	BroadcasterID             string         `json:"broadcaster_id"`
	StreamID                  sql.NullString `json:"stream_id"`
	ViewerCount               int64          `json:"viewer_count"`
	Language                  string         `json:"language"`
	RecordingType             string         `json:"recording_type"`
	ForceH264                 int64          `json:"force_h264"`
	TriggerScheduleID         sql.NullInt64  `json:"trigger_schedule_id"`
	RetentionSourceScheduleID sql.NullInt64  `json:"retention_source_schedule_id"`
	RetentionWindowHours      sql.NullInt64  `json:"retention_window_hours"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.JobID,
		arg.Filename,
		arg.DisplayName,
		arg.Title,
		arg.Status,
		arg.Quality,
		arg.BroadcasterID,
		arg.StreamID,
		arg.ViewerCount,
		arg.Language,
		arg.RecordingType,
		arg.ForceH264,
		arg.TriggerScheduleID,
		arg.RetentionSourceScheduleID,
		arg.RetentionWindowHours,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
		&i.Truncated,
		&i.TriggerScheduleID,
		&i.RetentionSourceScheduleID,
		&i.RetentionWindowHours,
		&i.DeletionKind,
		&i.DeleteRequestedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at FROM videos WHERE id = ?
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
		&i.Truncated,
		&i.TriggerScheduleID,
		&i.RetentionSourceScheduleID,
		&i.RetentionWindowHours,
		&i.DeletionKind,
		&i.DeleteRequestedAt,
	)
	return i, err
}

const getVideoByJobID = `-- name: GetVideoByJobID :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at FROM videos WHERE job_id = ?
`

func (q *Queries) GetVideoByJobID(ctx context.Context, jobID string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByJobID, jobID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
		&i.Truncated,
		&i.TriggerScheduleID,
		&i.RetentionSourceScheduleID,
		&i.RetentionWindowHours,
		&i.DeletionKind,
		&i.DeleteRequestedAt,
	)
	return i, err
}

const listFinishedVideosForRetention = `-- name: ListFinishedVideosForRetention :many
SELECT id, broadcaster_id, downloaded_at, retention_window_hours FROM videos
WHERE deleted_at IS NULL
  AND delete_requested_at IS NULL
  AND downloaded_at IS NOT NULL
  AND retention_window_hours IS NOT NULL
  AND datetime(downloaded_at, '+' || retention_window_hours || ' hours') < ?1
  AND (
    status = 'DONE'
    OR (status = 'FAILED' AND completion_kind IN ('partial', 'cancelled'))
  )
  AND NOT EXISTS (
    SELECT 1
    FROM recording_webhook_deliveries rwd
    WHERE rwd.video_id = videos.id
      AND rwd.test = 0
      AND rwd.status IN ('pending', 'delivering')
      AND rwd.frozen_parts = ''
  )
`

type ListFinishedVideosForRetentionRow struct {
	ID                   int64            `json:"id"`
	BroadcasterID        string           `json:"broadcaster_id"`
	DownloadedAt         *sqlitetype.Time `json:"downloaded_at"`
	RetentionWindowHours sql.NullInt64    `json:"retention_window_hours"`
}

// Terminal, not-yet-tombstoned recordings whose creation-time retention policy
// snapshot is due at @now. DONE rows own watchable artifacts; FAILED
// partial/cancelled rows may own finalized parts, thumbnails, strips, and
// snapshots. FAILED rows without salvage are excluded so retention does not
// erase error-only diagnostics. Recordings without retention_window_hours are
// explicitly outside retention, even if the same broadcaster currently has a
// delete schedule. The strict due boundary mirrors retention.expiredVideoIDs;
// keep both comparisons in lockstep so the SQL prefilter and Go invariant check
// agree on "exactly at the deadline is still retained".
func (q *Queries) ListFinishedVideosForRetention(ctx context.Context, now *sqlitetype.Time) ([]ListFinishedVideosForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedVideosForRetention, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinishedVideosForRetentionRow{}
	for rows.Next() {
		var i ListFinishedVideosForRetentionRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.DownloadedAt,
			&i.RetentionWindowHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
WITH params AS (
    SELECT CAST(?1 AS text) AS status_filter,
           CAST(?2 AS text) AS sort_key,
           CAST(?3 AS integer) AS row_limit,
           CAST(?4 AS integer) AS row_offset
)
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps, v.truncated, v.trigger_schedule_id, v.retention_source_schedule_id, v.retention_window_hours, v.deletion_kind, v.delete_requested_at FROM videos v
CROSS JOIN params
WHERE v.deleted_at IS NULL
  AND (params.status_filter = '' OR v.status = params.status_filter)
ORDER BY
  CASE WHEN params.sort_key = 'duration-desc'  THEN v.duration_seconds  END DESC NULLS LAST,
  CASE WHEN params.sort_key = 'duration-asc'   THEN v.duration_seconds  END ASC NULLS LAST,
  CASE WHEN params.sort_key = 'size-desc'      THEN v.size_bytes        END DESC NULLS LAST,
  CASE WHEN params.sort_key = 'size-asc'       THEN v.size_bytes        END ASC NULLS LAST,
  CASE WHEN params.sort_key = 'channel-asc'    THEN v.display_name      END ASC,
  CASE WHEN params.sort_key = 'channel-desc'   THEN v.display_name      END DESC,
  CASE WHEN params.sort_key = 'history_when-desc' THEN COALESCE(v.deleted_at, v.downloaded_at, v.start_download_at) END DESC,
  CASE WHEN params.sort_key = 'history_when-asc'  THEN COALESCE(v.deleted_at, v.downloaded_at, v.start_download_at) END ASC,
  CASE WHEN params.sort_key = 'created_at-asc' THEN v.start_download_at END ASC,
  v.start_download_at DESC,
  CASE WHEN params.sort_key LIKE '%-asc' THEN v.id END ASC,
  v.id DESC
LIMIT (SELECT row_limit FROM params) OFFSET (SELECT row_offset FROM params)
`

type ListVideosParams struct {
	StatusFilter string `json:"status_filter"`
	SortKey      string `json:"sort_key"`
	RowLimit     int64  `json:"row_limit"`
	RowOffset    int64  `json:"row_offset"`
}

// Unified list query with optional status filter and enum-driven sort.
// Bind params once in a CTE with explicit casts so sqlc's SQLite output stays
// typed through the repeated CASE expressions.
func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos,
		arg.StatusFilter,
		arg.SortKey,
		arg.RowLimit,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByBroadcasterPage = `-- name: ListVideosByBroadcasterPage :many
WITH params AS (
    SELECT CAST(?1 AS text) AS broadcaster_id,
           CAST(?2 AS text) AS cursor_start_download_at,
           CAST(?3 AS integer) AS cursor_id,
           CAST(?4 AS integer) AS row_limit
)
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps, v.truncated, v.trigger_schedule_id, v.retention_source_schedule_id, v.retention_window_hours, v.deletion_kind, v.delete_requested_at FROM videos v
CROSS JOIN params
WHERE v.broadcaster_id = params.broadcaster_id
  AND v.deleted_at IS NULL
  AND (
    params.cursor_start_download_at IS NULL
    OR v.start_download_at < params.cursor_start_download_at
    OR (v.start_download_at = params.cursor_start_download_at AND v.id < params.cursor_id)
  )
ORDER BY v.start_download_at DESC, v.id DESC
LIMIT (SELECT row_limit FROM params)
`

type ListVideosByBroadcasterPageParams struct {
	BroadcasterID         string         `json:"broadcaster_id"`
	CursorStartDownloadAt sql.NullString `json:"cursor_start_download_at"`
	CursorID              int64          `json:"cursor_id"`
	RowLimit              int64          `json:"row_limit"`
}

func (q *Queries) ListVideosByBroadcasterPage(ctx context.Context, arg ListVideosByBroadcasterPageParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByBroadcasterPage,
		arg.BroadcasterID,
		arg.CursorStartDownloadAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByCategoryPage = `-- name: ListVideosByCategoryPage :many
WITH params AS (
    SELECT CAST(?1 AS text) AS category_id,
           CAST(?2 AS text) AS cursor_start_download_at,
           CAST(?3 AS integer) AS cursor_id,
           CAST(?4 AS integer) AS row_limit
)
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps, v.truncated, v.trigger_schedule_id, v.retention_source_schedule_id, v.retention_window_hours, v.deletion_kind, v.delete_requested_at FROM videos v
CROSS JOIN params
INNER JOIN video_categories vc ON vc.video_id = v.id
WHERE vc.category_id = params.category_id
  AND v.deleted_at IS NULL
  AND (
    params.cursor_start_download_at IS NULL
    OR v.start_download_at < params.cursor_start_download_at
    OR (v.start_download_at = params.cursor_start_download_at AND v.id < params.cursor_id)
  )
ORDER BY v.start_download_at DESC, v.id DESC
LIMIT (SELECT row_limit FROM params)
`

type ListVideosByCategoryPageParams struct {
	CategoryID            string         `json:"category_id"`
	CursorStartDownloadAt sql.NullString `json:"cursor_start_download_at"`
	CursorID              int64          `json:"cursor_id"`
	RowLimit              int64          `json:"row_limit"`
}

func (q *Queries) ListVideosByCategoryPage(ctx context.Context, arg ListVideosByCategoryPageParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByCategoryPage,
		arg.CategoryID,
		arg.CursorStartDownloadAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByJobIDs = `-- name: ListVideosByJobIDs :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at FROM videos WHERE job_id IN (/*SLICE:job_ids*/?)
`

func (q *Queries) ListVideosByJobIDs(ctx context.Context, jobIds []string) ([]Video, error) {
	query := listVideosByJobIDs
	var queryParams []interface{}
	if len(jobIds) > 0 {
		for _, v := range jobIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:job_ids*/?", strings.Repeat(",?", len(jobIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:job_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosMissingThumbnail = `-- name: ListVideosMissingThumbnail :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at FROM videos WHERE status = 'DONE' AND thumbnail IS NULL AND deleted_at IS NULL
`

func (q *Queries) ListVideosMissingThumbnail(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosMissingThumbnail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosPendingManualDelete = `-- name: ListVideosPendingManualDelete :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at FROM videos
WHERE deleted_at IS NULL
  AND delete_requested_at IS NOT NULL
  AND status IN ('DONE', 'FAILED')
  AND NOT EXISTS (
    SELECT 1
    FROM recording_webhook_deliveries rwd
    WHERE rwd.video_id = videos.id
      AND rwd.test = 0
      AND rwd.status IN ('pending', 'delivering')
      AND rwd.frozen_parts = ''
  )
ORDER BY delete_requested_at ASC, id ASC
LIMIT ?1
`

// Operator-requested deletions that are safe for the background worker to
// finalize. The webhook frozen-parts guard mirrors retention: do not delete
// video_parts until any pending/delivering delivery has captured them.
func (q *Queries) ListVideosPendingManualDelete(ctx context.Context, rowLimit int64) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosPendingManualDelete, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoDone = `-- name: MarkVideoDone :exec
UPDATE videos SET
    status = 'DONE',
    downloaded_at = datetime('now'),
    duration_seconds = ?,
    size_bytes = ?,
    thumbnail = ?,
    completion_kind = ?,
    truncated = ?
WHERE id = ?
`

type MarkVideoDoneParams struct {
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	SizeBytes       sql.NullInt64   `json:"size_bytes"`
	Thumbnail       sql.NullString  `json:"thumbnail"`
	CompletionKind  string          `json:"completion_kind"`
	Truncated       int64           `json:"truncated"`
	ID              int64           `json:"id"`
}

// See postgres/videos.sql MarkVideoDone for the completion_kind /
// truncated rationale.
func (q *Queries) MarkVideoDone(ctx context.Context, arg MarkVideoDoneParams) error {
	_, err := q.db.ExecContext(ctx, markVideoDone,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Thumbnail,
		arg.CompletionKind,
		arg.Truncated,
		arg.ID,
	)
	return err
}

const markVideoFailed = `-- name: MarkVideoFailed :exec
UPDATE videos SET
    status = 'FAILED',
    downloaded_at = datetime('now'),
    error = ?,
    completion_kind = ?,
    truncated = ?
WHERE id = ?
`

type MarkVideoFailedParams struct {
	Error          sql.NullString `json:"error"`
	CompletionKind string         `json:"completion_kind"`
	Truncated      int64          `json:"truncated"`
	ID             int64          `json:"id"`
}

// See postgres/videos.sql MarkVideoFailed for the completion_kind /
// truncated rationale.
func (q *Queries) MarkVideoFailed(ctx context.Context, arg MarkVideoFailedParams) error {
	_, err := q.db.ExecContext(ctx, markVideoFailed,
		arg.Error,
		arg.CompletionKind,
		arg.Truncated,
		arg.ID,
	)
	return err
}

const requestVideoDelete = `-- name: RequestVideoDelete :one
UPDATE videos
SET delete_requested_at = COALESCE(delete_requested_at, datetime('now'))
WHERE id = ?
  AND deleted_at IS NULL
  AND status IN ('DONE', 'FAILED')
RETURNING id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at
`

// Queue an operator-requested deletion. Idempotent for already-queued live
// terminal rows; active recordings must be cancelled first.
func (q *Queries) RequestVideoDelete(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, requestVideoDelete, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
		&i.Truncated,
		&i.TriggerScheduleID,
		&i.RetentionSourceScheduleID,
		&i.RetentionWindowHours,
		&i.DeletionKind,
		&i.DeleteRequestedAt,
	)
	return i, err
}

const searchVideos = `-- name: SearchVideos :many
WITH q AS (
    SELECT
        lower(CAST(?1 AS text)) AS term,
        lower(CAST(?1 AS text)) || '%' AS prefix,
        '%' || lower(CAST(?1 AS text)) || '%' AS contains,
        CAST(?2 AS integer) AS row_limit
),
title_matches AS (
    SELECT
        vt.video_id,
        MAX(lower(t.name) = q.term) AS title_exact,
        MAX(lower(t.name) LIKE q.prefix) AS title_prefix,
        MAX(lower(t.name) LIKE q.contains) AS title_contains
    FROM video_titles vt
    INNER JOIN titles t ON t.id = vt.title_id
    CROSS JOIN q
    GROUP BY vt.video_id
),
category_matches AS (
    SELECT
        vc.video_id,
        MAX(lower(c.name) = q.term) AS category_exact,
        MAX(lower(c.name) LIKE q.prefix) AS category_prefix,
        MAX(lower(c.name) LIKE q.contains) AS category_contains
    FROM video_categories vc
    INNER JOIN categories c ON c.id = vc.category_id
    CROSS JOIN q
    GROUP BY vc.video_id
),
matched AS (
    SELECT
        v.id,
        q.term = '' AS empty_query,
        lower(coalesce(v.title, '')) = q.term OR coalesce(tm.title_exact, 0) AS title_exact,
        lower(coalesce(v.title, '')) LIKE q.prefix OR coalesce(tm.title_prefix, 0) AS title_prefix,
        lower(coalesce(v.title, '')) LIKE q.contains OR coalesce(tm.title_contains, 0) AS title_contains,
        lower(coalesce(v.display_name, '')) = q.term
            OR lower(coalesce(ch.broadcaster_login, '')) = q.term
            OR lower(coalesce(ch.broadcaster_name, '')) = q.term AS channel_exact,
        lower(coalesce(v.display_name, '')) LIKE q.prefix
            OR lower(coalesce(ch.broadcaster_login, '')) LIKE q.prefix
            OR lower(coalesce(ch.broadcaster_name, '')) LIKE q.prefix AS channel_prefix,
        lower(coalesce(v.display_name, '')) LIKE q.contains
            OR lower(coalesce(ch.broadcaster_login, '')) LIKE q.contains
            OR lower(coalesce(ch.broadcaster_name, '')) LIKE q.contains AS channel_contains,
        coalesce(cm.category_exact, 0) AS category_exact,
        coalesce(cm.category_prefix, 0) AS category_prefix,
        coalesce(cm.category_contains, 0) AS category_contains
    FROM videos v
    CROSS JOIN q
    LEFT JOIN channels ch ON ch.broadcaster_id = v.broadcaster_id
    LEFT JOIN title_matches tm ON tm.video_id = v.id
    LEFT JOIN category_matches cm ON cm.video_id = v.id
    WHERE v.deleted_at IS NULL
)
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps, v.truncated, v.trigger_schedule_id, v.retention_source_schedule_id, v.retention_window_hours, v.deletion_kind, v.delete_requested_at FROM videos v
INNER JOIN matched m ON m.id = v.id
WHERE m.empty_query
   OR m.title_contains
   OR m.channel_contains
   OR m.category_contains
ORDER BY
    CASE
        WHEN m.empty_query THEN 7
        WHEN m.title_exact THEN 0
        WHEN m.title_prefix THEN 1
        WHEN m.channel_exact THEN 2
        WHEN m.channel_prefix THEN 3
        WHEN m.category_exact THEN 4
        WHEN m.category_prefix THEN 5
        ELSE 6
    END,
    v.start_download_at DESC,
    v.id DESC
LIMIT (SELECT row_limit FROM q)
`

type SearchVideosParams struct {
	Query    string `json:"query"`
	RowLimit int64  `json:"row_limit"`
}

func (q *Queries) SearchVideos(ctx context.Context, arg SearchVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, searchVideos, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoThumbnail = `-- name: SetVideoThumbnail :exec
UPDATE videos SET thumbnail = ? WHERE id = ?
`

type SetVideoThumbnailParams struct {
	Thumbnail sql.NullString `json:"thumbnail"`
	ID        int64          `json:"id"`
}

func (q *Queries) SetVideoThumbnail(ctx context.Context, arg SetVideoThumbnailParams) error {
	_, err := q.db.ExecContext(ctx, setVideoThumbnail, arg.Thumbnail, arg.ID)
	return err
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos
SET deleted_at = datetime('now'),
    deletion_kind = CASE
      WHEN delete_requested_at IS NOT NULL THEN 'manual'
      ELSE ?2
    END,
    delete_requested_at = NULL
WHERE id = ?1 AND deleted_at IS NULL
`

type SoftDeleteVideoParams struct {
	ID           int64          `json:"id"`
	DeletionKind sql.NullString `json:"deletion_kind"`
}

// Tombstone a recording. deletion_kind records why ('retention' | 'manual').
func (q *Queries) SoftDeleteVideo(ctx context.Context, arg SoftDeleteVideoParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteVideo, arg.ID, arg.DeletionKind)
	return err
}

const statisticsByStatus = `-- name: StatisticsByStatus :many
SELECT status, COUNT(*) AS count FROM videos WHERE deleted_at IS NULL GROUP BY status
`

type StatisticsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) StatisticsByStatus(ctx context.Context) ([]StatisticsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, statisticsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatisticsByStatusRow{}
	for rows.Next() {
		var i StatisticsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statisticsChannels = `-- name: StatisticsChannels :one
SELECT CAST(COUNT(DISTINCT broadcaster_id) AS INTEGER) AS channels
FROM videos
WHERE deleted_at IS NULL
`

func (q *Queries) StatisticsChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsChannels)
	var channels int64
	err := row.Scan(&channels)
	return channels, err
}

const statisticsIncomplete = `-- name: StatisticsIncomplete :one
SELECT CAST(COUNT(*) AS INTEGER) AS incomplete
FROM videos
WHERE deleted_at IS NULL AND (completion_kind = 'partial' OR truncated)
`

func (q *Queries) StatisticsIncomplete(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsIncomplete)
	var incomplete int64
	err := row.Scan(&incomplete)
	return incomplete, err
}

const statisticsRemoved = `-- name: StatisticsRemoved :one
SELECT CAST(COUNT(*) AS INTEGER) AS removed
FROM videos
WHERE deleted_at IS NOT NULL
`

// Count of tombstoned (removed) recordings; powers the History "Removed" tab.
func (q *Queries) StatisticsRemoved(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsRemoved)
	var removed int64
	err := row.Scan(&removed)
	return removed, err
}

const statisticsThisWeek = `-- name: StatisticsThisWeek :one
SELECT CAST(COUNT(*) AS INTEGER) AS this_week
FROM videos
WHERE deleted_at IS NULL AND start_download_at >= datetime('now', '-7 days')
`

func (q *Queries) StatisticsThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsThisWeek)
	var this_week int64
	err := row.Scan(&this_week)
	return this_week, err
}

const statisticsTotalsByBroadcaster = `-- name: StatisticsTotalsByBroadcaster :one
SELECT
    CAST(COUNT(*) AS INTEGER) AS total,
    CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) AS total_size,
    CAST(COALESCE(SUM(duration_seconds), 0) AS REAL) AS total_duration
FROM videos
WHERE broadcaster_id = ? AND status = 'DONE' AND deleted_at IS NUL
`

type StatisticsTotalsByBroadcasterRow struct {
	Total         int64   `json:"total"`
	TotalSize     int64   `json:"total_size"`
	TotalDuration float64 `json:"total_duration"`
}

// Per-channel rollup of finished recordings: count + summed bytes +
// summed duration. Mirrors StatisticsTotals scoped to one broadcaster
// so the watch page can render a "N recordings · X GB" line under the
// channel name without paginating the full library client-side.
func (q *Queries) StatisticsTotalsByBroadcaster(ctx context.Context, broadcasterID string) (StatisticsTotalsByBroadcasterRow, error) {
	row := q.db.QueryRowContext(ctx, statisticsTotalsByBroadcaster, broadcasterID)
	var i StatisticsTotalsByBroadcasterRow
	err := row.Scan(&i.Total, &i.TotalSize, &i.TotalDuration)
	return i, err
}

const statisticsTotalsDoneOnly = `-- name: StatisticsTotalsDoneOnly :one

SELECT
    CAST(COUNT(*) AS INTEGER) AS total,
    CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) AS total_size,
    CAST(COALESCE(SUM(duration_seconds), 0) AS REAL) AS total_duration
FROM videos WHERE status = 'DONE' AND deleted_at IS NULL
`

type StatisticsTotalsDoneOnlyRow struct {
	Total         int64   `json:"total"`
	TotalSize     int64   `json:"total_size"`
	TotalDuration float64 `json:"total_duration"`
}

// StatisticsTotals is split across four atomic queries instead of
// one combined SELECT. The combined form (with CASE WHEN aggregates
// in a multi-column SELECT list) triggers a sqlc-on-SQLite codegen
// bug that truncates trailing chars off subsequent query consts
// (StatisticsTotalsByBroadcaster ends up with `IS NUL` instead of
// `IS NULL`). Splitting keeps each query small enough that the
// parser doesn't trip; the adapter combines them into a single
// VideoStatsTotals struct. Postgres still uses the single-query
// form; see queries/postgres/videos.sql.
func (q *Queries) StatisticsTotalsDoneOnly(ctx context.Context) (StatisticsTotalsDoneOnlyRow, error) {
	row := q.db.QueryRowContext(ctx, statisticsTotalsDoneOnly)
	var i StatisticsTotalsDoneOnlyRow
	err := row.Scan(&i.Total, &i.TotalSize, &i.TotalDuration)
	return i, err
}

const statisticsUnwatched = `-- name: StatisticsUnwatched :one
SELECT CAST(COUNT(*) AS INTEGER) AS unwatched
FROM videos v
LEFT JOIN video_user_states vus
  ON vus.video_id = v.id AND vus.user_id = CAST(?1 AS text)
WHERE v.deleted_at IS NULL
  AND v.status = 'DONE'
  AND CAST(?1 AS text) <> ''
  AND vus.watched_at IS NULL
`

func (q *Queries) StatisticsUnwatched(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsUnwatched, userID)
	var unwatched int64
	err := row.Scan(&unwatched)
	return unwatched, err
}

const statisticsWatchLater = `-- name: StatisticsWatchLater :one
SELECT CAST(COUNT(*) AS INTEGER) AS watch_later
FROM videos v
INNER JOIN video_user_states vus ON vus.video_id = v.id
WHERE v.deleted_at IS NULL
  AND CAST(?1 AS text) <> ''
  AND vus.user_id = CAST(?1 AS text)
  AND vus.watch_later = 1
`

func (q *Queries) StatisticsWatchLater(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, statisticsWatchLater, userID)
	var watch_later int64
	err := row.Scan(&watch_later)
	return watch_later, err
}

const updateVideoSelectedVariant = `-- name: UpdateVideoSelectedVariant :exec
UPDATE videos SET
    selected_quality = ?,
    selected_fps = ?
WHERE id = ?
`

type UpdateVideoSelectedVariantParams struct {
	SelectedQuality sql.NullString  `json:"selected_quality"`
	SelectedFps     sql.NullFloat64 `json:"selected_fps"`
	ID              int64           `json:"id"`
}

func (q *Queries) UpdateVideoSelectedVariant(ctx context.Context, arg UpdateVideoSelectedVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoSelectedVariant, arg.SelectedQuality, arg.SelectedFps, arg.ID)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET status = ? WHERE id = ?
`

type UpdateVideoStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoStatus, arg.Status, arg.ID)
	return err
}
