// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_parts.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const countVideoParts = `-- name: CountVideoParts :one
SELECT COUNT(*) FROM video_parts WHERE video_id = ?
`

func (q *Queries) CountVideoParts(ctx context.Context, videoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideoParts, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideoPart = `-- name: CreateVideoPart :one
INSERT INTO video_parts (
    video_id, part_index, filename, quality, codec, segment_format,
    start_media_seq, end_media_seq
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at
`

type CreateVideoPartParams struct {
	VideoID       int64  `json:"video_id"`
	PartIndex     int64  `json:"part_index"`
	Filename      string `json:"filename"`
	Quality       string `json:"quality"`
	Codec         string `json:"codec"`
	SegmentFormat string `json:"segment_format"`
	StartMediaSeq int64  `json:"start_media_seq"`
	EndMediaSeq   int64  `json:"end_media_seq"`
}

func (q *Queries) CreateVideoPart(ctx context.Context, arg CreateVideoPartParams) (VideoPart, error) {
	row := q.db.QueryRowContext(ctx, createVideoPart,
		arg.VideoID,
		arg.PartIndex,
		arg.Filename,
		arg.Quality,
		arg.Codec,
		arg.SegmentFormat,
		arg.StartMediaSeq,
		arg.EndMediaSeq,
	)
	var i VideoPart
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PartIndex,
		&i.Filename,
		&i.Quality,
		&i.Codec,
		&i.SegmentFormat,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.StartMediaSeq,
		&i.EndMediaSeq,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVideoParts = `-- name: DeleteVideoParts :exec
DELETE FROM video_parts WHERE video_id = ?
`

func (q *Queries) DeleteVideoParts(ctx context.Context, videoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVideoParts, videoID)
	return err
}

const finalizeVideoPart = `-- name: FinalizeVideoPart :exec
UPDATE video_parts SET
    duration_seconds = ?,
    size_bytes = ?,
    thumbnail = ?,
    end_media_seq = ?
WHERE id = ?
`

type FinalizeVideoPartParams struct {
	DurationSeconds float64        `json:"duration_seconds"`
	SizeBytes       int64          `json:"size_bytes"`
	Thumbnail       sql.NullString `json:"thumbnail"`
	EndMediaSeq     int64          `json:"end_media_seq"`
	ID              int64          `json:"id"`
}

func (q *Queries) FinalizeVideoPart(ctx context.Context, arg FinalizeVideoPartParams) error {
	_, err := q.db.ExecContext(ctx, finalizeVideoPart,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Thumbnail,
		arg.EndMediaSeq,
		arg.ID,
	)
	return err
}

const getVideoPart = `-- name: GetVideoPart :one
SELECT id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at FROM video_parts WHERE id = ?
`

func (q *Queries) GetVideoPart(ctx context.Context, id int64) (VideoPart, error) {
	row := q.db.QueryRowContext(ctx, getVideoPart, id)
	var i VideoPart
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PartIndex,
		&i.Filename,
		&i.Quality,
		&i.Codec,
		&i.SegmentFormat,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.StartMediaSeq,
		&i.EndMediaSeq,
		&i.CreatedAt,
	)
	return i, err
}

const listVideoParts = `-- name: ListVideoParts :many
SELECT id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at FROM video_parts WHERE video_id = ? ORDER BY part_index ASC
`

func (q *Queries) ListVideoParts(ctx context.Context, videoID int64) ([]VideoPart, error) {
	rows, err := q.db.QueryContext(ctx, listVideoParts, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoPart{}
	for rows.Next() {
		var i VideoPart
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.PartIndex,
			&i.Filename,
			&i.Quality,
			&i.Codec,
			&i.SegmentFormat,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.StartMediaSeq,
			&i.EndMediaSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
