// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const countVideosByStatus = `-- name: CountVideosByStatus :one
SELECT COUNT(*) FROM videos WHERE status = ? AND deleted_at IS NULL
`

func (q *Queries) CountVideosByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVideosByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    job_id, filename, display_name, title, status, quality,
    broadcaster_id, stream_id, viewer_count, language, recording_type,
    force_h264
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps
`

type CreateVideoParams struct {
	JobID         string         `json:"job_id"`
	Filename      string         `json:"filename"`
	DisplayName   string         `json:"display_name"`
	Title         string         `json:"title"`
	Status        string         `json:"status"`
	Quality       string         `json:"quality"`
	BroadcasterID string         `json:"broadcaster_id"`
	StreamID      sql.NullString `json:"stream_id"`
	ViewerCount   int64          `json:"viewer_count"`
	Language      string         `json:"language"`
	RecordingType string         `json:"recording_type"`
	ForceH264     int64          `json:"force_h264"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.JobID,
		arg.Filename,
		arg.DisplayName,
		arg.Title,
		arg.Status,
		arg.Quality,
		arg.BroadcasterID,
		arg.StreamID,
		arg.ViewerCount,
		arg.Language,
		arg.RecordingType,
		arg.ForceH264,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps FROM videos WHERE id = ?
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
	)
	return i, err
}

const getVideoByJobID = `-- name: GetVideoByJobID :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps FROM videos WHERE job_id = ?
`

func (q *Queries) GetVideoByJobID(ctx context.Context, jobID string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByJobID, jobID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
	)
	return i, err
}

const listVideosByBroadcaster = `-- name: ListVideosByBroadcaster :many

SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps FROM videos
WHERE broadcaster_id = ? AND deleted_at IS NULL
ORDER BY start_download_at DESC
LIMIT ? OFFSET ?
`

type ListVideosByBroadcasterParams struct {
	BroadcasterID string `json:"broadcaster_id"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

// NOTE: ListVideos is intentionally NOT declared here. The PG path
// uses a CASE-based dynamic ORDER BY (see queries/postgres/videos.sql),
// but sqlc's SQLite engine can't infer the param type of a named arg
// referenced only inside CASE expressions, so the equivalent query is
// hand-rolled against the raw *sql.DB in
// internal/repository/sqliteadapter/videos.go.
func (q *Queries) ListVideosByBroadcaster(ctx context.Context, arg ListVideosByBroadcasterParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByBroadcaster, arg.BroadcasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByCategory = `-- name: ListVideosByCategory :many
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps FROM videos v
INNER JOIN video_categories vc ON vc.video_id = v.id
WHERE vc.category_id = ? AND v.deleted_at IS NULL
ORDER BY v.start_download_at DESC
LIMIT ? OFFSET ?
`

type ListVideosByCategoryParams struct {
	CategoryID string `json:"category_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListVideosByCategory(ctx context.Context, arg ListVideosByCategoryParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosMissingThumbnail = `-- name: ListVideosMissingThumbnail :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps FROM videos WHERE status = 'DONE' AND thumbnail IS NULL AND deleted_at IS NULL
`

func (q *Queries) ListVideosMissingThumbnail(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosMissingThumbnail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoDone = `-- name: MarkVideoDone :exec
UPDATE videos SET
    status = 'DONE',
    downloaded_at = datetime('now'),
    duration_seconds = ?,
    size_bytes = ?,
    thumbnail = ?,
    completion_kind = ?
WHERE id = ?
`

type MarkVideoDoneParams struct {
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	SizeBytes       sql.NullInt64   `json:"size_bytes"`
	Thumbnail       sql.NullString  `json:"thumbnail"`
	CompletionKind  string          `json:"completion_kind"`
	ID              int64           `json:"id"`
}

// See postgres/videos.sql MarkVideoDone for completion_kind rationale.
func (q *Queries) MarkVideoDone(ctx context.Context, arg MarkVideoDoneParams) error {
	_, err := q.db.ExecContext(ctx, markVideoDone,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Thumbnail,
		arg.CompletionKind,
		arg.ID,
	)
	return err
}

const markVideoFailed = `-- name: MarkVideoFailed :exec
UPDATE videos SET
    status = 'FAILED',
    downloaded_at = datetime('now'),
    error = ?,
    completion_kind = ?
WHERE id = ?
`

type MarkVideoFailedParams struct {
	Error          sql.NullString `json:"error"`
	CompletionKind string         `json:"completion_kind"`
	ID             int64          `json:"id"`
}

// See postgres/videos.sql MarkVideoFailed for completion_kind rationale.
func (q *Queries) MarkVideoFailed(ctx context.Context, arg MarkVideoFailedParams) error {
	_, err := q.db.ExecContext(ctx, markVideoFailed, arg.Error, arg.CompletionKind, arg.ID)
	return err
}

const setVideoThumbnail = `-- name: SetVideoThumbnail :exec
UPDATE videos SET thumbnail = ? WHERE id = ?
`

type SetVideoThumbnailParams struct {
	Thumbnail sql.NullString `json:"thumbnail"`
	ID        int64          `json:"id"`
}

func (q *Queries) SetVideoThumbnail(ctx context.Context, arg SetVideoThumbnailParams) error {
	_, err := q.db.ExecContext(ctx, setVideoThumbnail, arg.Thumbnail, arg.ID)
	return err
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos SET deleted_at = datetime('now') WHERE id = ?
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteVideo, id)
	return err
}

const statisticsByStatus = `-- name: StatisticsByStatus :many
SELECT status, COUNT(*) AS count FROM videos WHERE deleted_at IS NULL GROUP BY status
`

type StatisticsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) StatisticsByStatus(ctx context.Context) ([]StatisticsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, statisticsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatisticsByStatusRow{}
	for rows.Next() {
		var i StatisticsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statisticsTotals = `-- name: StatisticsTotals :one
SELECT
    CAST(COUNT(*) AS INTEGER) AS total,
    CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) AS total_size,
    CAST(COALESCE(SUM(duration_seconds), 0) AS REAL) AS total_duration
FROM videos WHERE status = 'DONE' AND deleted_at IS NULL
`

type StatisticsTotalsRow struct {
	Total         int64   `json:"total"`
	TotalSize     int64   `json:"total_size"`
	TotalDuration float64 `json:"total_duration"`
}

func (q *Queries) StatisticsTotals(ctx context.Context) (StatisticsTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, statisticsTotals)
	var i StatisticsTotalsRow
	err := row.Scan(&i.Total, &i.TotalSize, &i.TotalDuration)
	return i, err
}

const updateVideoSelectedVariant = `-- name: UpdateVideoSelectedVariant :exec
UPDATE videos SET
    selected_quality = ?,
    selected_fps = ?
WHERE id = ?
`

type UpdateVideoSelectedVariantParams struct {
	SelectedQuality sql.NullString  `json:"selected_quality"`
	SelectedFps     sql.NullFloat64 `json:"selected_fps"`
	ID              int64           `json:"id"`
}

func (q *Queries) UpdateVideoSelectedVariant(ctx context.Context, arg UpdateVideoSelectedVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoSelectedVariant, arg.SelectedQuality, arg.SelectedFps, arg.ID)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET status = ? WHERE id = ?
`

type UpdateVideoStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoStatus, arg.Status, arg.ID)
	return err
}
