// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package pggen

import (
	"context"
	"encoding/json"
	"time"
)

const deleteExpiredCategorySearchCache = `-- name: DeleteExpiredCategorySearchCache :exec
DELETE FROM category_search_cache WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredCategorySearchCache(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredCategorySearchCache, expiresAt)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoxArtUrl,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoxArtUrl,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategorySearchCache = `-- name: GetCategorySearchCache :one
SELECT normalized_query, category_ids, expires_at, last_accessed_at, created_at, updated_at FROM category_search_cache WHERE normalized_query = $1
`

func (q *Queries) GetCategorySearchCache(ctx context.Context, normalizedQuery string) (CategorySearchCache, error) {
	row := q.db.QueryRow(ctx, getCategorySearchCache, normalizedQuery)
	var i CategorySearchCache
	err := row.Scan(
		&i.NormalizedQuery,
		&i.CategoryIds,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByIDs = `-- name: ListCategoriesByIDs :many
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories WHERE id = ANY($1::text[])
`

func (q *Queries) ListCategoriesByIDs(ctx context.Context, ids []string) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesMissingBoxArt = `-- name: ListCategoriesMissingBoxArt :many
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories WHERE box_art_url IS NULL OR box_art_url = ''
`

func (q *Queries) ListCategoriesMissingBoxArt(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesMissingBoxArt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithVideos = `-- name: ListCategoriesWithVideos :many
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at FROM categories c
WHERE EXISTS (
    SELECT 1
    FROM video_categories vc
    INNER JOIN videos v ON v.id = vc.video_id
    WHERE vc.category_id = c.id
      AND v.deleted_at IS NULL
)
ORDER BY c.name
`

// Browse/library list: categories must be linked to at least one visible
// recording. Twitch search can mirror catalog-only rows into categories; those
// should stay out of the category page until a video actually references them.
func (q *Queries) ListCategoriesWithVideos(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithVideosPageLatestDesc = `-- name: ListCategoriesWithVideosPageLatestDesc :many
WITH category_stats AS (
    SELECT
        vc.category_id,
        MAX(v.start_download_at) AS latest_video_at,
        COUNT(DISTINCT vc.video_id)::bigint AS video_count
    FROM video_categories vc
    INNER JOIN videos v ON v.id = vc.video_id
    WHERE v.deleted_at IS NULL
    GROUP BY vc.category_id
)
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at, category_stats.latest_video_at, category_stats.video_count
FROM categories c
INNER JOIN category_stats ON category_stats.category_id = c.id
WHERE (
    $1::timestamptz IS NULL
    OR category_stats.latest_video_at < $1::timestamptz
    OR (
        category_stats.latest_video_at = $1::timestamptz
        AND lower(c.name) > lower($2::text)
    )
    OR (
        category_stats.latest_video_at = $1::timestamptz
        AND lower(c.name) = lower($2::text)
        AND c.id > $3::text
    )
)
ORDER BY category_stats.latest_video_at DESC, lower(c.name) ASC, c.id ASC
LIMIT $4
`

type ListCategoriesWithVideosPageLatestDescParams struct {
	CursorLatestVideoAt *time.Time `json:"cursor_latest_video_at"`
	CursorName          *string    `json:"cursor_name"`
	CursorID            string     `json:"cursor_id"`
	RowLimit            int32      `json:"row_limit"`
}

type ListCategoriesWithVideosPageLatestDescRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	BoxArtUrl     *string     `json:"box_art_url"`
	IgdbID        *string     `json:"igdb_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	LatestVideoAt interface{} `json:"latest_video_at"`
	VideoCount    int64       `json:"video_count"`
}

func (q *Queries) ListCategoriesWithVideosPageLatestDesc(ctx context.Context, arg ListCategoriesWithVideosPageLatestDescParams) ([]ListCategoriesWithVideosPageLatestDescRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithVideosPageLatestDesc,
		arg.CursorLatestVideoAt,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithVideosPageLatestDescRow{}
	for rows.Next() {
		var i ListCategoriesWithVideosPageLatestDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVideoAt,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithVideosPageNameAsc = `-- name: ListCategoriesWithVideosPageNameAsc :many
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at FROM categories c
WHERE EXISTS (
    SELECT 1
    FROM video_categories vc
    INNER JOIN videos v ON v.id = vc.video_id
    WHERE vc.category_id = c.id
      AND v.deleted_at IS NULL
)
  AND (
    $1::text IS NULL
    OR lower(c.name) > lower($1::text)
    OR (lower(c.name) = lower($1::text) AND c.id > $2::text)
  )
ORDER BY lower(c.name) ASC, c.id ASC
LIMIT $3
`

type ListCategoriesWithVideosPageNameAscParams struct {
	CursorName *string `json:"cursor_name"`
	CursorID   string  `json:"cursor_id"`
	RowLimit   int32   `json:"row_limit"`
}

// Cursor-paginated browse list for the default category order. This mirrors
// ListCategoriesWithVideos' visibility predicate while over-fetching at the
// adapter layer to discover the next cursor.
func (q *Queries) ListCategoriesWithVideosPageNameAsc(ctx context.Context, arg ListCategoriesWithVideosPageNameAscParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithVideosPageNameAsc, arg.CursorName, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithVideosPageVideoCountDesc = `-- name: ListCategoriesWithVideosPageVideoCountDesc :many
WITH category_stats AS (
    SELECT
        vc.category_id,
        MAX(v.start_download_at) AS latest_video_at,
        COUNT(DISTINCT vc.video_id)::bigint AS video_count
    FROM video_categories vc
    INNER JOIN videos v ON v.id = vc.video_id
    WHERE v.deleted_at IS NULL
    GROUP BY vc.category_id
)
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at, category_stats.latest_video_at, category_stats.video_count
FROM categories c
INNER JOIN category_stats ON category_stats.category_id = c.id
WHERE (
    $1::text IS NULL
    OR category_stats.video_count < $2::bigint
    OR (
        category_stats.video_count = $2::bigint
        AND lower(c.name) > lower($1::text)
    )
    OR (
        category_stats.video_count = $2::bigint
        AND lower(c.name) = lower($1::text)
        AND c.id > $3::text
    )
)
ORDER BY category_stats.video_count DESC, lower(c.name) ASC, c.id ASC
LIMIT $4
`

type ListCategoriesWithVideosPageVideoCountDescParams struct {
	CursorName       *string `json:"cursor_name"`
	CursorVideoCount int64   `json:"cursor_video_count"`
	CursorID         string  `json:"cursor_id"`
	RowLimit         int32   `json:"row_limit"`
}

type ListCategoriesWithVideosPageVideoCountDescRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	BoxArtUrl     *string     `json:"box_art_url"`
	IgdbID        *string     `json:"igdb_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	LatestVideoAt interface{} `json:"latest_video_at"`
	VideoCount    int64       `json:"video_count"`
}

func (q *Queries) ListCategoriesWithVideosPageVideoCountDesc(ctx context.Context, arg ListCategoriesWithVideosPageVideoCountDescParams) ([]ListCategoriesWithVideosPageVideoCountDescRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithVideosPageVideoCountDesc,
		arg.CursorName,
		arg.CursorVideoCount,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithVideosPageVideoCountDescRow{}
	for rows.Next() {
		var i ListCategoriesWithVideosPageVideoCountDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVideoAt,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCategorySearchCache = `-- name: PruneCategorySearchCache :exec
DELETE FROM category_search_cache
WHERE normalized_query IN (
    SELECT normalized_query
    FROM category_search_cache
    ORDER BY last_accessed_at DESC, updated_at DESC, normalized_query ASC
    OFFSET $1
)
`

func (q *Queries) PruneCategorySearchCache(ctx context.Context, offset int32) error {
	_, err := q.db.Exec(ctx, pruneCategorySearchCache, offset)
	return err
}

const searchCategories = `-- name: SearchCategories :many
SELECT id, name, box_art_url, igdb_id, created_at, updated_at FROM categories
WHERE $1::text = ''
   OR lower(name) LIKE '%' || lower($1::text) || '%'
ORDER BY
    CASE
        WHEN $1::text = '' THEN 3
        WHEN lower(name) = lower($1::text) THEN 0
        WHEN lower(name) LIKE lower($1::text) || '%' THEN 1
        ELSE 2
    END,
    name
LIMIT $2
`

type SearchCategoriesParams struct {
	Query    string `json:"query"`
	RowLimit int32  `json:"row_limit"`
}

// Case-insensitive substring match on name. Ranks exact name match
// first, then prefix match, then substring match, then alphabetical.
// Mirrors queries/postgres/channels.sql SearchChannels so both
// combobox-backed dropdowns (schedule form channel picker + category
// picker) share a ranking contract. Empty query returns everything
// up to row_limit, so the same endpoint backs the "show all" state.
func (q *Queries) SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, searchCategories, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategoriesWithVideos = `-- name: SearchCategoriesWithVideos :many
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at FROM categories c
WHERE ($1::text = ''
       OR lower(c.name) LIKE '%' || lower($1::text) || '%')
  AND EXISTS (
      SELECT 1
      FROM video_categories vc
      INNER JOIN videos v ON v.id = vc.video_id
      WHERE vc.category_id = c.id
        AND v.deleted_at IS NULL
  )
ORDER BY
    CASE
        WHEN $1::text = '' THEN 3
        WHEN lower(c.name) = lower($1::text) THEN 0
        WHEN lower(c.name) LIKE lower($1::text) || '%' THEN 1
        ELSE 2
    END,
    c.name
LIMIT $2
`

type SearchCategoriesWithVideosParams struct {
	Query    string `json:"query"`
	RowLimit int32  `json:"row_limit"`
}

// Same ranking contract as SearchCategories, restricted to categories linked to
// at least one visible recording.
func (q *Queries) SearchCategoriesWithVideos(ctx context.Context, arg SearchCategoriesWithVideosParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, searchCategoriesWithVideos, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCategorySearchCache = `-- name: TouchCategorySearchCache :exec
UPDATE category_search_cache
SET last_accessed_at = $2,
    updated_at = NOW()
WHERE normalized_query = $1
`

type TouchCategorySearchCacheParams struct {
	NormalizedQuery string    `json:"normalized_query"`
	LastAccessedAt  time.Time `json:"last_accessed_at"`
}

func (q *Queries) TouchCategorySearchCache(ctx context.Context, arg TouchCategorySearchCacheParams) error {
	_, err := q.db.Exec(ctx, touchCategorySearchCache, arg.NormalizedQuery, arg.LastAccessedAt)
	return err
}

const updateCategoryBoxArt = `-- name: UpdateCategoryBoxArt :exec
UPDATE categories SET box_art_url = $2, updated_at = NOW() WHERE id = $1
`

type UpdateCategoryBoxArtParams struct {
	ID        string  `json:"id"`
	BoxArtUrl *string `json:"box_art_url"`
}

// Dedicated setter for box_art_url. Used by the category-art sync
// task and the Hydrator's eager enrichment; separates "refresh just
// the art" from the broader UpsertCategory contract.
func (q *Queries) UpdateCategoryBoxArt(ctx context.Context, arg UpdateCategoryBoxArtParams) error {
	_, err := q.db.Exec(ctx, updateCategoryBoxArt, arg.ID, arg.BoxArtUrl)
	return err
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO categories (id, name, box_art_url, igdb_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    -- NULLIF normalizes an explicit empty-string payload to NULL
    -- before COALESCE decides, so a caller passing &"" can't wipe
    -- the existing art any more than a nil caller can.
    box_art_url = COALESCE(NULLIF(EXCLUDED.box_art_url, ''), categories.box_art_url),
    igdb_id = COALESCE(NULLIF(EXCLUDED.igdb_id, ''), categories.igdb_id),
    updated_at = NOW()
RETURNING id, name, box_art_url, igdb_id, created_at, updated_at
`

type UpsertCategoryParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	BoxArtUrl *string `json:"box_art_url"`
	IgdbID    *string `json:"igdb_id"`
}

// Preserves box_art_url and igdb_id on conflict: a webhook-path
// upsert that only knows (id, name) won't wipe values the
// category-art sync has filled. COALESCE picks the existing row
// value when the caller passed NULL. UpdateCategoryBoxArt below is
// the explicit path to actively change the art.
func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, upsertCategory,
		arg.ID,
		arg.Name,
		arg.BoxArtUrl,
		arg.IgdbID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BoxArtUrl,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategorySearchCache = `-- name: UpsertCategorySearchCache :one
INSERT INTO category_search_cache (normalized_query, category_ids, expires_at, last_accessed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (normalized_query) DO UPDATE SET
    category_ids = EXCLUDED.category_ids,
    expires_at = EXCLUDED.expires_at,
    last_accessed_at = EXCLUDED.last_accessed_at,
    updated_at = NOW()
RETURNING normalized_query, category_ids, expires_at, last_accessed_at, created_at, updated_at
`

type UpsertCategorySearchCacheParams struct {
	NormalizedQuery string          `json:"normalized_query"`
	CategoryIds     json.RawMessage `json:"category_ids"`
	ExpiresAt       time.Time       `json:"expires_at"`
	LastAccessedAt  time.Time       `json:"last_accessed_at"`
}

func (q *Queries) UpsertCategorySearchCache(ctx context.Context, arg UpsertCategorySearchCacheParams) (CategorySearchCache, error) {
	row := q.db.QueryRow(ctx, upsertCategorySearchCache,
		arg.NormalizedQuery,
		arg.CategoryIds,
		arg.ExpiresAt,
		arg.LastAccessedAt,
	)
	var i CategorySearchCache
	err := row.Scan(
		&i.NormalizedQuery,
		&i.CategoryIds,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
