// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package pggen

import (
	"context"
	"time"
)

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE broadcaster_id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, broadcasterID string) error {
	_, err := q.db.Exec(ctx, deleteChannel, broadcasterID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_id = $1
`

func (q *Queries) GetChannel(ctx context.Context, broadcasterID string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, broadcasterID)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByLogin = `-- name: GetChannelByLogin :one
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_login = $1
`

func (q *Queries) GetChannelByLogin(ctx context.Context, broadcasterLogin string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByLogin, broadcasterLogin)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels ORDER BY broadcaster_login
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByIDs = `-- name: ListChannelsByIDs :many
SELECT broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at FROM channels WHERE broadcaster_id = ANY($1::text[])
`

func (q *Queries) ListChannelsByIDs(ctx context.Context, ids []string) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFollows = `-- name: ListUserFollows :many
SELECT c.broadcaster_id, c.broadcaster_login, c.broadcaster_name, c.broadcaster_language, c.profile_image_url, c.offline_image_url, c.description, c.broadcaster_type, c.view_count, c.created_at, c.updated_at FROM channels c
INNER JOIN user_followed_channels ufc ON ufc.broadcaster_id = c.broadcaster_id
WHERE ufc.user_id = $1 AND ufc.followed = TRUE
ORDER BY c.broadcaster_login
`

func (q *Queries) ListUserFollows(ctx context.Context, userID string) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listUserFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.BroadcasterLanguage,
			&i.ProfileImageUrl,
			&i.OfflineImageUrl,
			&i.Description,
			&i.BroadcasterType,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowChannel = `-- name: UnfollowChannel :exec
UPDATE user_followed_channels SET followed = FALSE WHERE user_id = $1 AND broadcaster_id = $2
`

type UnfollowChannelParams struct {
	UserID        string `json:"user_id"`
	BroadcasterID string `json:"broadcaster_id"`
}

func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) error {
	_, err := q.db.Exec(ctx, unfollowChannel, arg.UserID, arg.BroadcasterID)
	return err
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (
    broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language,
    profile_image_url, offline_image_url, description, broadcaster_type, view_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (broadcaster_id) DO UPDATE SET
    broadcaster_login = EXCLUDED.broadcaster_login,
    broadcaster_name = EXCLUDED.broadcaster_name,
    broadcaster_language = EXCLUDED.broadcaster_language,
    profile_image_url = EXCLUDED.profile_image_url,
    offline_image_url = EXCLUDED.offline_image_url,
    description = EXCLUDED.description,
    broadcaster_type = EXCLUDED.broadcaster_type,
    view_count = EXCLUDED.view_count,
    updated_at = NOW()
RETURNING broadcaster_id, broadcaster_login, broadcaster_name, broadcaster_language, profile_image_url, offline_image_url, description, broadcaster_type, view_count, created_at, updated_at
`

type UpsertChannelParams struct {
	BroadcasterID       string  `json:"broadcaster_id"`
	BroadcasterLogin    string  `json:"broadcaster_login"`
	BroadcasterName     string  `json:"broadcaster_name"`
	BroadcasterLanguage *string `json:"broadcaster_language"`
	ProfileImageUrl     *string `json:"profile_image_url"`
	OfflineImageUrl     *string `json:"offline_image_url"`
	Description         *string `json:"description"`
	BroadcasterType     *string `json:"broadcaster_type"`
	ViewCount           int32   `json:"view_count"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.BroadcasterID,
		arg.BroadcasterLogin,
		arg.BroadcasterName,
		arg.BroadcasterLanguage,
		arg.ProfileImageUrl,
		arg.OfflineImageUrl,
		arg.Description,
		arg.BroadcasterType,
		arg.ViewCount,
	)
	var i Channel
	err := row.Scan(
		&i.BroadcasterID,
		&i.BroadcasterLogin,
		&i.BroadcasterName,
		&i.BroadcasterLanguage,
		&i.ProfileImageUrl,
		&i.OfflineImageUrl,
		&i.Description,
		&i.BroadcasterType,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFollow = `-- name: UpsertUserFollow :exec
INSERT INTO user_followed_channels (user_id, broadcaster_id, followed_at, followed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, broadcaster_id) DO UPDATE SET
    followed_at = EXCLUDED.followed_at,
    followed = EXCLUDED.followed
`

type UpsertUserFollowParams struct {
	UserID        string    `json:"user_id"`
	BroadcasterID string    `json:"broadcaster_id"`
	FollowedAt    time.Time `json:"followed_at"`
	Followed      bool      `json:"followed"`
}

func (q *Queries) UpsertUserFollow(ctx context.Context, arg UpsertUserFollowParams) error {
	_, err := q.db.Exec(ctx, upsertUserFollow,
		arg.UserID,
		arg.BroadcasterID,
		arg.FollowedAt,
		arg.Followed,
	)
	return err
}
