// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"encoding/json"
	"time"
)

type AppAccessToken struct {
	ID        int64     `json:"id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Category struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	BoxArtUrl *string   `json:"box_art_url"`
	IgdbID    *string   `json:"igdb_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Channel struct {
	BroadcasterID       string    `json:"broadcaster_id"`
	BroadcasterLogin    string    `json:"broadcaster_login"`
	BroadcasterName     string    `json:"broadcaster_name"`
	BroadcasterLanguage *string   `json:"broadcaster_language"`
	ProfileImageUrl     *string   `json:"profile_image_url"`
	OfflineImageUrl     *string   `json:"offline_image_url"`
	Description         *string   `json:"description"`
	BroadcasterType     *string   `json:"broadcaster_type"`
	ViewCount           int32     `json:"view_count"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type DownloadSchedule struct {
	ID               int64      `json:"id"`
	BroadcasterID    string     `json:"broadcaster_id"`
	RequestedBy      string     `json:"requested_by"`
	Quality          string     `json:"quality"`
	HasMinViewers    bool       `json:"has_min_viewers"`
	MinViewers       *int32     `json:"min_viewers"`
	HasCategories    bool       `json:"has_categories"`
	HasTags          bool       `json:"has_tags"`
	IsDeleteRediff   bool       `json:"is_delete_rediff"`
	TimeBeforeDelete *int32     `json:"time_before_delete"`
	IsDisabled       bool       `json:"is_disabled"`
	LastTriggeredAt  *time.Time `json:"last_triggered_at"`
	TriggerCount     int64      `json:"trigger_count"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type DownloadScheduleCategory struct {
	ScheduleID int64  `json:"schedule_id"`
	CategoryID string `json:"category_id"`
}

type DownloadScheduleTag struct {
	ScheduleID int64 `json:"schedule_id"`
	TagID      int64 `json:"tag_id"`
}

type EventLog struct {
	ID           int64           `json:"id"`
	Domain       string          `json:"domain"`
	EventType    string          `json:"event_type"`
	Severity     string          `json:"severity"`
	Message      string          `json:"message"`
	ActorUserID  *string         `json:"actor_user_id"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    time.Time       `json:"created_at"`
	SearchVector interface{}     `json:"search_vector"`
}

type EventsubSnapshot struct {
	ID           int64     `json:"id"`
	Total        int32     `json:"total"`
	TotalCost    int32     `json:"total_cost"`
	MaxTotalCost int32     `json:"max_total_cost"`
	FetchedAt    time.Time `json:"fetched_at"`
}

type FetchLog struct {
	ID            int64     `json:"id"`
	UserID        *string   `json:"user_id"`
	FetchType     string    `json:"fetch_type"`
	BroadcasterID *string   `json:"broadcaster_id"`
	Status        int32     `json:"status"`
	Error         *string   `json:"error"`
	DurationMs    int32     `json:"duration_ms"`
	FetchedAt     time.Time `json:"fetched_at"`
}

type Job struct {
	ID            string          `json:"id"`
	VideoID       int64           `json:"video_id"`
	BroadcasterID string          `json:"broadcaster_id"`
	Status        string          `json:"status"`
	StartedAt     *time.Time      `json:"started_at"`
	FinishedAt    *time.Time      `json:"finished_at"`
	Error         *string         `json:"error"`
	ResumeState   json.RawMessage `json:"resume_state"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Session struct {
	HashedID        string    `json:"hashed_id"`
	UserID          string    `json:"user_id"`
	EncryptedTokens []byte    `json:"encrypted_tokens"`
	ExpiresAt       time.Time `json:"expires_at"`
	LastActiveAt    time.Time `json:"last_active_at"`
	UserAgent       *string   `json:"user_agent"`
	IpAddress       *string   `json:"ip_address"`
	CreatedAt       time.Time `json:"created_at"`
}

type Setting struct {
	UserID         string    `json:"user_id"`
	Timezone       string    `json:"timezone"`
	DatetimeFormat string    `json:"datetime_format"`
	Language       string    `json:"language"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type SnapshotSubscription struct {
	SnapshotID       int64  `json:"snapshot_id"`
	SubscriptionID   string `json:"subscription_id"`
	CostAtSnapshot   int32  `json:"cost_at_snapshot"`
	StatusAtSnapshot string `json:"status_at_snapshot"`
}

type Stream struct {
	ID            string     `json:"id"`
	BroadcasterID string     `json:"broadcaster_id"`
	Type          string     `json:"type"`
	Language      string     `json:"language"`
	ThumbnailUrl  *string    `json:"thumbnail_url"`
	ViewerCount   int32      `json:"viewer_count"`
	IsMature      *bool      `json:"is_mature"`
	StartedAt     time.Time  `json:"started_at"`
	EndedAt       *time.Time `json:"ended_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type StreamCategory struct {
	StreamID   string `json:"stream_id"`
	CategoryID string `json:"category_id"`
}

type StreamTag struct {
	StreamID string `json:"stream_id"`
	TagID    int64  `json:"tag_id"`
}

type StreamTitle struct {
	StreamID string `json:"stream_id"`
	TitleID  int64  `json:"title_id"`
}

type Subscription struct {
	ID                string          `json:"id"`
	Status            string          `json:"status"`
	Type              string          `json:"type"`
	Version           string          `json:"version"`
	Cost              int32           `json:"cost"`
	Condition         json.RawMessage `json:"condition"`
	BroadcasterID     *string         `json:"broadcaster_id"`
	TransportMethod   string          `json:"transport_method"`
	TransportCallback string          `json:"transport_callback"`
	TwitchCreatedAt   time.Time       `json:"twitch_created_at"`
	CreatedAt         time.Time       `json:"created_at"`
	RevokedAt         *time.Time      `json:"revoked_at"`
	RevokedReason     *string         `json:"revoked_reason"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	IntervalSeconds int32      `json:"interval_seconds"`
	IsEnabled       bool       `json:"is_enabled"`
	LastRunAt       *time.Time `json:"last_run_at"`
	LastDurationMs  int32      `json:"last_duration_ms"`
	LastStatus      string     `json:"last_status"`
	LastError       *string    `json:"last_error"`
	NextRunAt       *time.Time `json:"next_run_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type Title struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              string    `json:"id"`
	Login           string    `json:"login"`
	DisplayName     string    `json:"display_name"`
	Email           *string   `json:"email"`
	ProfileImageUrl *string   `json:"profile_image_url"`
	Role            string    `json:"role"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type UserFollowedChannel struct {
	UserID        string    `json:"user_id"`
	BroadcasterID string    `json:"broadcaster_id"`
	FollowedAt    time.Time `json:"followed_at"`
	Followed      bool      `json:"followed"`
}

type Video struct {
	ID              int64      `json:"id"`
	JobID           string     `json:"job_id"`
	Filename        string     `json:"filename"`
	DisplayName     string     `json:"display_name"`
	Status          string     `json:"status"`
	Quality         string     `json:"quality"`
	BroadcasterID   string     `json:"broadcaster_id"`
	StreamID        *string    `json:"stream_id"`
	ViewerCount     int32      `json:"viewer_count"`
	Language        string     `json:"language"`
	DurationSeconds *float64   `json:"duration_seconds"`
	SizeBytes       *int64     `json:"size_bytes"`
	Thumbnail       *string    `json:"thumbnail"`
	Error           *string    `json:"error"`
	StartDownloadAt time.Time  `json:"start_download_at"`
	DownloadedAt    *time.Time `json:"downloaded_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	RecordingType   string     `json:"recording_type"`
	ForceH264       bool       `json:"force_h264"`
	Title           string     `json:"title"`
	CompletionKind  string     `json:"completion_kind"`
	SelectedQuality *string    `json:"selected_quality"`
	SelectedFps     *float64   `json:"selected_fps"`
}

type VideoCategory struct {
	VideoID    int64  `json:"video_id"`
	CategoryID string `json:"category_id"`
}

type VideoPart struct {
	ID              int64     `json:"id"`
	VideoID         int64     `json:"video_id"`
	PartIndex       int32     `json:"part_index"`
	Filename        string    `json:"filename"`
	Quality         string    `json:"quality"`
	Codec           string    `json:"codec"`
	SegmentFormat   string    `json:"segment_format"`
	DurationSeconds float64   `json:"duration_seconds"`
	SizeBytes       int64     `json:"size_bytes"`
	Thumbnail       *string   `json:"thumbnail"`
	StartMediaSeq   int64     `json:"start_media_seq"`
	EndMediaSeq     *int64    `json:"end_media_seq"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Fps             *float64  `json:"fps"`
}

type VideoRequest struct {
	VideoID     int64     `json:"video_id"`
	UserID      string    `json:"user_id"`
	RequestedAt time.Time `json:"requested_at"`
}

type VideoTag struct {
	VideoID int64 `json:"video_id"`
	TagID   int64 `json:"tag_id"`
}

type VideoTitle struct {
	VideoID  int64     `json:"video_id"`
	TitleID  int64     `json:"title_id"`
	LinkedAt time.Time `json:"linked_at"`
}

type WebhookEvent struct {
	ID               int64           `json:"id"`
	EventID          string          `json:"event_id"`
	MessageType      string          `json:"message_type"`
	EventType        *string         `json:"event_type"`
	SubscriptionID   *string         `json:"subscription_id"`
	BroadcasterID    *string         `json:"broadcaster_id"`
	MessageTimestamp time.Time       `json:"message_timestamp"`
	Payload          json.RawMessage `json:"payload"`
	Status           string          `json:"status"`
	Error            *string         `json:"error"`
	ReceivedAt       time.Time       `json:"received_at"`
	ProcessedAt      *time.Time      `json:"processed_at"`
}

type Whitelist struct {
	TwitchUserID string    `json:"twitch_user_id"`
	AddedAt      time.Time `json:"added_at"`
}
