// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recording_execution.sql

package pggen

import (
	"context"
	"encoding/json"
	"time"
)

const checkpointAttempt = `-- name: CheckpointAttempt :execrows
UPDATE jobs SET resume_state = $3, updated_at = NOW()
WHERE jobs.id = $1 AND jobs.execution_id = $2 AND jobs.status = 'RUNNING'
  AND EXISTS (SELECT 1 FROM videos WHERE videos.id = jobs.video_id
      AND videos.job_id = jobs.id AND videos.status = 'RUNNING' AND videos.deleted_at IS NULL)
`

type CheckpointAttemptParams struct {
	ID          string          `json:"id"`
	ExecutionID string          `json:"execution_id"`
	ResumeState json.RawMessage `json:"resume_state"`
}

func (q *Queries) CheckpointAttempt(ctx context.Context, arg CheckpointAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, checkpointAttempt, arg.ID, arg.ExecutionID, arg.ResumeState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVideoForUpdate = `-- name: GetVideoForUpdate :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at, recording_type, force_h264, title, completion_kind, selected_quality, selected_fps, truncated, trigger_schedule_id, retention_source_schedule_id, retention_window_hours, deletion_kind, delete_requested_at, source, twitch_video_id, broadcast_at, next_retry_at FROM videos WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetVideoForUpdate(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoForUpdate, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
		&i.RecordingType,
		&i.ForceH264,
		&i.Title,
		&i.CompletionKind,
		&i.SelectedQuality,
		&i.SelectedFps,
		&i.Truncated,
		&i.TriggerScheduleID,
		&i.RetentionSourceScheduleID,
		&i.RetentionWindowHours,
		&i.DeletionKind,
		&i.DeleteRequestedAt,
		&i.Source,
		&i.TwitchVideoID,
		&i.BroadcastAt,
		&i.NextRetryAt,
	)
	return i, err
}

const listQueuedArchiveJobs = `-- name: ListQueuedArchiveJobs :many
SELECT jobs.id AS job_id, videos.id AS video_id, videos.start_download_at AS queued_at FROM jobs JOIN videos ON videos.id = jobs.video_id AND videos.job_id = jobs.id
WHERE jobs.status = 'PENDING' AND videos.status = 'PENDING' AND videos.source = 'vod' AND videos.deleted_at IS NULL
AND (videos.start_download_at > $1 OR (videos.start_download_at = $1 AND videos.id > CAST($2 AS BIGINT)))
ORDER BY videos.start_download_at, videos.id LIMIT $3
`

type ListQueuedArchiveJobsParams struct {
	AfterStart time.Time `json:"after_start"`
	AfterID    int64     `json:"after_id"`
	BatchLimit int32     `json:"batch_limit"`
}

type ListQueuedArchiveJobsRow struct {
	JobID    string    `json:"job_id"`
	VideoID  int64     `json:"video_id"`
	QueuedAt time.Time `json:"queued_at"`
}

func (q *Queries) ListQueuedArchiveJobs(ctx context.Context, arg ListQueuedArchiveJobsParams) ([]ListQueuedArchiveJobsRow, error) {
	rows, err := q.db.Query(ctx, listQueuedArchiveJobs, arg.AfterStart, arg.AfterID, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueuedArchiveJobsRow{}
	for rows.Next() {
		var i ListQueuedArchiveJobsRow
		if err := rows.Scan(&i.JobID, &i.VideoID, &i.QueuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryJobs = `-- name: ListRecoveryJobs :many
SELECT jobs.id, jobs.video_id, jobs.broadcaster_id, jobs.status, jobs.started_at, jobs.finished_at, jobs.error, jobs.resume_state, jobs.created_at, jobs.updated_at, jobs.attempt, jobs.execution_id, jobs.accepts_metadata, jobs.stop_requested FROM jobs JOIN videos ON videos.id = jobs.video_id AND videos.job_id = jobs.id
WHERE jobs.id > $1 AND (jobs.status = 'RUNNING' OR (jobs.status = 'PENDING' AND videos.source = 'live'))
  AND videos.status IN ('PENDING', 'RUNNING') AND videos.deleted_at IS NULL
ORDER BY jobs.id LIMIT $2
`

type ListRecoveryJobsParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRecoveryJobs(ctx context.Context, arg ListRecoveryJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listRecoveryJobs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.BroadcasterID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.ResumeState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attempt,
			&i.ExecutionID,
			&i.AcceptsMetadata,
			&i.StopRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoppedJobs = `-- name: ListStoppedJobs :many
SELECT jobs.id, jobs.video_id, jobs.broadcaster_id, jobs.status, jobs.started_at, jobs.finished_at, jobs.error, jobs.resume_state, jobs.created_at, jobs.updated_at, jobs.attempt, jobs.execution_id, jobs.accepts_metadata, jobs.stop_requested FROM jobs JOIN videos ON videos.id = jobs.video_id AND videos.job_id = jobs.id
WHERE jobs.id > $1 AND jobs.stop_requested AND jobs.status IN ('PENDING', 'RUNNING')
  AND videos.status IN ('PENDING', 'RUNNING') AND videos.deleted_at IS NULL
ORDER BY jobs.id LIMIT $2
`

type ListStoppedJobsParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListStoppedJobs(ctx context.Context, arg ListStoppedJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listStoppedJobs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.BroadcasterID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.ResumeState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attempt,
			&i.ExecutionID,
			&i.AcceptsMetadata,
			&i.StopRequested,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestJobStop = `-- name: RequestJobStop :exec
UPDATE jobs SET stop_requested = TRUE, accepts_metadata = FALSE, updated_at = NOW()
WHERE id = $1 AND status IN ('PENDING', 'RUNNING')
`

func (q *Queries) RequestJobStop(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, requestJobStop, id)
	return err
}

const setJobExecution = `-- name: SetJobExecution :execrows
UPDATE jobs SET execution_id = $2, accepts_metadata = $3,
    status = 'RUNNING', started_at = COALESCE(started_at, NOW()), updated_at = NOW()
WHERE id = $1 AND status IN ('PENDING', 'RUNNING')
`

type SetJobExecutionParams struct {
	ID              string `json:"id"`
	ExecutionID     string `json:"execution_id"`
	AcceptsMetadata bool   `json:"accepts_metadata"`
}

func (q *Queries) SetJobExecution(ctx context.Context, arg SetJobExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJobExecution, arg.ID, arg.ExecutionID, arg.AcceptsMetadata)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopJobMetadata = `-- name: StopJobMetadata :execrows
UPDATE jobs SET accepts_metadata = FALSE
WHERE id = $1 AND execution_id = $2 AND status = 'RUNNING'
`

type StopJobMetadataParams struct {
	ID          string `json:"id"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) StopJobMetadata(ctx context.Context, arg StopJobMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopJobMetadata, arg.ID, arg.ExecutionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
