// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_requests.sql

package pggen

import (
	"context"
	"time"
)

const createScheduleRequest = `-- name: CreateScheduleRequest :one
INSERT INTO schedule_requests (broadcaster_id, requested_by, note)
VALUES ($1, $2, $3)
RETURNING id, broadcaster_id, requested_by, note, status, decided_by, decided_at, schedule_id, created_at
`

type CreateScheduleRequestParams struct {
	BroadcasterID string  `json:"broadcaster_id"`
	RequestedBy   string  `json:"requested_by"`
	Note          *string `json:"note"`
}

func (q *Queries) CreateScheduleRequest(ctx context.Context, arg CreateScheduleRequestParams) (ScheduleRequest, error) {
	row := q.db.QueryRow(ctx, createScheduleRequest, arg.BroadcasterID, arg.RequestedBy, arg.Note)
	var i ScheduleRequest
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Note,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ScheduleID,
		&i.CreatedAt,
	)
	return i, err
}

const decideScheduleRequest = `-- name: DecideScheduleRequest :execrows
UPDATE schedule_requests
SET status = $2, decided_by = $3, decided_at = NOW(), schedule_id = $4
WHERE id = $1 AND status = 'PENDING'
`

type DecideScheduleRequestParams struct {
	ID         int64   `json:"id"`
	Status     string  `json:"status"`
	DecidedBy  *string `json:"decided_by"`
	ScheduleID *int64  `json:"schedule_id"`
}

func (q *Queries) DecideScheduleRequest(ctx context.Context, arg DecideScheduleRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideScheduleRequest,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.ScheduleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleRequest = `-- name: DeleteScheduleRequest :execrows
DELETE FROM schedule_requests
WHERE id = $1 AND requested_by = $2 AND status = 'PENDING'
`

type DeleteScheduleRequestParams struct {
	ID          int64  `json:"id"`
	RequestedBy string `json:"requested_by"`
}

func (q *Queries) DeleteScheduleRequest(ctx context.Context, arg DeleteScheduleRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleRequest, arg.ID, arg.RequestedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduleRequest = `-- name: GetScheduleRequest :one
SELECT id, broadcaster_id, requested_by, note, status, decided_by, decided_at, schedule_id, created_at FROM schedule_requests WHERE id = $1
`

func (q *Queries) GetScheduleRequest(ctx context.Context, id int64) (ScheduleRequest, error) {
	row := q.db.QueryRow(ctx, getScheduleRequest, id)
	var i ScheduleRequest
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Note,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ScheduleID,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleRequests = `-- name: ListScheduleRequests :many
SELECT sr.id, sr.broadcaster_id, sr.requested_by, sr.note, sr.status, sr.decided_by, sr.decided_at, sr.schedule_id, sr.created_at, c.broadcaster_login, c.broadcaster_name, c.profile_image_url,
       u.login AS requested_by_login, u.display_name AS requested_by_name
FROM schedule_requests sr
INNER JOIN channels c ON c.broadcaster_id = sr.broadcaster_id
INNER JOIN users u ON u.id = sr.requested_by
WHERE (sr.created_at, sr.id) < ($1, CAST($2 AS BIGINT))
ORDER BY sr.created_at DESC, sr.id DESC
LIMIT $3
`

type ListScheduleRequestsParams struct {
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        int64     `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

type ListScheduleRequestsRow struct {
	ID               int64      `json:"id"`
	BroadcasterID    string     `json:"broadcaster_id"`
	RequestedBy      string     `json:"requested_by"`
	Note             *string    `json:"note"`
	Status           string     `json:"status"`
	DecidedBy        *string    `json:"decided_by"`
	DecidedAt        *time.Time `json:"decided_at"`
	ScheduleID       *int64     `json:"schedule_id"`
	CreatedAt        time.Time  `json:"created_at"`
	BroadcasterLogin string     `json:"broadcaster_login"`
	BroadcasterName  string     `json:"broadcaster_name"`
	ProfileImageUrl  *string    `json:"profile_image_url"`
	RequestedByLogin string     `json:"requested_by_login"`
	RequestedByName  string     `json:"requested_by_name"`
}

func (q *Queries) ListScheduleRequests(ctx context.Context, arg ListScheduleRequestsParams) ([]ListScheduleRequestsRow, error) {
	rows, err := q.db.Query(ctx, listScheduleRequests, arg.BeforeCreatedAt, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRequestsRow{}
	for rows.Next() {
		var i ListScheduleRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Note,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.ProfileImageUrl,
			&i.RequestedByLogin,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRequestsForUser = `-- name: ListScheduleRequestsForUser :many
SELECT sr.id, sr.broadcaster_id, sr.requested_by, sr.note, sr.status, sr.decided_by, sr.decided_at, sr.schedule_id, sr.created_at, c.broadcaster_login, c.broadcaster_name, c.profile_image_url,
       u.login AS requested_by_login, u.display_name AS requested_by_name
FROM schedule_requests sr
INNER JOIN channels c ON c.broadcaster_id = sr.broadcaster_id
INNER JOIN users u ON u.id = sr.requested_by
WHERE sr.requested_by = $1 AND (sr.created_at, sr.id) < ($2, CAST($3 AS BIGINT))
ORDER BY sr.created_at DESC, sr.id DESC
LIMIT $4
`

type ListScheduleRequestsForUserParams struct {
	RequestedBy     string    `json:"requested_by"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforeID        int64     `json:"before_id"`
	PageLimit       int32     `json:"page_limit"`
}

type ListScheduleRequestsForUserRow struct {
	ID               int64      `json:"id"`
	BroadcasterID    string     `json:"broadcaster_id"`
	RequestedBy      string     `json:"requested_by"`
	Note             *string    `json:"note"`
	Status           string     `json:"status"`
	DecidedBy        *string    `json:"decided_by"`
	DecidedAt        *time.Time `json:"decided_at"`
	ScheduleID       *int64     `json:"schedule_id"`
	CreatedAt        time.Time  `json:"created_at"`
	BroadcasterLogin string     `json:"broadcaster_login"`
	BroadcasterName  string     `json:"broadcaster_name"`
	ProfileImageUrl  *string    `json:"profile_image_url"`
	RequestedByLogin string     `json:"requested_by_login"`
	RequestedByName  string     `json:"requested_by_name"`
}

func (q *Queries) ListScheduleRequestsForUser(ctx context.Context, arg ListScheduleRequestsForUserParams) ([]ListScheduleRequestsForUserRow, error) {
	rows, err := q.db.Query(ctx, listScheduleRequestsForUser,
		arg.RequestedBy,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRequestsForUserRow{}
	for rows.Next() {
		var i ListScheduleRequestsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Note,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.BroadcasterLogin,
			&i.BroadcasterName,
			&i.ProfileImageUrl,
			&i.RequestedByLogin,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
