// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package pggen

import (
	"context"
)

const clearScheduleCategories = `-- name: ClearScheduleCategories :exec
DELETE FROM download_schedule_categories WHERE schedule_id = $1
`

func (q *Queries) ClearScheduleCategories(ctx context.Context, scheduleID int64) error {
	_, err := q.db.Exec(ctx, clearScheduleCategories, scheduleID)
	return err
}

const clearScheduleTags = `-- name: ClearScheduleTags :exec
DELETE FROM download_schedule_tags WHERE schedule_id = $1
`

func (q *Queries) ClearScheduleTags(ctx context.Context, scheduleID int64) error {
	_, err := q.db.Exec(ctx, clearScheduleTags, scheduleID)
	return err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO download_schedules (
    broadcaster_id, requested_by, quality,
    has_min_viewers, min_viewers,
    has_categories, has_tags,
    is_delete_rediff, time_before_delete,
    is_disabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

type CreateScheduleParams struct {
	BroadcasterID    string `json:"broadcaster_id"`
	RequestedBy      string `json:"requested_by"`
	Quality          string `json:"quality"`
	HasMinViewers    bool   `json:"has_min_viewers"`
	MinViewers       *int32 `json:"min_viewers"`
	HasCategories    bool   `json:"has_categories"`
	HasTags          bool   `json:"has_tags"`
	IsDeleteRediff   bool   `json:"is_delete_rediff"`
	TimeBeforeDelete *int32 `json:"time_before_delete"`
	IsDisabled       bool   `json:"is_disabled"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (DownloadSchedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.BroadcasterID,
		arg.RequestedBy,
		arg.Quality,
		arg.HasMinViewers,
		arg.MinViewers,
		arg.HasCategories,
		arg.HasTags,
		arg.IsDeleteRediff,
		arg.TimeBeforeDelete,
		arg.IsDisabled,
	)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM download_schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (DownloadSchedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleForUserChannel = `-- name: GetScheduleForUserChannel :one
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE broadcaster_id = $1 AND requested_by = $2
`

type GetScheduleForUserChannelParams struct {
	BroadcasterID string `json:"broadcaster_id"`
	RequestedBy   string `json:"requested_by"`
}

func (q *Queries) GetScheduleForUserChannel(ctx context.Context, arg GetScheduleForUserChannelParams) (DownloadSchedule, error) {
	row := q.db.QueryRow(ctx, getScheduleForUserChannel, arg.BroadcasterID, arg.RequestedBy)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkScheduleCategory = `-- name: LinkScheduleCategory :exec
INSERT INTO download_schedule_categories (schedule_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkScheduleCategoryParams struct {
	ScheduleID int64  `json:"schedule_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) LinkScheduleCategory(ctx context.Context, arg LinkScheduleCategoryParams) error {
	_, err := q.db.Exec(ctx, linkScheduleCategory, arg.ScheduleID, arg.CategoryID)
	return err
}

const linkScheduleTag = `-- name: LinkScheduleTag :exec
INSERT INTO download_schedule_tags (schedule_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkScheduleTagParams struct {
	ScheduleID int64 `json:"schedule_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) LinkScheduleTag(ctx context.Context, arg LinkScheduleTagParams) error {
	_, err := q.db.Exec(ctx, linkScheduleTag, arg.ScheduleID, arg.TagID)
	return err
}

const listActiveSchedulesForBroadcaster = `-- name: ListActiveSchedulesForBroadcaster :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE broadcaster_id = $1 AND is_disabled = FALSE
`

// Match path: called on every stream.online event. Partial index
// idx_schedules_active makes this O(log active_schedules).
func (q *Queries) ListActiveSchedulesForBroadcaster(ctx context.Context, broadcasterID string) ([]DownloadSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveSchedulesForBroadcaster, broadcasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleCategories = `-- name: ListScheduleCategories :many
SELECT c.id, c.name, c.box_art_url, c.igdb_id, c.created_at, c.updated_at FROM categories c
INNER JOIN download_schedule_categories dsc ON dsc.category_id = c.id
WHERE dsc.schedule_id = $1
ORDER BY c.name
`

func (q *Queries) ListScheduleCategories(ctx context.Context, scheduleID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listScheduleCategories, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BoxArtUrl,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTags = `-- name: ListScheduleTags :many
SELECT t.id, t.name, t.created_at FROM tags t
INNER JOIN download_schedule_tags dst ON dst.tag_id = t.id
WHERE dst.schedule_id = $1
ORDER BY t.name
`

func (q *Queries) ListScheduleTags(ctx context.Context, scheduleID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listScheduleTags, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]DownloadSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForUser = `-- name: ListSchedulesForUser :many
SELECT id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at FROM download_schedules
WHERE requested_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSchedulesForUserParams struct {
	RequestedBy string `json:"requested_by"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListSchedulesForUser(ctx context.Context, arg ListSchedulesForUserParams) ([]DownloadSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesForUser, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadSchedule{}
	for rows.Next() {
		var i DownloadSchedule
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.RequestedBy,
			&i.Quality,
			&i.HasMinViewers,
			&i.MinViewers,
			&i.HasCategories,
			&i.HasTags,
			&i.IsDeleteRediff,
			&i.TimeBeforeDelete,
			&i.IsDisabled,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleTrigger = `-- name: RecordScheduleTrigger :exec
UPDATE download_schedules SET
    last_triggered_at = NOW(),
    trigger_count = trigger_count + 1
WHERE id = $1
`

// Atomic increment + timestamp stamp. Called after a successful auto-download
// trigger so the dashboard can show "this schedule fired N times, last at T".
func (q *Queries) RecordScheduleTrigger(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordScheduleTrigger, id)
	return err
}

const toggleSchedule = `-- name: ToggleSchedule :one
UPDATE download_schedules SET is_disabled = NOT is_disabled, updated_at = NOW()
WHERE id = $1
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

func (q *Queries) ToggleSchedule(ctx context.Context, id int64) (DownloadSchedule, error) {
	row := q.db.QueryRow(ctx, toggleSchedule, id)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkScheduleCategory = `-- name: UnlinkScheduleCategory :exec
DELETE FROM download_schedule_categories
WHERE schedule_id = $1 AND category_id = $2
`

type UnlinkScheduleCategoryParams struct {
	ScheduleID int64  `json:"schedule_id"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) UnlinkScheduleCategory(ctx context.Context, arg UnlinkScheduleCategoryParams) error {
	_, err := q.db.Exec(ctx, unlinkScheduleCategory, arg.ScheduleID, arg.CategoryID)
	return err
}

const unlinkScheduleTag = `-- name: UnlinkScheduleTag :exec
DELETE FROM download_schedule_tags
WHERE schedule_id = $1 AND tag_id = $2
`

type UnlinkScheduleTagParams struct {
	ScheduleID int64 `json:"schedule_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) UnlinkScheduleTag(ctx context.Context, arg UnlinkScheduleTagParams) error {
	_, err := q.db.Exec(ctx, unlinkScheduleTag, arg.ScheduleID, arg.TagID)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE download_schedules SET
    quality             = $2,
    has_min_viewers     = $3,
    min_viewers         = $4,
    has_categories      = $5,
    has_tags            = $6,
    is_delete_rediff    = $7,
    time_before_delete  = $8,
    is_disabled         = $9,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, broadcaster_id, requested_by, quality, has_min_viewers, min_viewers, has_categories, has_tags, is_delete_rediff, time_before_delete, is_disabled, last_triggered_at, trigger_count, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID               int64  `json:"id"`
	Quality          string `json:"quality"`
	HasMinViewers    bool   `json:"has_min_viewers"`
	MinViewers       *int32 `json:"min_viewers"`
	HasCategories    bool   `json:"has_categories"`
	HasTags          bool   `json:"has_tags"`
	IsDeleteRediff   bool   `json:"is_delete_rediff"`
	TimeBeforeDelete *int32 `json:"time_before_delete"`
	IsDisabled       bool   `json:"is_disabled"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (DownloadSchedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Quality,
		arg.HasMinViewers,
		arg.MinViewers,
		arg.HasCategories,
		arg.HasTags,
		arg.IsDeleteRediff,
		arg.TimeBeforeDelete,
		arg.IsDisabled,
	)
	var i DownloadSchedule
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.RequestedBy,
		&i.Quality,
		&i.HasMinViewers,
		&i.MinViewers,
		&i.HasCategories,
		&i.HasTags,
		&i.IsDeleteRediff,
		&i.TimeBeforeDelete,
		&i.IsDisabled,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
