// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package pggen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT user_id, timezone, datetime_format, language, created_at, updated_at FROM settings WHERE user_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, userID string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings, userID)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.DatetimeFormat,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (user_id, timezone, datetime_format, language)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET timezone        = EXCLUDED.timezone,
    datetime_format = EXCLUDED.datetime_format,
    language        = EXCLUDED.language,
    updated_at      = NOW()
RETURNING user_id, timezone, datetime_format, language, created_at, updated_at
`

type UpsertSettingsParams struct {
	UserID         string `json:"user_id"`
	Timezone       string `json:"timezone"`
	DatetimeFormat string `json:"datetime_format"`
	Language       string `json:"language"`
}

// Called on first access and on every update. Defaults (UTC / ISO /
// en) come from the column defaults when the caller passes empty
// strings, but we expect callers to pass concrete values — validation
// lives at the tRPC boundary.
func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSettings,
		arg.UserID,
		arg.Timezone,
		arg.DatetimeFormat,
		arg.Language,
	)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.DatetimeFormat,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
