// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streams.sql

package pggen

import (
	"context"
	"time"
)

const endStream = `-- name: EndStream :exec
UPDATE streams SET ended_at = $2 WHERE id = $1 AND ended_at IS NULL
`

type EndStreamParams struct {
	ID      string     `json:"id"`
	EndedAt *time.Time `json:"ended_at"`
}

func (q *Queries) EndStream(ctx context.Context, arg EndStreamParams) error {
	_, err := q.db.Exec(ctx, endStream, arg.ID, arg.EndedAt)
	return err
}

const getLastLiveStream = `-- name: GetLastLiveStream :one
SELECT id, broadcaster_id, type, language, thumbnail_url, viewer_count, is_mature, started_at, ended_at, created_at FROM streams WHERE broadcaster_id = $1 ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLastLiveStream(ctx context.Context, broadcasterID string) (Stream, error) {
	row := q.db.QueryRow(ctx, getLastLiveStream, broadcasterID)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.Type,
		&i.Language,
		&i.ThumbnailUrl,
		&i.ViewerCount,
		&i.IsMature,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStream = `-- name: GetStream :one
SELECT id, broadcaster_id, type, language, thumbnail_url, viewer_count, is_mature, started_at, ended_at, created_at FROM streams WHERE id = $1
`

func (q *Queries) GetStream(ctx context.Context, id string) (Stream, error) {
	row := q.db.QueryRow(ctx, getStream, id)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.Type,
		&i.Language,
		&i.ThumbnailUrl,
		&i.ViewerCount,
		&i.IsMature,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStreams = `-- name: ListActiveStreams :many
SELECT id, broadcaster_id, type, language, thumbnail_url, viewer_count, is_mature, started_at, ended_at, created_at FROM streams WHERE ended_at IS NULL ORDER BY started_at DESC
`

func (q *Queries) ListActiveStreams(ctx context.Context) ([]Stream, error) {
	rows, err := q.db.Query(ctx, listActiveStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stream{}
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.Type,
			&i.Language,
			&i.ThumbnailUrl,
			&i.ViewerCount,
			&i.IsMature,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamsByBroadcaster = `-- name: ListStreamsByBroadcaster :many
SELECT id, broadcaster_id, type, language, thumbnail_url, viewer_count, is_mature, started_at, ended_at, created_at FROM streams WHERE broadcaster_id = $1 ORDER BY started_at DESC LIMIT $2 OFFSET $3
`

type ListStreamsByBroadcasterParams struct {
	BroadcasterID string `json:"broadcaster_id"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) ListStreamsByBroadcaster(ctx context.Context, arg ListStreamsByBroadcasterParams) ([]Stream, error) {
	rows, err := q.db.Query(ctx, listStreamsByBroadcaster, arg.BroadcasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stream{}
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.BroadcasterID,
			&i.Type,
			&i.Language,
			&i.ThumbnailUrl,
			&i.ViewerCount,
			&i.IsMature,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStreamViewers = `-- name: UpdateStreamViewers :exec
UPDATE streams SET viewer_count = $2 WHERE id = $1
`

type UpdateStreamViewersParams struct {
	ID          string `json:"id"`
	ViewerCount int32  `json:"viewer_count"`
}

func (q *Queries) UpdateStreamViewers(ctx context.Context, arg UpdateStreamViewersParams) error {
	_, err := q.db.Exec(ctx, updateStreamViewers, arg.ID, arg.ViewerCount)
	return err
}

const upsertStream = `-- name: UpsertStream :one
INSERT INTO streams (
    id, broadcaster_id, type, language, thumbnail_url,
    viewer_count, is_mature, started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    language = EXCLUDED.language,
    thumbnail_url = EXCLUDED.thumbnail_url,
    viewer_count = EXCLUDED.viewer_count,
    is_mature = EXCLUDED.is_mature
RETURNING id, broadcaster_id, type, language, thumbnail_url, viewer_count, is_mature, started_at, ended_at, created_at
`

type UpsertStreamParams struct {
	ID            string    `json:"id"`
	BroadcasterID string    `json:"broadcaster_id"`
	Type          string    `json:"type"`
	Language      string    `json:"language"`
	ThumbnailUrl  *string   `json:"thumbnail_url"`
	ViewerCount   int32     `json:"viewer_count"`
	IsMature      *bool     `json:"is_mature"`
	StartedAt     time.Time `json:"started_at"`
}

func (q *Queries) UpsertStream(ctx context.Context, arg UpsertStreamParams) (Stream, error) {
	row := q.db.QueryRow(ctx, upsertStream,
		arg.ID,
		arg.BroadcasterID,
		arg.Type,
		arg.Language,
		arg.ThumbnailUrl,
		arg.ViewerCount,
		arg.IsMature,
		arg.StartedAt,
	)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.BroadcasterID,
		&i.Type,
		&i.Language,
		&i.ThumbnailUrl,
		&i.ViewerCount,
		&i.IsMature,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}
