// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_execution.sql

package pggen

import (
	"context"
)

const claimTask = `-- name: ClaimTask :execrows
UPDATE tasks SET execution_id = $2, last_status = 'running', last_run_at = NOW(),
    next_run_at = NULL, last_error = NULL, updated_at = NOW()
WHERE name = $1 AND execution_id <> $2 AND is_available = TRUE AND is_enabled = TRUE AND (interval_seconds > 0 OR next_run_at IS NOT NULL)
  AND last_status <> 'running'
  AND (next_run_at IS NULL OR next_run_at <= NOW())
`

type ClaimTaskParams struct {
	Name        string `json:"name"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimTask, arg.Name, arg.ExecutionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverInterruptedTasks = `-- name: RecoverInterruptedTasks :exec
UPDATE tasks SET last_status = 'interrupted',
    next_run_at = COALESCE(next_run_at, NOW()), updated_at = NOW()
WHERE last_status = 'running'
`

// Startup owns abandoned executions, including paused or unavailable one-shots.
func (q *Queries) RecoverInterruptedTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverInterruptedTasks)
	return err
}

const resetTaskAvailability = `-- name: ResetTaskAvailability :exec
UPDATE tasks SET is_available = FALSE
`

func (q *Queries) ResetTaskAvailability(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTaskAvailability)
	return err
}

const settleTask = `-- name: SettleTask :execrows
UPDATE tasks SET last_status = $1, last_duration_ms = $2, last_error = NULLIF($3::text, ''),
    next_run_at = CASE
      WHEN $1 = 'interrupted' THEN COALESCE(next_run_at, NOW())
      WHEN interval_seconds > 0 THEN COALESCE(next_run_at, NOW() + (interval_seconds * INTERVAL '1 second'))
      ELSE next_run_at END,
    updated_at = NOW()
WHERE name = $4 AND execution_id = $5 AND last_status = 'running'
`

type SettleTaskParams struct {
	Status      string `json:"status"`
	DurationMs  int32  `json:"duration_ms"`
	Message     string `json:"message"`
	Name        string `json:"name"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) SettleTask(ctx context.Context, arg SettleTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleTask,
		arg.Status,
		arg.DurationMs,
		arg.Message,
		arg.Name,
		arg.ExecutionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
