// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: twitch_playback_sessions.sql

package pggen

import (
	"context"
)

const deleteTwitchPlaybackSession = `-- name: DeleteTwitchPlaybackSession :exec
DELETE FROM twitch_playback_sessions WHERE id = 1
`

func (q *Queries) DeleteTwitchPlaybackSession(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTwitchPlaybackSession)
	return err
}

const getTwitchPlaybackSession = `-- name: GetTwitchPlaybackSession :one
SELECT id, twitch_user_id, twitch_login, encrypted_token, expires_at, checked_at, needs_reconnect FROM twitch_playback_sessions WHERE id = 1
`

func (q *Queries) GetTwitchPlaybackSession(ctx context.Context) (TwitchPlaybackSession, error) {
	row := q.db.QueryRow(ctx, getTwitchPlaybackSession)
	var i TwitchPlaybackSession
	err := row.Scan(
		&i.ID,
		&i.TwitchUserID,
		&i.TwitchLogin,
		&i.EncryptedToken,
		&i.ExpiresAt,
		&i.CheckedAt,
		&i.NeedsReconnect,
	)
	return i, err
}

const saveTwitchPlaybackSession = `-- name: SaveTwitchPlaybackSession :exec
INSERT INTO twitch_playback_sessions (id, twitch_user_id, twitch_login, encrypted_token, expires_at, checked_at)
VALUES (1, $1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET twitch_user_id = EXCLUDED.twitch_user_id,
    twitch_login = EXCLUDED.twitch_login, encrypted_token = EXCLUDED.encrypted_token,
    expires_at = EXCLUDED.expires_at, checked_at = EXCLUDED.checked_at, needs_reconnect = FALSE
`

type SaveTwitchPlaybackSessionParams struct {
	TwitchUserID   string `json:"twitch_user_id"`
	TwitchLogin    string `json:"twitch_login"`
	EncryptedToken []byte `json:"encrypted_token"`
	ExpiresAt      int64  `json:"expires_at"`
	CheckedAt      int64  `json:"checked_at"`
}

func (q *Queries) SaveTwitchPlaybackSession(ctx context.Context, arg SaveTwitchPlaybackSessionParams) error {
	_, err := q.db.Exec(ctx, saveTwitchPlaybackSession,
		arg.TwitchUserID,
		arg.TwitchLogin,
		arg.EncryptedToken,
		arg.ExpiresAt,
		arg.CheckedAt,
	)
	return err
}

const updateTwitchPlaybackSessionValidation = `-- name: UpdateTwitchPlaybackSessionValidation :exec
UPDATE twitch_playback_sessions SET checked_at = $1, expires_at = $2, needs_reconnect = $3
WHERE id = 1 AND encrypted_token = $4 AND needs_reconnect = FALSE
`

type UpdateTwitchPlaybackSessionValidationParams struct {
	CheckedAt      int64  `json:"checked_at"`
	ExpiresAt      int64  `json:"expires_at"`
	NeedsReconnect bool   `json:"needs_reconnect"`
	EncryptedToken []byte `json:"encrypted_token"`
}

func (q *Queries) UpdateTwitchPlaybackSessionValidation(ctx context.Context, arg UpdateTwitchPlaybackSessionValidationParams) error {
	_, err := q.db.Exec(ctx, updateTwitchPlaybackSessionValidation,
		arg.CheckedAt,
		arg.ExpiresAt,
		arg.NeedsReconnect,
		arg.EncryptedToken,
	)
	return err
}
