// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_user_states.sql

package pggen

import (
	"context"
)

const getVideoUserState = `-- name: GetVideoUserState :one
SELECT user_id, video_id, watch_later, last_position_seconds, last_progress_at_ms, watched_at, completed_at, created_at, updated_at, progress_revision FROM video_user_states WHERE user_id = $1 AND video_id = $2
`

type GetVideoUserStateParams struct {
	UserID  string `json:"user_id"`
	VideoID int64  `json:"video_id"`
}

func (q *Queries) GetVideoUserState(ctx context.Context, arg GetVideoUserStateParams) (VideoUserState, error) {
	row := q.db.QueryRow(ctx, getVideoUserState, arg.UserID, arg.VideoID)
	var i VideoUserState
	err := row.Scan(
		&i.UserID,
		&i.VideoID,
		&i.WatchLater,
		&i.LastPositionSeconds,
		&i.LastProgressAtMs,
		&i.WatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProgressRevision,
	)
	return i, err
}

const listContinueWatchingVideos = `-- name: ListContinueWatchingVideos :many
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at, v.recording_type, v.force_h264, v.title, v.completion_kind, v.selected_quality, v.selected_fps, v.truncated, v.trigger_schedule_id, v.retention_source_schedule_id, v.retention_window_hours, v.deletion_kind, v.delete_requested_at, v.source, v.twitch_video_id, v.broadcast_at, v.next_retry_at FROM videos v
INNER JOIN video_user_states vus
    ON vus.video_id = v.id AND vus.user_id = $1::text
WHERE v.deleted_at IS NULL
  AND v.status = 'DONE'
  AND vus.watched_at IS NOT NULL
  AND vus.last_position_seconds > 0
  AND (v.duration_seconds IS NULL OR v.duration_seconds <= 0
       OR vus.last_position_seconds < v.duration_seconds - 1)
ORDER BY vus.last_progress_at_ms DESC NULLS LAST, v.id DESC
LIMIT $2::int
`

type ListContinueWatchingVideosParams struct {
	UserID   string `json:"user_id"`
	RowLimit int32  `json:"row_limit"`
}

// Recordings the user started and has not played to the end, most recently
// watched first. The dashboard applies its resume policy on top.
func (q *Queries) ListContinueWatchingVideos(ctx context.Context, arg ListContinueWatchingVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listContinueWatchingVideos, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
			&i.RecordingType,
			&i.ForceH264,
			&i.Title,
			&i.CompletionKind,
			&i.SelectedQuality,
			&i.SelectedFps,
			&i.Truncated,
			&i.TriggerScheduleID,
			&i.RetentionSourceScheduleID,
			&i.RetentionWindowHours,
			&i.DeletionKind,
			&i.DeleteRequestedAt,
			&i.Source,
			&i.TwitchVideoID,
			&i.BroadcastAt,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoUserStatesForVideos = `-- name: ListVideoUserStatesForVideos :many
SELECT user_id, video_id, watch_later, last_position_seconds, last_progress_at_ms, watched_at, completed_at, created_at, updated_at, progress_revision FROM video_user_states
WHERE user_id = $1 AND video_id = ANY($2::bigint[])
`

type ListVideoUserStatesForVideosParams struct {
	UserID   string  `json:"user_id"`
	VideoIds []int64 `json:"video_ids"`
}

func (q *Queries) ListVideoUserStatesForVideos(ctx context.Context, arg ListVideoUserStatesForVideosParams) ([]VideoUserState, error) {
	rows, err := q.db.Query(ctx, listVideoUserStatesForVideos, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoUserState{}
	for rows.Next() {
		var i VideoUserState
		if err := rows.Scan(
			&i.UserID,
			&i.VideoID,
			&i.WatchLater,
			&i.LastPositionSeconds,
			&i.LastProgressAtMs,
			&i.WatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProgressRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoWatchLater = `-- name: SetVideoWatchLater :one
INSERT INTO video_user_states (user_id, video_id, watch_later, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT(user_id, video_id) DO UPDATE SET
    watch_later = EXCLUDED.watch_later,
    updated_at = NOW()
RETURNING user_id, video_id, watch_later, last_position_seconds, last_progress_at_ms, watched_at, completed_at, created_at, updated_at, progress_revision
`

type SetVideoWatchLaterParams struct {
	UserID     string `json:"user_id"`
	VideoID    int64  `json:"video_id"`
	WatchLater bool   `json:"watch_later"`
}

func (q *Queries) SetVideoWatchLater(ctx context.Context, arg SetVideoWatchLaterParams) (VideoUserState, error) {
	row := q.db.QueryRow(ctx, setVideoWatchLater, arg.UserID, arg.VideoID, arg.WatchLater)
	var i VideoUserState
	err := row.Scan(
		&i.UserID,
		&i.VideoID,
		&i.WatchLater,
		&i.LastPositionSeconds,
		&i.LastProgressAtMs,
		&i.WatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProgressRevision,
	)
	return i, err
}

const updateVideoWatchProgress = `-- name: UpdateVideoWatchProgress :one
INSERT INTO video_user_states (
    user_id, video_id, last_position_seconds, last_progress_at_ms, progress_revision, watched_at, completed_at, updated_at
)
SELECT
    $1, v.id, GREATEST(0::DOUBLE PRECISION, $3::DOUBLE PRECISION),
    $4::BIGINT, 1,
    CASE
        WHEN $5::BOOLEAN
          OR $3::DOUBLE PRECISION >= CASE
              WHEN v.duration_seconds > 0
              THEN LEAST($6::DOUBLE PRECISION, v.duration_seconds * $7::DOUBLE PRECISION)
              ELSE $6::DOUBLE PRECISION
          END
        THEN NOW() ELSE NULL
    END,
    CASE WHEN $5::BOOLEAN THEN NOW() ELSE NULL END,
    NOW()
FROM videos v
WHERE v.id = $2
  AND v.deleted_at IS NULL
  AND v.status = 'DONE'
ON CONFLICT(user_id, video_id) DO UPDATE SET
    progress_revision = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN video_user_states.progress_revision + 1 ELSE video_user_states.progress_revision END,
    last_position_seconds = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN EXCLUDED.last_position_seconds ELSE video_user_states.last_position_seconds END,
    last_progress_at_ms = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN EXCLUDED.last_progress_at_ms ELSE video_user_states.last_progress_at_ms END,
    watched_at = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN COALESCE(video_user_states.watched_at, EXCLUDED.watched_at) ELSE video_user_states.watched_at END,
    completed_at = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN COALESCE(EXCLUDED.completed_at, video_user_states.completed_at) ELSE video_user_states.completed_at END,
    updated_at = CASE WHEN excluded.last_progress_at_ms >= COALESCE(video_user_states.last_progress_at_ms, 0) THEN NOW() ELSE video_user_states.updated_at END
RETURNING user_id, video_id, watch_later, last_position_seconds, last_progress_at_ms, watched_at, completed_at, created_at, updated_at, progress_revision
`

type UpdateVideoWatchProgressParams struct {
	UserID          string  `json:"user_id"`
	ID              int64   `json:"id"`
	PositionSeconds float64 `json:"position_seconds"`
	ProgressAtMs    int64   `json:"progress_at_ms"`
	Completed       bool    `json:"completed"`
	StartedSeconds  float64 `json:"started_seconds"`
	StartedFraction float64 `json:"started_fraction"`
}

// Progress writes are ordered by the server clock (@progress_at_ms), so
// devices with skewed clocks cannot shadow each other. watched_at marks the
// recording as started once the position reaches the smaller of
// @started_seconds and @started_fraction of the duration, or on completion;
// both stamps are kept once set.
func (q *Queries) UpdateVideoWatchProgress(ctx context.Context, arg UpdateVideoWatchProgressParams) (VideoUserState, error) {
	row := q.db.QueryRow(ctx, updateVideoWatchProgress,
		arg.UserID,
		arg.ID,
		arg.PositionSeconds,
		arg.ProgressAtMs,
		arg.Completed,
		arg.StartedSeconds,
		arg.StartedFraction,
	)
	var i VideoUserState
	err := row.Scan(
		&i.UserID,
		&i.VideoID,
		&i.WatchLater,
		&i.LastPositionSeconds,
		&i.LastProgressAtMs,
		&i.WatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProgressRevision,
	)
	return i, err
}
