// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package pggen

import (
	"context"
)

const countVideosByStatus = `-- name: CountVideosByStatus :one
SELECT COUNT(*) FROM videos WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountVideosByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    job_id, filename, display_name, status, quality,
    broadcaster_id, stream_id, viewer_count, language
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at
`

type CreateVideoParams struct {
	JobID         string  `json:"job_id"`
	Filename      string  `json:"filename"`
	DisplayName   string  `json:"display_name"`
	Status        string  `json:"status"`
	Quality       string  `json:"quality"`
	BroadcasterID string  `json:"broadcaster_id"`
	StreamID      *string `json:"stream_id"`
	ViewerCount   int32   `json:"viewer_count"`
	Language      string  `json:"language"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.JobID,
		arg.Filename,
		arg.DisplayName,
		arg.Status,
		arg.Quality,
		arg.BroadcasterID,
		arg.StreamID,
		arg.ViewerCount,
		arg.Language,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByJobID = `-- name: GetVideoByJobID :one
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos WHERE job_id = $1
`

func (q *Queries) GetVideoByJobID(ctx context.Context, jobID string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByJobID, jobID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Filename,
		&i.DisplayName,
		&i.Status,
		&i.Quality,
		&i.BroadcasterID,
		&i.StreamID,
		&i.ViewerCount,
		&i.Language,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.Error,
		&i.StartDownloadAt,
		&i.DownloadedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos WHERE deleted_at IS NULL ORDER BY start_download_at DESC LIMIT $1 OFFSET $2
`

type ListVideosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByBroadcaster = `-- name: ListVideosByBroadcaster :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos
WHERE broadcaster_id = $1 AND deleted_at IS NULL
ORDER BY start_download_at DESC
LIMIT $2 OFFSET $3
`

type ListVideosByBroadcasterParams struct {
	BroadcasterID string `json:"broadcaster_id"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) ListVideosByBroadcaster(ctx context.Context, arg ListVideosByBroadcasterParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByBroadcaster, arg.BroadcasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByCategory = `-- name: ListVideosByCategory :many
SELECT v.id, v.job_id, v.filename, v.display_name, v.status, v.quality, v.broadcaster_id, v.stream_id, v.viewer_count, v.language, v.duration_seconds, v.size_bytes, v.thumbnail, v.error, v.start_download_at, v.downloaded_at, v.deleted_at FROM videos v
INNER JOIN video_categories vc ON vc.video_id = v.id
WHERE vc.category_id = $1 AND v.deleted_at IS NULL
ORDER BY v.start_download_at DESC
LIMIT $2 OFFSET $3
`

type ListVideosByCategoryParams struct {
	CategoryID string `json:"category_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListVideosByCategory(ctx context.Context, arg ListVideosByCategoryParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByStatus = `-- name: ListVideosByStatus :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos WHERE status = $1 AND deleted_at IS NULL ORDER BY start_download_at DESC LIMIT $2 OFFSET $3
`

type ListVideosByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListVideosByStatus(ctx context.Context, arg ListVideosByStatusParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosMissingThumbnail = `-- name: ListVideosMissingThumbnail :many
SELECT id, job_id, filename, display_name, status, quality, broadcaster_id, stream_id, viewer_count, language, duration_seconds, size_bytes, thumbnail, error, start_download_at, downloaded_at, deleted_at FROM videos WHERE status = 'DONE' AND thumbnail IS NULL AND deleted_at IS NULL
`

func (q *Queries) ListVideosMissingThumbnail(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosMissingThumbnail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Filename,
			&i.DisplayName,
			&i.Status,
			&i.Quality,
			&i.BroadcasterID,
			&i.StreamID,
			&i.ViewerCount,
			&i.Language,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.Error,
			&i.StartDownloadAt,
			&i.DownloadedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoDone = `-- name: MarkVideoDone :exec
UPDATE videos SET
    status = 'DONE',
    downloaded_at = NOW(),
    duration_seconds = $2,
    size_bytes = $3,
    thumbnail = $4
WHERE id = $1
`

type MarkVideoDoneParams struct {
	ID              int64    `json:"id"`
	DurationSeconds *float64 `json:"duration_seconds"`
	SizeBytes       *int64   `json:"size_bytes"`
	Thumbnail       *string  `json:"thumbnail"`
}

func (q *Queries) MarkVideoDone(ctx context.Context, arg MarkVideoDoneParams) error {
	_, err := q.db.Exec(ctx, markVideoDone,
		arg.ID,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Thumbnail,
	)
	return err
}

const markVideoFailed = `-- name: MarkVideoFailed :exec
UPDATE videos SET
    status = 'FAILED',
    downloaded_at = NOW(),
    error = $2
WHERE id = $1
`

type MarkVideoFailedParams struct {
	ID    int64   `json:"id"`
	Error *string `json:"error"`
}

func (q *Queries) MarkVideoFailed(ctx context.Context, arg MarkVideoFailedParams) error {
	_, err := q.db.Exec(ctx, markVideoFailed, arg.ID, arg.Error)
	return err
}

const setVideoThumbnail = `-- name: SetVideoThumbnail :exec
UPDATE videos SET thumbnail = $2 WHERE id = $1
`

type SetVideoThumbnailParams struct {
	ID        int64   `json:"id"`
	Thumbnail *string `json:"thumbnail"`
}

func (q *Queries) SetVideoThumbnail(ctx context.Context, arg SetVideoThumbnailParams) error {
	_, err := q.db.Exec(ctx, setVideoThumbnail, arg.ID, arg.Thumbnail)
	return err
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteVideo, id)
	return err
}

const statisticsByStatus = `-- name: StatisticsByStatus :many
SELECT status, COUNT(*) AS count FROM videos WHERE deleted_at IS NULL GROUP BY status
`

type StatisticsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) StatisticsByStatus(ctx context.Context) ([]StatisticsByStatusRow, error) {
	rows, err := q.db.Query(ctx, statisticsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatisticsByStatusRow{}
	for rows.Next() {
		var i StatisticsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statisticsTotals = `-- name: StatisticsTotals :one
SELECT
    COUNT(*)::BIGINT AS total,
    COALESCE(SUM(size_bytes), 0)::BIGINT AS total_size,
    COALESCE(SUM(duration_seconds), 0)::DOUBLE PRECISION AS total_duration
FROM videos WHERE status = 'DONE' AND deleted_at IS NULL
`

type StatisticsTotalsRow struct {
	Total         int64   `json:"total"`
	TotalSize     int64   `json:"total_size"`
	TotalDuration float64 `json:"total_duration"`
}

func (q *Queries) StatisticsTotals(ctx context.Context) (StatisticsTotalsRow, error) {
	row := q.db.QueryRow(ctx, statisticsTotals)
	var i StatisticsTotalsRow
	err := row.Scan(&i.Total, &i.TotalSize, &i.TotalDuration)
	return i, err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET status = $2 WHERE id = $1
`

type UpdateVideoStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus, arg.ID, arg.Status)
	return err
}
