// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_parts.sql

package pggen

import (
	"context"
)

const countVideoParts = `-- name: CountVideoParts :one
SELECT COUNT(*) FROM video_parts WHERE video_id = $1
`

func (q *Queries) CountVideoParts(ctx context.Context, videoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVideoParts, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideoPart = `-- name: CreateVideoPart :one
INSERT INTO video_parts (
    video_id, part_index, filename, quality, fps, codec,
    segment_format, start_media_seq
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at, updated_at, fps
`

type CreateVideoPartParams struct {
	VideoID       int64    `json:"video_id"`
	PartIndex     int32    `json:"part_index"`
	Filename      string   `json:"filename"`
	Quality       string   `json:"quality"`
	Fps           *float64 `json:"fps"`
	Codec         string   `json:"codec"`
	SegmentFormat string   `json:"segment_format"`
	StartMediaSeq int64    `json:"start_media_seq"`
}

// end_media_seq is deliberately omitted: its real value is only known
// at FinalizeVideoPart time. Creating a part with a placeholder
// produced rows indistinguishable from zero-length recordings when a
// job failed before finalize.
func (q *Queries) CreateVideoPart(ctx context.Context, arg CreateVideoPartParams) (VideoPart, error) {
	row := q.db.QueryRow(ctx, createVideoPart,
		arg.VideoID,
		arg.PartIndex,
		arg.Filename,
		arg.Quality,
		arg.Fps,
		arg.Codec,
		arg.SegmentFormat,
		arg.StartMediaSeq,
	)
	var i VideoPart
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PartIndex,
		&i.Filename,
		&i.Quality,
		&i.Codec,
		&i.SegmentFormat,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.StartMediaSeq,
		&i.EndMediaSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fps,
	)
	return i, err
}

const deleteVideoParts = `-- name: DeleteVideoParts :exec
DELETE FROM video_parts WHERE video_id = $1
`

func (q *Queries) DeleteVideoParts(ctx context.Context, videoID int64) error {
	_, err := q.db.Exec(ctx, deleteVideoParts, videoID)
	return err
}

const finalizeVideoPart = `-- name: FinalizeVideoPart :exec
UPDATE video_parts SET
    duration_seconds = $2,
    size_bytes = $3,
    thumbnail = $4,
    end_media_seq = $5,
    updated_at = NOW()
WHERE id = $1
`

type FinalizeVideoPartParams struct {
	ID              int64   `json:"id"`
	DurationSeconds float64 `json:"duration_seconds"`
	SizeBytes       int64   `json:"size_bytes"`
	Thumbnail       *string `json:"thumbnail"`
	EndMediaSeq     *int64  `json:"end_media_seq"`
}

func (q *Queries) FinalizeVideoPart(ctx context.Context, arg FinalizeVideoPartParams) error {
	_, err := q.db.Exec(ctx, finalizeVideoPart,
		arg.ID,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Thumbnail,
		arg.EndMediaSeq,
	)
	return err
}

const getVideoPart = `-- name: GetVideoPart :one
SELECT id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at, updated_at, fps FROM video_parts WHERE id = $1
`

func (q *Queries) GetVideoPart(ctx context.Context, id int64) (VideoPart, error) {
	row := q.db.QueryRow(ctx, getVideoPart, id)
	var i VideoPart
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PartIndex,
		&i.Filename,
		&i.Quality,
		&i.Codec,
		&i.SegmentFormat,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.StartMediaSeq,
		&i.EndMediaSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fps,
	)
	return i, err
}

const getVideoPartByIndex = `-- name: GetVideoPartByIndex :one
SELECT id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at, updated_at, fps FROM video_parts WHERE video_id = $1 AND part_index = $2
`

type GetVideoPartByIndexParams struct {
	VideoID   int64 `json:"video_id"`
	PartIndex int32 `json:"part_index"`
}

// The "current part" lookup used by resume logic — given a video and
// a part_index, return the row without pulling the whole list.
func (q *Queries) GetVideoPartByIndex(ctx context.Context, arg GetVideoPartByIndexParams) (VideoPart, error) {
	row := q.db.QueryRow(ctx, getVideoPartByIndex, arg.VideoID, arg.PartIndex)
	var i VideoPart
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.PartIndex,
		&i.Filename,
		&i.Quality,
		&i.Codec,
		&i.SegmentFormat,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Thumbnail,
		&i.StartMediaSeq,
		&i.EndMediaSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fps,
	)
	return i, err
}

const hasFinalizedVideoParts = `-- name: HasFinalizedVideoParts :one
SELECT EXISTS (
    SELECT 1 FROM video_parts
    WHERE video_id = $1 AND size_bytes > 0
) AS has_finalized
`

// True when at least one part for this video has been remuxed and
// persisted (size_bytes > 0). Stub rows created at PrepareInput but
// not yet finalized at Store don't count — their files don't exist on
// storage. Used by the failure path to distinguish "recording lost
// before any watchable output" from "some parts saved before the run
// failed", which becomes the partial completion_kind on the row.
func (q *Queries) HasFinalizedVideoParts(ctx context.Context, videoID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasFinalizedVideoParts, videoID)
	var has_finalized bool
	err := row.Scan(&has_finalized)
	return has_finalized, err
}

const listVideoParts = `-- name: ListVideoParts :many
SELECT id, video_id, part_index, filename, quality, codec, segment_format, duration_seconds, size_bytes, thumbnail, start_media_seq, end_media_seq, created_at, updated_at, fps FROM video_parts WHERE video_id = $1 ORDER BY part_index ASC
`

func (q *Queries) ListVideoParts(ctx context.Context, videoID int64) ([]VideoPart, error) {
	rows, err := q.db.Query(ctx, listVideoParts, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoPart{}
	for rows.Next() {
		var i VideoPart
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.PartIndex,
			&i.Filename,
			&i.Quality,
			&i.Codec,
			&i.SegmentFormat,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Thumbnail,
			&i.StartMediaSeq,
			&i.EndMediaSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Fps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
