// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_playback_assets.sql

package pggen

import (
	"context"
	"time"
)

const deleteVideoPlaybackAsset = `-- name: DeleteVideoPlaybackAsset :exec
DELETE FROM video_playback_assets WHERE video_id = $1
`

func (q *Queries) DeleteVideoPlaybackAsset(ctx context.Context, videoID int64) error {
	_, err := q.db.Exec(ctx, deleteVideoPlaybackAsset, videoID)
	return err
}

const getVideoPlaybackAsset = `-- name: GetVideoPlaybackAsset :one
SELECT video_id, status, filename, mime_type, duration_seconds, size_bytes, error, generated_at, last_accessed_at, created_at, updated_at FROM video_playback_assets WHERE video_id = $1
`

func (q *Queries) GetVideoPlaybackAsset(ctx context.Context, videoID int64) (VideoPlaybackAsset, error) {
	row := q.db.QueryRow(ctx, getVideoPlaybackAsset, videoID)
	var i VideoPlaybackAsset
	err := row.Scan(
		&i.VideoID,
		&i.Status,
		&i.Filename,
		&i.MimeType,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Error,
		&i.GeneratedAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReadyVideoPlaybackAssets = `-- name: ListReadyVideoPlaybackAssets :many
SELECT video_id, status, filename, mime_type, duration_seconds, size_bytes, error, generated_at, last_accessed_at, created_at, updated_at
FROM video_playback_assets
WHERE status = 'ready'
ORDER BY last_accessed_at ASC, generated_at ASC, video_id ASC
`

func (q *Queries) ListReadyVideoPlaybackAssets(ctx context.Context) ([]VideoPlaybackAsset, error) {
	rows, err := q.db.Query(ctx, listReadyVideoPlaybackAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoPlaybackAsset{}
	for rows.Next() {
		var i VideoPlaybackAsset
		if err := rows.Scan(
			&i.VideoID,
			&i.Status,
			&i.Filename,
			&i.MimeType,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.Error,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchVideoPlaybackAsset = `-- name: TouchVideoPlaybackAsset :exec
UPDATE video_playback_assets
SET last_accessed_at = NOW(),
    updated_at = NOW()
WHERE video_id = $1
  AND status = 'ready'
`

func (q *Queries) TouchVideoPlaybackAsset(ctx context.Context, videoID int64) error {
	_, err := q.db.Exec(ctx, touchVideoPlaybackAsset, videoID)
	return err
}

const upsertVideoPlaybackAsset = `-- name: UpsertVideoPlaybackAsset :one
INSERT INTO video_playback_assets (
    video_id, status, filename, mime_type,
    duration_seconds, size_bytes, error, generated_at, last_accessed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT(video_id) DO UPDATE SET
    status = excluded.status,
    filename = excluded.filename,
    mime_type = excluded.mime_type,
    duration_seconds = excluded.duration_seconds,
    size_bytes = excluded.size_bytes,
    error = excluded.error,
    generated_at = excluded.generated_at,
    last_accessed_at = excluded.last_accessed_at,
    updated_at = NOW()
RETURNING video_id, status, filename, mime_type, duration_seconds, size_bytes, error, generated_at, last_accessed_at, created_at, updated_at
`

type UpsertVideoPlaybackAssetParams struct {
	VideoID         int64      `json:"video_id"`
	Status          string     `json:"status"`
	Filename        *string    `json:"filename"`
	MimeType        *string    `json:"mime_type"`
	DurationSeconds *float64   `json:"duration_seconds"`
	SizeBytes       *int64     `json:"size_bytes"`
	Error           *string    `json:"error"`
	GeneratedAt     *time.Time `json:"generated_at"`
	LastAccessedAt  *time.Time `json:"last_accessed_at"`
}

func (q *Queries) UpsertVideoPlaybackAsset(ctx context.Context, arg UpsertVideoPlaybackAssetParams) (VideoPlaybackAsset, error) {
	row := q.db.QueryRow(ctx, upsertVideoPlaybackAsset,
		arg.VideoID,
		arg.Status,
		arg.Filename,
		arg.MimeType,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.Error,
		arg.GeneratedAt,
		arg.LastAccessedAt,
	)
	var i VideoPlaybackAsset
	err := row.Scan(
		&i.VideoID,
		&i.Status,
		&i.Filename,
		&i.MimeType,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.Error,
		&i.GeneratedAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
