// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_events.sql

package pggen

import (
	"context"
	"encoding/json"
	"time"
)

const clearWebhookEventPayload = `-- name: ClearWebhookEventPayload :exec
UPDATE webhook_events
SET payload = NULL
WHERE received_at < $1 AND payload IS NOT NULL
`

// Retention trim: scheduler task nulls the payload on rows older than
// webhook_event_payload_retention_days. The row (with audit metadata)
// stays; just the fat JSON column goes.
func (q *Queries) ClearWebhookEventPayload(ctx context.Context, receivedAt time.Time) error {
	_, err := q.db.Exec(ctx, clearWebhookEventPayload, receivedAt)
	return err
}

const countWebhookEvents = `-- name: CountWebhookEvents :one
SELECT COUNT(*) FROM webhook_events
`

func (q *Queries) CountWebhookEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookEventsByType = `-- name: CountWebhookEventsByType :one
SELECT COUNT(*) FROM webhook_events WHERE event_type = $1
`

func (q *Queries) CountWebhookEventsByType(ctx context.Context, eventType *string) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEventsByType, eventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (
    event_id, message_type, event_type,
    subscription_id, broadcaster_id,
    message_timestamp, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at
`

type CreateWebhookEventParams struct {
	EventID          string          `json:"event_id"`
	MessageType      string          `json:"message_type"`
	EventType        *string         `json:"event_type"`
	SubscriptionID   *string         `json:"subscription_id"`
	BroadcasterID    *string         `json:"broadcaster_id"`
	MessageTimestamp time.Time       `json:"message_timestamp"`
	Payload          json.RawMessage `json:"payload"`
}

// Idempotent: Twitch retries with the same Message-Id on delivery failure.
// ON CONFLICT DO NOTHING avoids double-processing; the RETURNING is NULL
// on conflict so the handler knows the event was already recorded.
func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.EventID,
		arg.MessageType,
		arg.EventType,
		arg.SubscriptionID,
		arg.BroadcasterID,
		arg.MessageTimestamp,
		arg.Payload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MessageType,
		&i.EventType,
		&i.SubscriptionID,
		&i.BroadcasterID,
		&i.MessageTimestamp,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEvent(ctx context.Context, id int64) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEvent, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MessageType,
		&i.EventType,
		&i.SubscriptionID,
		&i.BroadcasterID,
		&i.MessageTimestamp,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getWebhookEventByEventID = `-- name: GetWebhookEventByEventID :one
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events WHERE event_id = $1
`

func (q *Queries) GetWebhookEventByEventID(ctx context.Context, eventID string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByEventID, eventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MessageType,
		&i.EventType,
		&i.SubscriptionID,
		&i.BroadcasterID,
		&i.MessageTimestamp,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listStuckWebhookEvents = `-- name: ListStuckWebhookEvents :many
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events
WHERE status = 'received' AND received_at < $1
ORDER BY received_at DESC
LIMIT $2
`

type ListStuckWebhookEventsParams struct {
	ReceivedAt time.Time `json:"received_at"`
	Limit      int32     `json:"limit"`
}

// Dashboard "stuck" query: status='received' rows older than a threshold
// indicate the handler crashed mid-processing. Partial index
// idx_webhook_events_received_status keeps this fast.
func (q *Queries) ListStuckWebhookEvents(ctx context.Context, arg ListStuckWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listStuckWebhookEvents, arg.ReceivedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MessageType,
			&i.EventType,
			&i.SubscriptionID,
			&i.BroadcasterID,
			&i.MessageTimestamp,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events
ORDER BY received_at DESC
LIMIT $1 OFFSET $2
`

type ListWebhookEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MessageType,
			&i.EventType,
			&i.SubscriptionID,
			&i.BroadcasterID,
			&i.MessageTimestamp,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsByBroadcaster = `-- name: ListWebhookEventsByBroadcaster :many
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events
WHERE broadcaster_id = $1
ORDER BY received_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsByBroadcasterParams struct {
	BroadcasterID *string `json:"broadcaster_id"`
	Limit         int32   `json:"limit"`
	Offset        int32   `json:"offset"`
}

func (q *Queries) ListWebhookEventsByBroadcaster(ctx context.Context, arg ListWebhookEventsByBroadcasterParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsByBroadcaster, arg.BroadcasterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MessageType,
			&i.EventType,
			&i.SubscriptionID,
			&i.BroadcasterID,
			&i.MessageTimestamp,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsByType = `-- name: ListWebhookEventsByType :many
SELECT id, event_id, message_type, event_type, subscription_id, broadcaster_id, message_timestamp, payload, status, error, received_at, processed_at FROM webhook_events
WHERE event_type = $1
ORDER BY received_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsByTypeParams struct {
	EventType *string `json:"event_type"`
	Limit     int32   `json:"limit"`
	Offset    int32   `json:"offset"`
}

func (q *Queries) ListWebhookEventsByType(ctx context.Context, arg ListWebhookEventsByTypeParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsByType, arg.EventType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MessageType,
			&i.EventType,
			&i.SubscriptionID,
			&i.BroadcasterID,
			&i.MessageTimestamp,
			&i.Payload,
			&i.Status,
			&i.Error,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventFailed = `-- name: MarkWebhookEventFailed :exec
UPDATE webhook_events
SET status = 'failed', processed_at = NOW(), error = $2
WHERE id = $1
`

type MarkWebhookEventFailedParams struct {
	ID    int64   `json:"id"`
	Error *string `json:"error"`
}

func (q *Queries) MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookEventFailed, arg.ID, arg.Error)
	return err
}

const markWebhookEventProcessed = `-- name: MarkWebhookEventProcessed :exec
UPDATE webhook_events
SET status = 'processed', processed_at = NOW(), error = NULL
WHERE id = $1
`

func (q *Queries) MarkWebhookEventProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWebhookEventProcessed, id)
	return err
}
