// Code generated by repo-adapter-gen. DO NOT EDIT.

package pgadapter

import (
	"github.com/befabri/replayvod/server/internal/repository"
	"github.com/befabri/replayvod/server/internal/repository/pgadapter/pggen"
)

func pgArchiveQueueCandidateToDomain(src pggen.ListQueuedArchiveJobsRow) *repository.ArchiveQueueCandidate {
	return &repository.ArchiveQueueCandidate{
		JobID:    src.JobID,
		QueuedAt: src.QueuedAt,
		VideoID:  src.VideoID,
	}
}

func pgArchiveQueueCandidatesToDomain(rows []pggen.ListQueuedArchiveJobsRow) []repository.ArchiveQueueCandidate {
	out := make([]repository.ArchiveQueueCandidate, len(rows))
	for i, r := range rows {
		out[i] = *pgArchiveQueueCandidateToDomain(r)
	}
	return out
}

func pgRetentionVideoToDomain(src pggen.ListRetentionCandidatesRow) *repository.RetentionVideo {
	return &repository.RetentionVideo{
		BroadcasterID:        src.BroadcasterID,
		DownloadedAt:         src.DownloadedAt,
		RetentionWindowHours: int32PtrToInt64Ptr(src.RetentionWindowHours),
		VideoID:              src.VideoID,
	}
}

func pgRetentionVideosToDomain(rows []pggen.ListRetentionCandidatesRow) []repository.RetentionVideo {
	out := make([]repository.RetentionVideo, len(rows))
	for i, r := range rows {
		out[i] = *pgRetentionVideoToDomain(r)
	}
	return out
}

func pgStorageScanVideoToDomain(src pggen.ListVideosForStorageScanRow) *repository.StorageScanVideo {
	return &repository.StorageScanVideo{
		Filename: src.Filename,
		Status:   src.Status,
		VideoID:  src.VideoID,
	}
}

func pgStorageScanVideosToDomain(rows []pggen.ListVideosForStorageScanRow) []repository.StorageScanVideo {
	out := make([]repository.StorageScanVideo, len(rows))
	for i, r := range rows {
		out[i] = *pgStorageScanVideoToDomain(r)
	}
	return out
}

func pgMissingTombstoneToDomain(src pggen.ListMissingTombstonesRow) *repository.StorageScanVideo {
	return &repository.StorageScanVideo{
		Filename: src.Filename,
		Status:   src.Status,
		VideoID:  src.VideoID,
	}
}

func pgMissingTombstonesToDomain(rows []pggen.ListMissingTombstonesRow) []repository.StorageScanVideo {
	out := make([]repository.StorageScanVideo, len(rows))
	for i, r := range rows {
		out[i] = *pgMissingTombstoneToDomain(r)
	}
	return out
}

func pgStorageWitnessToDomain(src pggen.ListVideosForStorageWitnessRow) *repository.StorageScanVideo {
	return &repository.StorageScanVideo{
		Filename: src.Filename,
		Status:   src.Status,
		VideoID:  src.VideoID,
	}
}

func pgStorageWitnessesToDomain(rows []pggen.ListVideosForStorageWitnessRow) []repository.StorageScanVideo {
	out := make([]repository.StorageScanVideo, len(rows))
	for i, r := range rows {
		out[i] = *pgStorageWitnessToDomain(r)
	}
	return out
}

func pgSessionToDomain(src pggen.Session) *repository.Session {
	return &repository.Session{
		CreatedAt:       src.CreatedAt,
		EncryptedTokens: src.EncryptedTokens,
		ExpiresAt:       src.ExpiresAt,
		HashedID:        src.HashedID,
		IPAddress:       src.IpAddress,
		LastActiveAt:    src.LastActiveAt,
		UserAgent:       src.UserAgent,
		UserID:          src.UserID,
	}
}

func pgSessionInfoToDomain(src pggen.ListUserSessionsRow) *repository.SessionInfo {
	return &repository.SessionInfo{
		CreatedAt:    src.CreatedAt,
		ExpiresAt:    src.ExpiresAt,
		HashedID:     src.HashedID,
		IPAddress:    src.IpAddress,
		LastActiveAt: src.LastActiveAt,
		UserAgent:    src.UserAgent,
		UserID:       src.UserID,
	}
}

func pgSessionInfosToDomain(rows []pggen.ListUserSessionsRow) []repository.SessionInfo {
	out := make([]repository.SessionInfo, len(rows))
	for i, r := range rows {
		out[i] = *pgSessionInfoToDomain(r)
	}
	return out
}

func pgAppAccessTokenToDomain(src pggen.AppAccessToken) *repository.AppAccessToken {
	return &repository.AppAccessToken{
		CreatedAt: src.CreatedAt,
		ExpiresAt: src.ExpiresAt,
		ID:        src.ID,
		Token:     src.Token,
	}
}

func pgTwitchPlaybackSessionToDomain(src pggen.TwitchPlaybackSession) *repository.TwitchPlaybackSession {
	return &repository.TwitchPlaybackSession{
		CheckedAt:      src.CheckedAt,
		EncryptedToken: src.EncryptedToken,
		ExpiresAt:      src.ExpiresAt,
		NeedsReconnect: src.NeedsReconnect,
		TwitchLogin:    src.TwitchLogin,
		TwitchUserID:   src.TwitchUserID,
	}
}

func pgWhitelistEntryToDomain(src pggen.Whitelist) *repository.WhitelistEntry {
	return &repository.WhitelistEntry{
		AddedAt:      src.AddedAt,
		TwitchUserID: src.TwitchUserID,
	}
}

func pgWhitelistEntriesToDomain(rows []pggen.Whitelist) []repository.WhitelistEntry {
	out := make([]repository.WhitelistEntry, len(rows))
	for i, r := range rows {
		out[i] = *pgWhitelistEntryToDomain(r)
	}
	return out
}

func pgRelatedRecordingToDomain(src pggen.ListRelatedRecordingsRow) *repository.RelatedRecording {
	return &repository.RelatedRecording{
		CompletionKind:  src.CompletionKind,
		DeletedAt:       src.DeletedAt,
		ID:              src.ID,
		JobID:           src.JobID,
		Position:        src.Position,
		StartDownloadAt: src.StartDownloadAt,
		Status:          src.Status,
		Title:           src.Title,
	}
}

func pgRelatedRecordingsToDomain(rows []pggen.ListRelatedRecordingsRow) []repository.RelatedRecording {
	out := make([]repository.RelatedRecording, len(rows))
	for i, r := range rows {
		out[i] = *pgRelatedRecordingToDomain(r)
	}
	return out
}

func pgVideoStatsByStatusToDomain(src pggen.StatisticsByStatusRow) *repository.VideoStatsByStatus {
	return &repository.VideoStatsByStatus{
		Count:  src.Count,
		Status: src.Status,
	}
}

func pgVideoStatsByStatusesToDomain(rows []pggen.StatisticsByStatusRow) []repository.VideoStatsByStatus {
	out := make([]repository.VideoStatsByStatus, len(rows))
	for i, r := range rows {
		out[i] = *pgVideoStatsByStatusToDomain(r)
	}
	return out
}

func pgTitleToDomain(src pggen.Title) *repository.Title {
	return &repository.Title{
		CreatedAt: src.CreatedAt,
		ID:        src.ID,
		Name:      src.Name,
	}
}

func pgTagToDomain(src pggen.Tag) *repository.Tag {
	return &repository.Tag{
		CreatedAt: src.CreatedAt,
		ID:        src.ID,
		Name:      src.Name,
	}
}

func pgTagsToDomain(rows []pggen.Tag) []repository.Tag {
	out := make([]repository.Tag, len(rows))
	for i, r := range rows {
		out[i] = *pgTagToDomain(r)
	}
	return out
}

func pgCategoryToDomain(src pggen.Category) *repository.Category {
	return &repository.Category{
		BoxArtURL:             src.BoxArtUrl,
		CreatedAt:             src.CreatedAt,
		Description:           src.Description,
		DescriptionCheckedAt:  src.DescriptionCheckedAt,
		GameMetadataCheckedAt: src.GameMetadataCheckedAt,
		ID:                    src.ID,
		IGDBID:                src.IgdbID,
		Name:                  src.Name,
		UpdatedAt:             src.UpdatedAt,
	}
}

func pgCategoriesToDomain(rows []pggen.Category) []repository.Category {
	out := make([]repository.Category, len(rows))
	for i, r := range rows {
		out[i] = *pgCategoryToDomain(r)
	}
	return out
}

func pgChannelToDomain(src pggen.Channel) *repository.Channel {
	return &repository.Channel{
		BroadcasterID:       src.BroadcasterID,
		BroadcasterLanguage: src.BroadcasterLanguage,
		BroadcasterLogin:    src.BroadcasterLogin,
		BroadcasterName:     src.BroadcasterName,
		BroadcasterType:     src.BroadcasterType,
		CreatedAt:           src.CreatedAt,
		Description:         src.Description,
		OfflineImageURL:     src.OfflineImageUrl,
		ProfileImageURL:     src.ProfileImageUrl,
		UpdatedAt:           src.UpdatedAt,
		ViewCount:           src.ViewCount,
	}
}

func pgChannelsToDomain(rows []pggen.Channel) []repository.Channel {
	out := make([]repository.Channel, len(rows))
	for i, r := range rows {
		out[i] = *pgChannelToDomain(r)
	}
	return out
}

func pgChannelUserStateToDomain(src pggen.ChannelUserState) *repository.ChannelUserState {
	return &repository.ChannelUserState{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt,
		Favorite:      src.Favorite,
		UpdatedAt:     src.UpdatedAt,
		UserID:        src.UserID,
	}
}

func pgEventLogToDomain(src pggen.EventLog) *repository.EventLog {
	return &repository.EventLog{
		ActorUserID: src.ActorUserID,
		CreatedAt:   src.CreatedAt,
		Data:        src.Data,
		Domain:      src.Domain,
		EventType:   src.EventType,
		ID:          src.ID,
		Message:     src.Message,
		Severity:    src.Severity,
	}
}

func pgEventLogsToDomain(rows []pggen.EventLog) []repository.EventLog {
	out := make([]repository.EventLog, len(rows))
	for i, r := range rows {
		out[i] = *pgEventLogToDomain(r)
	}
	return out
}

func pgJobToDomain(src pggen.Job) *repository.Job {
	return &repository.Job{
		AcceptsMetadata: src.AcceptsMetadata,
		Attempt:         src.Attempt,
		BroadcasterID:   src.BroadcasterID,
		CreatedAt:       src.CreatedAt,
		Error:           src.Error,
		ExecutionID:     src.ExecutionID,
		FinishedAt:      src.FinishedAt,
		ID:              src.ID,
		ResumeState:     src.ResumeState,
		StartedAt:       src.StartedAt,
		Status:          src.Status,
		StopRequested:   src.StopRequested,
		UpdatedAt:       src.UpdatedAt,
		VideoID:         src.VideoID,
	}
}

func pgMediaPublicationToDomain(src pggen.MediaPublication) *repository.MediaPublication {
	return &repository.MediaPublication{
		DeleteRequested: src.DeleteRequested,
		Digest:          src.Digest,
		Key:             src.Key,
		SizeBytes:       src.SizeBytes,
		Unresolved:      src.Unresolved,
		VideoID:         src.VideoID,
	}
}

func pgMediaPublicationsToDomain(rows []pggen.MediaPublication) []repository.MediaPublication {
	out := make([]repository.MediaPublication, len(rows))
	for i, r := range rows {
		out[i] = *pgMediaPublicationToDomain(r)
	}
	return out
}

func pgRecordingIntentToDomain(src pggen.RecordingIntent) *repository.RecordingIntent {
	return &repository.RecordingIntent{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt,
		CurrentJobID:  src.CurrentJobID,
		ID:            src.ID,
		LastStreamID:  src.LastStreamID,
		Params:        src.Params,
		Status:        src.Status,
		StopRequested: src.StopRequested,
		WaitSeconds:   src.WaitSeconds,
		WaitUntil:     src.WaitUntil,
	}
}

func pgRecordingIntentsToDomain(rows []pggen.RecordingIntent) []repository.RecordingIntent {
	out := make([]repository.RecordingIntent, len(rows))
	for i, r := range rows {
		out[i] = *pgRecordingIntentToDomain(r)
	}
	return out
}

func pgRecordingWebhookDeliveryToDomain(src pggen.RecordingWebhookDelivery) *repository.RecordingWebhookDelivery {
	return &repository.RecordingWebhookDelivery{
		Attempts:      int(src.Attempts),
		CreatedAt:     src.CreatedAt,
		DedupeKey:     src.DedupeKey,
		DeliveredAt:   src.DeliveredAt,
		Event:         src.Event,
		FrozenParts:   src.FrozenParts,
		ID:            src.ID,
		LastAttemptAt: src.LastAttemptAt,
		LastError:     src.LastError,
		LastStatus:    int(src.LastStatus),
		MessageID:     src.MessageID,
		NextAttemptAt: src.NextAttemptAt,
		Status:        src.Status,
		Test:          src.Test,
		UpdatedAt:     src.UpdatedAt,
		VideoID:       src.VideoID,
	}
}

func pgStreamToDomain(src pggen.Stream) *repository.Stream {
	return &repository.Stream{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt,
		EndedAt:       src.EndedAt,
		ID:            src.ID,
		IsMature:      src.IsMature,
		Language:      src.Language,
		StartedAt:     src.StartedAt,
		ThumbnailURL:  src.ThumbnailUrl,
		Type:          src.Type,
		ViewerCount:   int64(src.ViewerCount),
	}
}

func pgStreamsToDomain(rows []pggen.Stream) []repository.Stream {
	out := make([]repository.Stream, len(rows))
	for i, r := range rows {
		out[i] = *pgStreamToDomain(r)
	}
	return out
}

func pgSubscriptionToDomain(src pggen.Subscription) *repository.Subscription {
	return &repository.Subscription{
		BroadcasterID:     src.BroadcasterID,
		Condition:         src.Condition,
		Cost:              int64(src.Cost),
		CreatedAt:         src.CreatedAt,
		ID:                src.ID,
		RevokedAt:         src.RevokedAt,
		RevokedReason:     src.RevokedReason,
		Status:            src.Status,
		TransportCallback: src.TransportCallback,
		TransportMethod:   src.TransportMethod,
		TwitchCreatedAt:   src.TwitchCreatedAt,
		Type:              src.Type,
		Version:           src.Version,
	}
}

func pgSubscriptionsToDomain(rows []pggen.Subscription) []repository.Subscription {
	out := make([]repository.Subscription, len(rows))
	for i, r := range rows {
		out[i] = *pgSubscriptionToDomain(r)
	}
	return out
}

func pgTaskToDomain(src pggen.Task) *repository.Task {
	return &repository.Task{
		CreatedAt:       src.CreatedAt,
		Description:     src.Description,
		ExecutionID:     src.ExecutionID,
		IntervalSeconds: src.IntervalSeconds,
		IsAvailable:     src.IsAvailable,
		IsEnabled:       src.IsEnabled,
		LastDurationMs:  src.LastDurationMs,
		LastError:       src.LastError,
		LastRunAt:       src.LastRunAt,
		LastStatus:      src.LastStatus,
		Name:            src.Name,
		NextRunAt:       src.NextRunAt,
		UpdatedAt:       src.UpdatedAt,
	}
}

func pgTasksToDomain(rows []pggen.Task) []repository.Task {
	out := make([]repository.Task, len(rows))
	for i, r := range rows {
		out[i] = *pgTaskToDomain(r)
	}
	return out
}

func pgUserToDomain(src pggen.User) *repository.User {
	return &repository.User{
		CreatedAt:       src.CreatedAt,
		DisplayName:     src.DisplayName,
		Email:           src.Email,
		ID:              src.ID,
		Login:           src.Login,
		ProfileImageURL: src.ProfileImageUrl,
		Role:            src.Role,
		UpdatedAt:       src.UpdatedAt,
	}
}

func pgUsersToDomain(rows []pggen.User) []repository.User {
	out := make([]repository.User, len(rows))
	for i, r := range rows {
		out[i] = *pgUserToDomain(r)
	}
	return out
}

func pgVideoPartToDomain(src pggen.VideoPart) *repository.VideoPart {
	return &repository.VideoPart{
		Codec:           src.Codec,
		CreatedAt:       src.CreatedAt,
		DurationSeconds: src.DurationSeconds,
		EndMediaSeq:     src.EndMediaSeq,
		FPS:             src.Fps,
		Filename:        src.Filename,
		ID:              src.ID,
		PartIndex:       src.PartIndex,
		Quality:         src.Quality,
		SegmentFormat:   src.SegmentFormat,
		SizeBytes:       src.SizeBytes,
		StartMediaSeq:   src.StartMediaSeq,
		Thumbnail:       src.Thumbnail,
		UpdatedAt:       src.UpdatedAt,
		VideoID:         src.VideoID,
	}
}

func pgVideoPartsToDomain(rows []pggen.VideoPart) []repository.VideoPart {
	out := make([]repository.VideoPart, len(rows))
	for i, r := range rows {
		out[i] = *pgVideoPartToDomain(r)
	}
	return out
}

func pgVideoPlaybackAssetToDomain(src pggen.VideoPlaybackAsset) *repository.VideoPlaybackAsset {
	return &repository.VideoPlaybackAsset{
		CreatedAt:       src.CreatedAt,
		DurationSeconds: src.DurationSeconds,
		Error:           src.Error,
		Filename:        src.Filename,
		GeneratedAt:     src.GeneratedAt,
		LastAccessedAt:  src.LastAccessedAt,
		MimeType:        src.MimeType,
		SizeBytes:       src.SizeBytes,
		Status:          src.Status,
		UpdatedAt:       src.UpdatedAt,
		VideoID:         src.VideoID,
	}
}

func pgVideoUserStateToDomain(src pggen.VideoUserState) *repository.VideoUserState {
	return &repository.VideoUserState{
		CompletedAt:         src.CompletedAt,
		CreatedAt:           src.CreatedAt,
		LastPositionSeconds: src.LastPositionSeconds,
		LastProgressAtMs:    src.LastProgressAtMs,
		ProgressRevision:    src.ProgressRevision,
		UpdatedAt:           src.UpdatedAt,
		UserID:              src.UserID,
		VideoID:             src.VideoID,
		WatchLater:          src.WatchLater,
		WatchedAt:           src.WatchedAt,
	}
}

func pgWebhookEventToDomain(src pggen.WebhookEvent) *repository.WebhookEvent {
	return &repository.WebhookEvent{
		BroadcasterID:    src.BroadcasterID,
		Error:            src.Error,
		EventID:          src.EventID,
		EventType:        src.EventType,
		ID:               src.ID,
		MessageTimestamp: src.MessageTimestamp,
		MessageType:      src.MessageType,
		Payload:          src.Payload,
		ProcessedAt:      src.ProcessedAt,
		ReceivedAt:       src.ReceivedAt,
		Status:           src.Status,
		SubscriptionID:   src.SubscriptionID,
	}
}

func pgWebhookEventsToDomain(rows []pggen.WebhookEvent) []repository.WebhookEvent {
	out := make([]repository.WebhookEvent, len(rows))
	for i, r := range rows {
		out[i] = *pgWebhookEventToDomain(r)
	}
	return out
}

func pgServerSettingsToDomain(src pggen.ServerSetting) *repository.ServerSettings {
	return &repository.ServerSettings{
		CreatedAt:                     src.CreatedAt,
		EventSubRelayIngestURL:        src.EventsubRelayIngestUrl,
		EventSubRelayLocalCallbackURL: src.EventsubRelayLocalCallbackUrl,
		EventSubRelaySubscribeURL:     src.EventsubRelaySubscribeUrl,
		EventSubWebhookCallbackURL:    src.EventsubWebhookCallbackUrl,
		PlaybackCacheAutoGenerate:     src.PlaybackCacheAutoGenerate,
		PlaybackCacheEnabled:          src.PlaybackCacheEnabled,
		PlaybackCacheMaxPercent:       int(src.PlaybackCacheMaxPercent),
		RecordingWebhookEnabled:       src.RecordingWebhookEnabled,
		RecordingWebhookEvents:        src.RecordingWebhookEvents,
		RecordingWebhookSecret:        src.RecordingWebhookSecret,
		RecordingWebhookURL:           src.RecordingWebhookUrl,
		SchedulesPaused:               src.SchedulesPaused,
		ServerMode:                    src.ServerMode,
		StorageID:                     src.StorageID,
		StorageRestoreCursor:          src.StorageRestoreCursor,
		StorageScanCursor:             src.StorageScanCursor,
		UpdatedAt:                     src.UpdatedAt,
	}
}

func pgSettingsToDomain(src pggen.Setting) *repository.Settings {
	return &repository.Settings{
		CreatedAt:              src.CreatedAt,
		DatetimeFormat:         src.DatetimeFormat,
		Language:               src.Language,
		ResumeEndMarginPercent: src.ResumeEndMarginPercent,
		ResumeEndMarginSeconds: src.ResumeEndMarginSeconds,
		ResumeMinSeconds:       src.ResumeMinSeconds,
		Timezone:               src.Timezone,
		UpdatedAt:              src.UpdatedAt,
		UserID:                 src.UserID,
	}
}

func pgSnapshotToDomain(src pggen.EventsubSnapshot) *repository.EventSubSnapshot {
	return &repository.EventSubSnapshot{
		FetchedAt:    src.FetchedAt,
		ID:           src.ID,
		MaxTotalCost: int64(src.MaxTotalCost),
		Total:        int64(src.Total),
		TotalCost:    int64(src.TotalCost),
	}
}

func pgSnapshotsToDomain(rows []pggen.EventsubSnapshot) []repository.EventSubSnapshot {
	out := make([]repository.EventSubSnapshot, len(rows))
	for i, r := range rows {
		out[i] = *pgSnapshotToDomain(r)
	}
	return out
}
