// Code generated by repo-adapter-gen. DO NOT EDIT.

package pgadapter

import (
	"context"
	"fmt"
	"github.com/befabri/replayvod/server/internal/repository"
)

func (a *PGAdapter) DeleteExpiredAppTokens(ctx context.Context) error {
	return a.queries.DeleteExpiredAppTokens(ctx)
}

func (a *PGAdapter) DeleteExpiredSessions(ctx context.Context) error {
	return a.queries.DeleteExpiredSessions(ctx)
}

func (a *PGAdapter) UpsertTitle(ctx context.Context, name string) (*repository.Title, error) {
	row, err := a.queries.UpsertTitle(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("pg upsert title: %w", err)
	}
	return pgTitleToDomain(row), nil
}

func (a *PGAdapter) UpsertTag(ctx context.Context, name string) (*repository.Tag, error) {
	row, err := a.queries.UpsertTag(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("pg upsert tag: %w", err)
	}
	return pgTagToDomain(row), nil
}
