// Code generated by twitch-api-gen. DO NOT EDIT.
// Source: https://dev.twitch.tv/docs/api/reference/
// Generated: 2026-04-12T00:37:48Z

package twitch

import "context"

// CreateEventSubSubscription — Creates an EventSub subscription.
// POST /eventsub/subscriptions
// Auth: either (scopes: channel:read:subscriptions)
// https://dev.twitch.tv/docs/api/reference#create-eventsub-subscription
func (c *Client) CreateEventSubSubscription(ctx context.Context, body *CreateEventSubSubscriptionBody) ([]EventSubSubscription, error) {
	var result helixResponse[EventSubSubscription]
	if err := c.post(ctx, "/eventsub/subscriptions", nil, body, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// DeleteEventSubSubscription — Deletes an EventSub subscription.
// DELETE /eventsub/subscriptions
// Auth: either
// https://dev.twitch.tv/docs/api/reference#delete-eventsub-subscription
func (c *Client) DeleteEventSubSubscription(ctx context.Context, params *DeleteEventSubSubscriptionParams) error {
	if err := c.delete(ctx, "/eventsub/subscriptions", params, nil); err != nil {
		return err
	}
	return nil
}

// GetChannelInformation — Gets information about one or more channels.
// GET /channels
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-channel-information
func (c *Client) GetChannelInformation(ctx context.Context, params *GetChannelInformationParams) ([]ChannelInformation, error) {
	var result helixResponse[ChannelInformation]
	if err := c.get(ctx, "/channels", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetEventSubSubscriptions — Gets a list of EventSub subscriptions that the client in the access token created.
// GET /eventsub/subscriptions
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions
func (c *Client) GetEventSubSubscriptions(ctx context.Context, params *GetEventSubSubscriptionsParams) ([]EventSubSubscription, Pagination, error) {
	var result helixResponse[EventSubSubscription]
	if err := c.get(ctx, "/eventsub/subscriptions", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetEventSubSubscriptionsAll iterates GetEventSubSubscriptions until pagination is exhausted.
func (c *Client) GetEventSubSubscriptionsAll(ctx context.Context, params *GetEventSubSubscriptionsParams) ([]EventSubSubscription, error) {
	var all []EventSubSubscription
	if params == nil {
		params = &GetEventSubSubscriptionsParams{}
	}
	for {
		page, pagination, err := c.GetEventSubSubscriptions(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}

// GetFollowedChannels — Gets a list of broadcasters that the specified user follows. You can also use this endpoint to see whether a user follows a specific broadcaster.
// GET /channels/followed
// Auth: user (scopes: user:read:follows)
// https://dev.twitch.tv/docs/api/reference#get-followed-channels
func (c *Client) GetFollowedChannels(ctx context.Context, params *GetFollowedChannelsParams) ([]FollowedChannel, Pagination, error) {
	var result helixResponse[FollowedChannel]
	if err := c.get(ctx, "/channels/followed", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetFollowedChannelsAll iterates GetFollowedChannels until pagination is exhausted.
func (c *Client) GetFollowedChannelsAll(ctx context.Context, params *GetFollowedChannelsParams) ([]FollowedChannel, error) {
	var all []FollowedChannel
	if params == nil {
		params = &GetFollowedChannelsParams{}
	}
	for {
		page, pagination, err := c.GetFollowedChannels(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}

// GetFollowedStreams — Gets the list of broadcasters that the user follows and that are streaming live.
// GET /streams/followed
// Auth: user (scopes: user:read:follows)
// https://dev.twitch.tv/docs/api/reference#get-followed-streams
func (c *Client) GetFollowedStreams(ctx context.Context, params *GetFollowedStreamsParams) ([]Stream, Pagination, error) {
	var result helixResponse[Stream]
	if err := c.get(ctx, "/streams/followed", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetFollowedStreamsAll iterates GetFollowedStreams until pagination is exhausted.
func (c *Client) GetFollowedStreamsAll(ctx context.Context, params *GetFollowedStreamsParams) ([]Stream, error) {
	var all []Stream
	if params == nil {
		params = &GetFollowedStreamsParams{}
	}
	for {
		page, pagination, err := c.GetFollowedStreams(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}

// GetGames — Gets information about specified games.
// GET /games
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-games
func (c *Client) GetGames(ctx context.Context, params *GetGamesParams) ([]Game, error) {
	var result helixResponse[Game]
	if err := c.get(ctx, "/games", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetStreams — Gets a list of all streams.
// GET /streams
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-streams
func (c *Client) GetStreams(ctx context.Context, params *GetStreamsParams) ([]Stream, Pagination, error) {
	var result helixResponse[Stream]
	if err := c.get(ctx, "/streams", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetStreamsAll iterates GetStreams until pagination is exhausted.
func (c *Client) GetStreamsAll(ctx context.Context, params *GetStreamsParams) ([]Stream, error) {
	var all []Stream
	if params == nil {
		params = &GetStreamsParams{}
	}
	for {
		page, pagination, err := c.GetStreams(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}

// GetTopGames — Gets information about all broadcasts on Twitch.
// GET /games/top
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-top-games
func (c *Client) GetTopGames(ctx context.Context, params *GetTopGamesParams) ([]Game, Pagination, error) {
	var result helixResponse[Game]
	if err := c.get(ctx, "/games/top", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetTopGamesAll iterates GetTopGames until pagination is exhausted.
func (c *Client) GetTopGamesAll(ctx context.Context, params *GetTopGamesParams) ([]Game, error) {
	var all []Game
	if params == nil {
		params = &GetTopGamesParams{}
	}
	for {
		page, pagination, err := c.GetTopGames(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}

// GetUsers — Gets information about one or more users.
// GET /users
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-users
func (c *Client) GetUsers(ctx context.Context, params *GetUsersParams) ([]User, error) {
	var result helixResponse[User]
	if err := c.get(ctx, "/users", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetVideos — Gets information about one or more published videos.
// GET /videos
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-videos
func (c *Client) GetVideos(ctx context.Context, params *GetVideosParams) ([]Video, Pagination, error) {
	var result helixResponse[Video]
	if err := c.get(ctx, "/videos", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, result.Pagination, nil
}

// GetVideosAll iterates GetVideos until pagination is exhausted.
func (c *Client) GetVideosAll(ctx context.Context, params *GetVideosParams) ([]Video, error) {
	var all []Video
	if params == nil {
		params = &GetVideosParams{}
	}
	for {
		page, pagination, err := c.GetVideos(ctx, params)
		if err != nil {
			return nil, err
		}
		all = append(all, page...)
		if pagination.Cursor == "" {
			return all, nil
		}
		params.After = pagination.Cursor
	}
}
