// Code generated by twitch-api-gen. DO NOT EDIT.
// Source: https://dev.twitch.tv/docs/api/reference/
// Generated: 2026-04-12T00:00:00Z

package twitch

import "context"

// CreateChannelStreamScheduleSegment — Adds a single or recurring broadcast to the broadcaster’s streaming schedule.
// POST /schedule/segment
// Auth: user (scopes: channel:manage:schedule)
// https://dev.twitch.tv/docs/api/reference#create-channel-stream-schedule-segment
func (c *Client) CreateChannelStreamScheduleSegment(ctx context.Context, params *CreateChannelStreamScheduleSegmentParams, body *CreateChannelStreamScheduleSegmentBody) ([]CreateChannelStreamScheduleSegmentResponse, error) {
	var result helixResponse[CreateChannelStreamScheduleSegmentResponse]
	if err := c.post(ctx, "/schedule/segment", params, body, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// CreateEventSubSubscription — Creates an EventSub subscription.
// POST /eventsub/subscriptions
// Auth: either (scopes: channel:read:subscriptions)
// https://dev.twitch.tv/docs/api/reference#create-eventsub-subscription
func (c *Client) CreateEventSubSubscription(ctx context.Context, body *CreateEventSubSubscriptionBody) ([]EventSubSubscription, error) {
	var result helixResponse[EventSubSubscription]
	if err := c.post(ctx, "/eventsub/subscriptions", nil, body, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// CreateStreamMarker — Adds a marker to a live stream.
// POST /streams/markers
// Auth: user (scopes: channel:manage:broadcast)
// https://dev.twitch.tv/docs/api/reference#create-stream-marker
func (c *Client) CreateStreamMarker(ctx context.Context, body *CreateStreamMarkerBody) ([]StreamMarkerCreated, error) {
	var result helixResponse[StreamMarkerCreated]
	if err := c.post(ctx, "/streams/markers", nil, body, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// DeleteChannelStreamScheduleSegment — Deletes a broadcast from the broadcaster’s streaming schedule.
// DELETE /schedule/segment
// Auth: user (scopes: channel:manage:schedule)
// https://dev.twitch.tv/docs/api/reference#delete-channel-stream-schedule-segment
func (c *Client) DeleteChannelStreamScheduleSegment(ctx context.Context, params *DeleteChannelStreamScheduleSegmentParams) error {
	if err := c.delete(ctx, "/schedule/segment", params, nil); err != nil {
		return err
	}
	return nil
}

// DeleteEventSubSubscription — Deletes an EventSub subscription.
// DELETE /eventsub/subscriptions
// Auth: either
// https://dev.twitch.tv/docs/api/reference#delete-eventsub-subscription
func (c *Client) DeleteEventSubSubscription(ctx context.Context, params *DeleteEventSubSubscriptionParams) error {
	if err := c.delete(ctx, "/eventsub/subscriptions", params, nil); err != nil {
		return err
	}
	return nil
}

// GetChannelInformation — Gets information about one or more channels.
// GET /channels
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-channel-information
func (c *Client) GetChannelInformation(ctx context.Context, params *GetChannelInformationParams) ([]ChannelInformation, error) {
	var result helixResponse[ChannelInformation]
	if err := c.get(ctx, "/channels", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetChannelStreamSchedule — Gets the broadcaster’s streaming schedule.
// GET /schedule
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-channel-stream-schedule
func (c *Client) GetChannelStreamSchedule(ctx context.Context, params *GetChannelStreamScheduleParams) ([]GetChannelStreamScheduleResponse, error) {
	var result helixResponse[GetChannelStreamScheduleResponse]
	if err := c.get(ctx, "/schedule", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetClips — Gets one or more video clips.
// GET /clips
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-clips
func (c *Client) GetClips(ctx context.Context, params *GetClipsParams) ([]Clip, Pagination, error) {
	var result helixResponse[Clip]
	if err := c.get(ctx, "/clips", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetClipsAll iterates GetClips until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetClipsAll(ctx context.Context, params *GetClipsParams) ([]Clip, Pagination, error) {
	var (
		all  []Clip
		last Pagination
	)
	if params == nil {
		params = &GetClipsParams{}
	}
	for {
		page, pagination, err := c.GetClips(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetEventSubSubscriptions — Gets a list of EventSub subscriptions that the client in the access token created.
// GET /eventsub/subscriptions
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions
func (c *Client) GetEventSubSubscriptions(ctx context.Context, params *GetEventSubSubscriptionsParams) ([]EventSubSubscription, Pagination, error) {
	var result helixResponse[EventSubSubscription]
	if err := c.get(ctx, "/eventsub/subscriptions", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetEventSubSubscriptionsAll iterates GetEventSubSubscriptions until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetEventSubSubscriptionsAll(ctx context.Context, params *GetEventSubSubscriptionsParams) ([]EventSubSubscription, Pagination, error) {
	var (
		all  []EventSubSubscription
		last Pagination
	)
	if params == nil {
		params = &GetEventSubSubscriptionsParams{}
	}
	for {
		page, pagination, err := c.GetEventSubSubscriptions(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetFollowedChannels — Gets a list of broadcasters that the specified user follows. You can also use this endpoint to see whether a user follows a specific broadcaster.
// GET /channels/followed
// Auth: user (scopes: user:read:follows)
// https://dev.twitch.tv/docs/api/reference#get-followed-channels
func (c *Client) GetFollowedChannels(ctx context.Context, params *GetFollowedChannelsParams) ([]FollowedChannel, Pagination, error) {
	var result helixResponse[FollowedChannel]
	if err := c.get(ctx, "/channels/followed", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetFollowedChannelsAll iterates GetFollowedChannels until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetFollowedChannelsAll(ctx context.Context, params *GetFollowedChannelsParams) ([]FollowedChannel, Pagination, error) {
	var (
		all  []FollowedChannel
		last Pagination
	)
	if params == nil {
		params = &GetFollowedChannelsParams{}
	}
	for {
		page, pagination, err := c.GetFollowedChannels(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetFollowedStreams — Gets the list of broadcasters that the user follows and that are streaming live.
// GET /streams/followed
// Auth: user (scopes: user:read:follows)
// https://dev.twitch.tv/docs/api/reference#get-followed-streams
func (c *Client) GetFollowedStreams(ctx context.Context, params *GetFollowedStreamsParams) ([]Stream, Pagination, error) {
	var result helixResponse[Stream]
	if err := c.get(ctx, "/streams/followed", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetFollowedStreamsAll iterates GetFollowedStreams until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetFollowedStreamsAll(ctx context.Context, params *GetFollowedStreamsParams) ([]Stream, Pagination, error) {
	var (
		all  []Stream
		last Pagination
	)
	if params == nil {
		params = &GetFollowedStreamsParams{}
	}
	for {
		page, pagination, err := c.GetFollowedStreams(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetGames — Gets information about specified games.
// GET /games
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-games
func (c *Client) GetGames(ctx context.Context, params *GetGamesParams) ([]Game, error) {
	var result helixResponse[Game]
	if err := c.get(ctx, "/games", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetStreamMarkers — Gets a list of markers from the user’s most recent stream or from the specified VOD/video.
// GET /streams/markers
// Auth: user (scopes: user:read:broadcast, channel:manage:broadcast)
// https://dev.twitch.tv/docs/api/reference#get-stream-markers
func (c *Client) GetStreamMarkers(ctx context.Context, params *GetStreamMarkersParams) ([]StreamMarkers, Pagination, error) {
	var result helixResponse[StreamMarkers]
	if err := c.get(ctx, "/streams/markers", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetStreamMarkersAll iterates GetStreamMarkers until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetStreamMarkersAll(ctx context.Context, params *GetStreamMarkersParams) ([]StreamMarkers, Pagination, error) {
	var (
		all  []StreamMarkers
		last Pagination
	)
	if params == nil {
		params = &GetStreamMarkersParams{}
	}
	for {
		page, pagination, err := c.GetStreamMarkers(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetStreams — Gets a list of all streams.
// GET /streams
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-streams
func (c *Client) GetStreams(ctx context.Context, params *GetStreamsParams) ([]Stream, Pagination, error) {
	var result helixResponse[Stream]
	if err := c.get(ctx, "/streams", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetStreamsAll iterates GetStreams until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetStreamsAll(ctx context.Context, params *GetStreamsParams) ([]Stream, Pagination, error) {
	var (
		all  []Stream
		last Pagination
	)
	if params == nil {
		params = &GetStreamsParams{}
	}
	for {
		page, pagination, err := c.GetStreams(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetTopGames — Gets information about all broadcasts on Twitch.
// GET /games/top
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-top-games
func (c *Client) GetTopGames(ctx context.Context, params *GetTopGamesParams) ([]Game, Pagination, error) {
	var result helixResponse[Game]
	if err := c.get(ctx, "/games/top", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetTopGamesAll iterates GetTopGames until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetTopGamesAll(ctx context.Context, params *GetTopGamesParams) ([]Game, Pagination, error) {
	var (
		all  []Game
		last Pagination
	)
	if params == nil {
		params = &GetTopGamesParams{}
	}
	for {
		page, pagination, err := c.GetTopGames(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// GetUsers — Gets information about one or more users.
// GET /users
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-users
func (c *Client) GetUsers(ctx context.Context, params *GetUsersParams) ([]User, error) {
	var result helixResponse[User]
	if err := c.get(ctx, "/users", params, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}

// GetVideos — Gets information about one or more published videos.
// GET /videos
// Auth: either
// https://dev.twitch.tv/docs/api/reference#get-videos
func (c *Client) GetVideos(ctx context.Context, params *GetVideosParams) ([]Video, Pagination, error) {
	var result helixResponse[Video]
	if err := c.get(ctx, "/videos", params, &result); err != nil {
		return nil, Pagination{}, err
	}
	return result.Data, Pagination{Cursor: result.Pagination.Cursor, Total: result.Total, TotalCost: result.TotalCost, MaxCost: result.MaxCost}, nil
}

// GetVideosAll iterates GetVideos until pagination is exhausted.
// The returned Pagination carries the final page's Total / TotalCost / MaxCost
// so callers can record quota without rolling their own loop.
func (c *Client) GetVideosAll(ctx context.Context, params *GetVideosParams) ([]Video, Pagination, error) {
	var (
		all  []Video
		last Pagination
	)
	if params == nil {
		params = &GetVideosParams{}
	}
	for {
		page, pagination, err := c.GetVideos(ctx, params)
		if err != nil {
			return nil, Pagination{}, err
		}
		all = append(all, page...)
		last = pagination
		if pagination.Cursor == "" {
			return all, last, nil
		}
		params.After = pagination.Cursor
	}
}

// ModifyChannelInformation — Updates a channel’s properties.
// PATCH /channels
// Auth: user (scopes: channel:manage:broadcast)
// https://dev.twitch.tv/docs/api/reference#modify-channel-information
func (c *Client) ModifyChannelInformation(ctx context.Context, params *ModifyChannelInformationParams, body *ModifyChannelInformationBody) error {
	if err := c.patch(ctx, "/channels", params, body, nil); err != nil {
		return err
	}
	return nil
}

// UpdateChannelStreamSchedule — Updates the broadcaster’s schedule settings, such as scheduling a vacation.
// PATCH /schedule/settings
// Auth: user (scopes: channel:manage:schedule)
// https://dev.twitch.tv/docs/api/reference#update-channel-stream-schedule
func (c *Client) UpdateChannelStreamSchedule(ctx context.Context, params *UpdateChannelStreamScheduleParams) error {
	if err := c.patch(ctx, "/schedule/settings", params, nil, nil); err != nil {
		return err
	}
	return nil
}

// UpdateChannelStreamScheduleSegment — Updates a scheduled broadcast segment.
// PATCH /schedule/segment
// Auth: user (scopes: channel:manage:schedule)
// https://dev.twitch.tv/docs/api/reference#update-channel-stream-schedule-segment
func (c *Client) UpdateChannelStreamScheduleSegment(ctx context.Context, params *UpdateChannelStreamScheduleSegmentParams, body *UpdateChannelStreamScheduleSegmentBody) ([]UpdateChannelStreamScheduleSegmentResponse, error) {
	var result helixResponse[UpdateChannelStreamScheduleSegmentResponse]
	if err := c.patch(ctx, "/schedule/segment", params, body, &result); err != nil {
		return nil, err
	}
	return result.Data, nil
}
