// Code generated by repo-adapter-gen. DO NOT EDIT.

package sqliteadapter

import (
	"github.com/befabri/replayvod/server/internal/repository"
	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitegen"
)

func sqliteTitleToDomain(src sqlitegen.Title) *repository.Title {
	return &repository.Title{
		CreatedAt: src.CreatedAt.Time,
		ID:        src.ID,
		Name:      src.Name,
	}
}

func sqliteTagToDomain(src sqlitegen.Tag) *repository.Tag {
	return &repository.Tag{
		CreatedAt: src.CreatedAt.Time,
		ID:        src.ID,
		Name:      src.Name,
	}
}
