// Code generated by repo-adapter-gen. DO NOT EDIT.

package sqliteadapter

import (
	"encoding/json"
	"github.com/befabri/replayvod/server/internal/repository"
	"github.com/befabri/replayvod/server/internal/repository/sqliteadapter/sqlitegen"
)

func sqliteTitleToDomain(src sqlitegen.Title) *repository.Title {
	return &repository.Title{
		CreatedAt: src.CreatedAt.Time,
		ID:        src.ID,
		Name:      src.Name,
	}
}

func sqliteTagToDomain(src sqlitegen.Tag) *repository.Tag {
	return &repository.Tag{
		CreatedAt: src.CreatedAt.Time,
		ID:        src.ID,
		Name:      src.Name,
	}
}

func sqliteTagsToDomain(rows []sqlitegen.Tag) []repository.Tag {
	out := make([]repository.Tag, len(rows))
	for i, r := range rows {
		out[i] = *sqliteTagToDomain(r)
	}
	return out
}

func sqliteCategoryToDomain(src sqlitegen.Category) *repository.Category {
	return &repository.Category{
		BoxArtURL:             fromNullString(src.BoxArtUrl),
		CreatedAt:             src.CreatedAt.Time,
		Description:           fromNullString(src.Description),
		DescriptionCheckedAt:  timePtrFromSQLite(src.DescriptionCheckedAt),
		GameMetadataCheckedAt: timePtrFromSQLite(src.GameMetadataCheckedAt),
		ID:                    src.ID,
		IGDBID:                fromNullString(src.IgdbID),
		Name:                  src.Name,
		UpdatedAt:             src.UpdatedAt.Time,
	}
}

func sqliteCategoriesToDomain(rows []sqlitegen.Category) []repository.Category {
	out := make([]repository.Category, len(rows))
	for i, r := range rows {
		out[i] = *sqliteCategoryToDomain(r)
	}
	return out
}

func sqliteChannelToDomain(src sqlitegen.Channel) *repository.Channel {
	return &repository.Channel{
		BroadcasterID:       src.BroadcasterID,
		BroadcasterLanguage: fromNullString(src.BroadcasterLanguage),
		BroadcasterLogin:    src.BroadcasterLogin,
		BroadcasterName:     src.BroadcasterName,
		BroadcasterType:     fromNullString(src.BroadcasterType),
		CreatedAt:           src.CreatedAt.Time,
		Description:         fromNullString(src.Description),
		OfflineImageURL:     fromNullString(src.OfflineImageUrl),
		ProfileImageURL:     fromNullString(src.ProfileImageUrl),
		UpdatedAt:           src.UpdatedAt.Time,
		ViewCount:           src.ViewCount,
	}
}

func sqliteChannelsToDomain(rows []sqlitegen.Channel) []repository.Channel {
	out := make([]repository.Channel, len(rows))
	for i, r := range rows {
		out[i] = *sqliteChannelToDomain(r)
	}
	return out
}

func sqliteChannelUserStateToDomain(src sqlitegen.ChannelUserState) *repository.ChannelUserState {
	return &repository.ChannelUserState{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt.Time,
		Favorite:      src.Favorite != 0,
		UpdatedAt:     src.UpdatedAt.Time,
		UserID:        src.UserID,
	}
}

func sqliteEventLogToDomain(src sqlitegen.EventLog) *repository.EventLog {
	return &repository.EventLog{
		ActorUserID: fromNullString(src.ActorUserID),
		CreatedAt:   src.CreatedAt.Time,
		Data:        rawMessageFromSQLite(src.Data),
		Domain:      src.Domain,
		EventType:   src.EventType,
		ID:          src.ID,
		Message:     src.Message,
		Severity:    src.Severity,
	}
}

func sqliteEventLogsToDomain(rows []sqlitegen.EventLog) []repository.EventLog {
	out := make([]repository.EventLog, len(rows))
	for i, r := range rows {
		out[i] = *sqliteEventLogToDomain(r)
	}
	return out
}

func sqliteJobToDomain(src sqlitegen.Job) *repository.Job {
	return &repository.Job{
		AcceptsMetadata: src.AcceptsMetadata != 0,
		Attempt:         int32(src.Attempt),
		BroadcasterID:   src.BroadcasterID,
		CreatedAt:       src.CreatedAt.Time,
		Error:           fromNullString(src.Error),
		ExecutionID:     src.ExecutionID,
		FinishedAt:      timePtrFromSQLite(src.FinishedAt),
		ID:              src.ID,
		ResumeState:     json.RawMessage(src.ResumeState),
		StartedAt:       timePtrFromSQLite(src.StartedAt),
		Status:          src.Status,
		StopRequested:   src.StopRequested != 0,
		UpdatedAt:       src.UpdatedAt.Time,
		VideoID:         src.VideoID,
	}
}

func sqliteMediaPublicationToDomain(src sqlitegen.MediaPublication) *repository.MediaPublication {
	return &repository.MediaPublication{
		DeleteRequested: src.DeleteRequested != 0,
		Digest:          src.Digest,
		Key:             src.Key,
		SizeBytes:       src.SizeBytes,
		Unresolved:      src.Unresolved != 0,
		VideoID:         src.VideoID,
	}
}

func sqliteMediaPublicationsToDomain(rows []sqlitegen.MediaPublication) []repository.MediaPublication {
	out := make([]repository.MediaPublication, len(rows))
	for i, r := range rows {
		out[i] = *sqliteMediaPublicationToDomain(r)
	}
	return out
}

func sqliteRecordingIntentToDomain(src sqlitegen.RecordingIntent) *repository.RecordingIntent {
	return &repository.RecordingIntent{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt.Time,
		CurrentJobID:  src.CurrentJobID,
		ID:            src.ID,
		LastStreamID:  src.LastStreamID,
		Params:        json.RawMessage(src.Params),
		Status:        src.Status,
		StopRequested: src.StopRequested != 0,
		WaitSeconds:   src.WaitSeconds,
		WaitUntil:     timePtrFromSQLitePrecise(src.WaitUntil),
	}
}

func sqliteRecordingIntentsToDomain(rows []sqlitegen.RecordingIntent) []repository.RecordingIntent {
	out := make([]repository.RecordingIntent, len(rows))
	for i, r := range rows {
		out[i] = *sqliteRecordingIntentToDomain(r)
	}
	return out
}

func sqliteRecordingWebhookDeliveryToDomain(src sqlitegen.RecordingWebhookDelivery) *repository.RecordingWebhookDelivery {
	return &repository.RecordingWebhookDelivery{
		Attempts:      int(src.Attempts),
		CreatedAt:     src.CreatedAt.Time,
		DedupeKey:     src.DedupeKey,
		DeliveredAt:   timePtrFromSQLite(src.DeliveredAt),
		Event:         src.Event,
		FrozenParts:   src.FrozenParts,
		ID:            src.ID,
		LastAttemptAt: timePtrFromSQLite(src.LastAttemptAt),
		LastError:     src.LastError,
		LastStatus:    int(src.LastStatus),
		MessageID:     src.MessageID,
		NextAttemptAt: src.NextAttemptAt.Time,
		Status:        src.Status,
		Test:          src.Test != 0,
		UpdatedAt:     src.UpdatedAt.Time,
		VideoID:       src.VideoID,
	}
}

func sqliteStreamToDomain(src sqlitegen.Stream) *repository.Stream {
	return &repository.Stream{
		BroadcasterID: src.BroadcasterID,
		CreatedAt:     src.CreatedAt.Time,
		EndedAt:       timePtrFromSQLite(src.EndedAt),
		ID:            src.ID,
		IsMature:      nullInt64ToBool(src.IsMature),
		Language:      src.Language,
		StartedAt:     src.StartedAt.Time,
		ThumbnailURL:  fromNullString(src.ThumbnailUrl),
		Type:          src.Type,
		ViewerCount:   src.ViewerCount,
	}
}

func sqliteStreamsToDomain(rows []sqlitegen.Stream) []repository.Stream {
	out := make([]repository.Stream, len(rows))
	for i, r := range rows {
		out[i] = *sqliteStreamToDomain(r)
	}
	return out
}

func sqliteSubscriptionToDomain(src sqlitegen.Subscription) *repository.Subscription {
	return &repository.Subscription{
		BroadcasterID:     fromNullString(src.BroadcasterID),
		Condition:         json.RawMessage(src.Condition),
		Cost:              src.Cost,
		CreatedAt:         src.CreatedAt.Time,
		ID:                src.ID,
		RevokedAt:         timePtrFromSQLite(src.RevokedAt),
		RevokedReason:     fromNullString(src.RevokedReason),
		Status:            src.Status,
		TransportCallback: src.TransportCallback,
		TransportMethod:   src.TransportMethod,
		TwitchCreatedAt:   src.TwitchCreatedAt.Time,
		Type:              src.Type,
		Version:           src.Version,
	}
}

func sqliteSubscriptionsToDomain(rows []sqlitegen.Subscription) []repository.Subscription {
	out := make([]repository.Subscription, len(rows))
	for i, r := range rows {
		out[i] = *sqliteSubscriptionToDomain(r)
	}
	return out
}

func sqliteTaskToDomain(src sqlitegen.Task) *repository.Task {
	return &repository.Task{
		CreatedAt:       src.CreatedAt.Time,
		Description:     src.Description,
		ExecutionID:     src.ExecutionID,
		IntervalSeconds: int32(src.IntervalSeconds),
		IsAvailable:     src.IsAvailable != 0,
		IsEnabled:       src.IsEnabled != 0,
		LastDurationMs:  int32(src.LastDurationMs),
		LastError:       fromNullString(src.LastError),
		LastRunAt:       timePtrFromSQLite(src.LastRunAt),
		LastStatus:      src.LastStatus,
		Name:            src.Name,
		NextRunAt:       timePtrFromSQLite(src.NextRunAt),
		UpdatedAt:       src.UpdatedAt.Time,
	}
}

func sqliteTasksToDomain(rows []sqlitegen.Task) []repository.Task {
	out := make([]repository.Task, len(rows))
	for i, r := range rows {
		out[i] = *sqliteTaskToDomain(r)
	}
	return out
}

func sqliteUserToDomain(src sqlitegen.User) *repository.User {
	return &repository.User{
		CreatedAt:       src.CreatedAt.Time,
		DisplayName:     src.DisplayName,
		Email:           fromNullString(src.Email),
		ID:              src.ID,
		Login:           src.Login,
		ProfileImageURL: fromNullString(src.ProfileImageUrl),
		Role:            src.Role,
		UpdatedAt:       src.UpdatedAt.Time,
	}
}

func sqliteUsersToDomain(rows []sqlitegen.User) []repository.User {
	out := make([]repository.User, len(rows))
	for i, r := range rows {
		out[i] = *sqliteUserToDomain(r)
	}
	return out
}

func sqliteVideoPartToDomain(src sqlitegen.VideoPart) *repository.VideoPart {
	return &repository.VideoPart{
		Codec:           src.Codec,
		CreatedAt:       src.CreatedAt.Time,
		DurationSeconds: src.DurationSeconds,
		EndMediaSeq:     fromNullInt64(src.EndMediaSeq),
		FPS:             fromNullFloat64(src.Fps),
		Filename:        src.Filename,
		ID:              src.ID,
		PartIndex:       int32(src.PartIndex),
		Quality:         src.Quality,
		SegmentFormat:   src.SegmentFormat,
		SizeBytes:       src.SizeBytes,
		StartMediaSeq:   src.StartMediaSeq,
		Thumbnail:       fromNullString(src.Thumbnail),
		UpdatedAt:       src.UpdatedAt.Time,
		VideoID:         src.VideoID,
	}
}

func sqliteVideoPartsToDomain(rows []sqlitegen.VideoPart) []repository.VideoPart {
	out := make([]repository.VideoPart, len(rows))
	for i, r := range rows {
		out[i] = *sqliteVideoPartToDomain(r)
	}
	return out
}

func sqliteVideoPlaybackAssetToDomain(src sqlitegen.VideoPlaybackAsset) *repository.VideoPlaybackAsset {
	return &repository.VideoPlaybackAsset{
		CreatedAt:       src.CreatedAt.Time,
		DurationSeconds: fromNullFloat64(src.DurationSeconds),
		Error:           fromNullString(src.Error),
		Filename:        fromNullString(src.Filename),
		GeneratedAt:     timePtrFromSQLite(src.GeneratedAt),
		LastAccessedAt:  timePtrFromSQLite(src.LastAccessedAt),
		MimeType:        fromNullString(src.MimeType),
		SizeBytes:       fromNullInt64(src.SizeBytes),
		Status:          src.Status,
		UpdatedAt:       src.UpdatedAt.Time,
		VideoID:         src.VideoID,
	}
}

func sqliteVideoUserStateToDomain(src sqlitegen.VideoUserState) *repository.VideoUserState {
	return &repository.VideoUserState{
		CompletedAt:         timePtrFromSQLite(src.CompletedAt),
		CreatedAt:           src.CreatedAt.Time,
		LastPositionSeconds: src.LastPositionSeconds,
		LastProgressAtMs:    fromNullInt64(src.LastProgressAtMs),
		ProgressRevision:    src.ProgressRevision,
		UpdatedAt:           src.UpdatedAt.Time,
		UserID:              src.UserID,
		VideoID:             src.VideoID,
		WatchLater:          src.WatchLater != 0,
		WatchedAt:           timePtrFromSQLite(src.WatchedAt),
	}
}

func sqliteWebhookEventToDomain(src sqlitegen.WebhookEvent) *repository.WebhookEvent {
	return &repository.WebhookEvent{
		BroadcasterID:    fromNullString(src.BroadcasterID),
		Error:            fromNullString(src.Error),
		EventID:          src.EventID,
		EventType:        fromNullString(src.EventType),
		ID:               src.ID,
		MessageTimestamp: src.MessageTimestamp.Time,
		MessageType:      src.MessageType,
		Payload:          rawMessageFromSQLite(src.Payload),
		ProcessedAt:      timePtrFromSQLite(src.ProcessedAt),
		ReceivedAt:       src.ReceivedAt.Time,
		Status:           src.Status,
		SubscriptionID:   fromNullString(src.SubscriptionID),
	}
}

func sqliteWebhookEventsToDomain(rows []sqlitegen.WebhookEvent) []repository.WebhookEvent {
	out := make([]repository.WebhookEvent, len(rows))
	for i, r := range rows {
		out[i] = *sqliteWebhookEventToDomain(r)
	}
	return out
}

func sqliteServerSettingsToDomain(src sqlitegen.ServerSetting) *repository.ServerSettings {
	return &repository.ServerSettings{
		CreatedAt:                     src.CreatedAt.Time,
		EventSubRelayIngestURL:        src.EventsubRelayIngestUrl,
		EventSubRelayLocalCallbackURL: src.EventsubRelayLocalCallbackUrl,
		EventSubRelaySubscribeURL:     src.EventsubRelaySubscribeUrl,
		EventSubWebhookCallbackURL:    src.EventsubWebhookCallbackUrl,
		PlaybackCacheAutoGenerate:     src.PlaybackCacheAutoGenerate != 0,
		PlaybackCacheEnabled:          src.PlaybackCacheEnabled != 0,
		PlaybackCacheMaxPercent:       int(src.PlaybackCacheMaxPercent),
		RecordingWebhookEnabled:       src.RecordingWebhookEnabled != 0,
		RecordingWebhookEvents:        src.RecordingWebhookEvents,
		RecordingWebhookSecret:        src.RecordingWebhookSecret,
		RecordingWebhookURL:           src.RecordingWebhookUrl,
		SchedulesPaused:               src.SchedulesPaused != 0,
		ServerMode:                    src.ServerMode,
		StorageID:                     src.StorageID,
		StorageRestoreCursor:          fromNullInt64(src.StorageRestoreCursor),
		StorageScanCursor:             src.StorageScanCursor,
		UpdatedAt:                     src.UpdatedAt.Time,
	}
}

func sqliteSettingsToDomain(src sqlitegen.Setting) *repository.Settings {
	return &repository.Settings{
		CreatedAt:              src.CreatedAt.Time,
		DatetimeFormat:         src.DatetimeFormat,
		Language:               src.Language,
		ResumeEndMarginPercent: src.ResumeEndMarginPercent,
		ResumeEndMarginSeconds: src.ResumeEndMarginSeconds,
		ResumeMinSeconds:       src.ResumeMinSeconds,
		Timezone:               src.Timezone,
		UpdatedAt:              src.UpdatedAt.Time,
		UserID:                 src.UserID,
	}
}

func sqliteSnapshotToDomain(src sqlitegen.EventsubSnapshot) *repository.EventSubSnapshot {
	return &repository.EventSubSnapshot{
		FetchedAt:    src.FetchedAt.Time,
		ID:           src.ID,
		MaxTotalCost: src.MaxTotalCost,
		Total:        src.Total,
		TotalCost:    src.TotalCost,
	}
}

func sqliteSnapshotsToDomain(rows []sqlitegen.EventsubSnapshot) []repository.EventSubSnapshot {
	out := make([]repository.EventSubSnapshot, len(rows))
	for i, r := range rows {
		out[i] = *sqliteSnapshotToDomain(r)
	}
	return out
}
