package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCheckAgainstCommitted covers the three user-facing outcomes: matched,
// drift, and missing committed file. Uses tmpdir fixtures so we don't have
// to edit the real committed copies.
func TestCheckAgainstCommitted(t *testing.T) {
	const header = "// Code generated by twitch-api-gen. DO NOT EDIT.\n// Source: https://example.test/\n// Generated: %s\n\npackage twitch\n"

	t.Run("match ignoring timestamp", func(t *testing.T) {
		gen := t.TempDir()
		committed := t.TempDir()
		for _, name := range checkedFiles {
			writeFile(t, filepath.Join(gen, name), []byte(render(header, "2026-04-12T00:37:00Z")))
			writeFile(t, filepath.Join(committed, name), []byte(render(header, "2026-04-12T00:00:00Z")))
		}
		if err := checkAgainstCommitted(gen, committed, silentLogger()); err != nil {
			t.Fatalf("expected nil; got %v", err)
		}
	})

	t.Run("drift reports stale files", func(t *testing.T) {
		gen := t.TempDir()
		committed := t.TempDir()
		for _, name := range checkedFiles {
			writeFile(t, filepath.Join(gen, name), []byte(render(header, "t")+"added line\n"))
			writeFile(t, filepath.Join(committed, name), []byte(render(header, "t")))
		}
		err := checkAgainstCommitted(gen, committed, silentLogger())
		if err == nil {
			t.Fatalf("expected drift error")
		}
		if !errors.Is(err, ErrGeneratedFilesStale) {
			t.Errorf("err %v: want wrapping ErrGeneratedFilesStale", err)
		}
		for _, name := range checkedFiles {
			if !strings.Contains(err.Error(), name) {
				t.Errorf("drift message should name %s; got %q", name, err.Error())
			}
		}
	})

	t.Run("missing committed file counts as drift", func(t *testing.T) {
		gen := t.TempDir()
		committed := t.TempDir()
		for _, name := range checkedFiles {
			writeFile(t, filepath.Join(gen, name), []byte(render(header, "t")))
		}
		// committed dir is empty — every file is "missing"
		err := checkAgainstCommitted(gen, committed, silentLogger())
		if err == nil {
			t.Fatalf("expected drift error")
		}
		if !errors.Is(err, ErrGeneratedFilesStale) {
			t.Errorf("err %v: want wrapping ErrGeneratedFilesStale", err)
		}
		if !strings.Contains(err.Error(), "committed file missing") {
			t.Errorf("drift message should mention missing files; got %q", err.Error())
		}
	})

	t.Run("timestamp anywhere in file still stripped", func(t *testing.T) {
		// Regression guard: earlier stripTimestampLine only scanned the first
		// 4 lines; this puts Generated: on line 10 and expects it to still match.
		gen := t.TempDir()
		committed := t.TempDir()
		padded := "// a\n// b\n// c\n// d\n// e\n// f\n// g\n// h\n// i\n// Generated: %s\npackage twitch\n"
		for _, name := range checkedFiles {
			writeFile(t, filepath.Join(gen, name), []byte(render(padded, "2026-04-12T00:37:00Z")))
			writeFile(t, filepath.Join(committed, name), []byte(render(padded, "2026-04-12T00:00:00Z")))
		}
		if err := checkAgainstCommitted(gen, committed, silentLogger()); err != nil {
			t.Errorf("late-line timestamp should strip; got %v", err)
		}
	})
}

func writeFile(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func render(format, ts string) string {
	return strings.Replace(format, "%s", ts, 1)
}
