import { Buffer } from "node:buffer";
import type { Route } from "@playwright/test";

// A four second AAC clip and a byte-range responder for it, shared by the
// watch page specs so a real <audio> element can load, play, and fail.
export const audioDurationSeconds = 4;
export const audioFixture = Buffer.from(
	[
		"AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAABbNtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAPoAABAAABAAAA",
		"AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
		"AAAE3XRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAPoAAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAA",
		"AAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAD6AAAAQAAAEAAAAABFVtZGlh",
		"AAAAIG1kaGQAAAAAAAAAAAAAAAAAAKxEAAK1EFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNvdW5kSGFu",
		"ZGxlcgAAAAQAbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAPEc3Ri",
		"bAAAAGpzdHNkAAAAAAAAAAEAAABabXA0YQAAAAAAAAABAAAAAAAAAAAAAQAQAAAAAKxEAAAAAAA2ZXNkcwAAAAADgICAJQAB",
		"AASAgIAXQBUAAAAAAB9AAAAFiQWAgIAFEghW5QAGgICAAQIAAAAgc3R0cwAAAAAAAAACAAAArQAABAAAAAABAAABEAAAABxz",
		"dHNjAAAAAAAAAAEAAAABAAAArgAAAAEAAALMc3RzegAAAAAAAAAAAAAArgAAABUAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQA",
		"AAAEAAAABAAAAAQAAAAEAAAABAAAABRzdGNvAAAAAAAAAAEAAAXfAAAAGnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2Jn",
		"cAAAAAByb2xsAAAAAQAAAK4AAAABAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAA",
		"AAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDEAAAAIZnJlZQAAAtFtZGF03gIATGF2YzYy",
		"LjI4LjEwMQACMEAOARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAH",
		"ARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAcBGCAHARggBwEYIAc=",
	].join(""),
	"base64",
);

export function fulfillAudioFixture(route: Route) {
	return fulfillRangeFixture(route, audioFixture, "audio/mp4");
}

// fulfillRangeFixture answers a media request the way the stream route does:
// HEAD with the length, byte ranges as 206, anything else as the whole body.
export async function fulfillRangeFixture(
	route: Route,
	fixture: Buffer,
	contentType: string,
) {
	const range = route.request().headers().range;
	const baseHeaders = {
		"Accept-Ranges": "bytes",
		"Content-Type": contentType,
	};
	if (route.request().method() === "HEAD") {
		await route.fulfill({
			status: 200,
			headers: {
				...baseHeaders,
				"Content-Length": String(fixture.length),
			},
		});
		return;
	}
	if (range) {
		const match = /^bytes=(\d*)-(\d*)$/.exec(range);
		const start = match?.[1] ? Number(match[1]) : 0;
		const requestedEnd = match?.[2] ? Number(match[2]) : fixture.length - 1;
		const end = Math.min(requestedEnd, fixture.length - 1);
		if (!match || start < 0 || start > end || start >= fixture.length) {
			await route.fulfill({
				status: 416,
				headers: {
					...baseHeaders,
					"Content-Range": `bytes */${fixture.length}`,
				},
			});
			return;
		}
		const body = fixture.subarray(start, end + 1);
		await route.fulfill({
			status: 206,
			headers: {
				...baseHeaders,
				"Content-Length": String(body.length),
				"Content-Range": `bytes ${start}-${end}/${fixture.length}`,
			},
			body,
		});
		return;
	}
	await route.fulfill({
		status: 200,
		headers: {
			...baseHeaders,
			"Content-Length": String(fixture.length),
		},
		body: fixture,
	});
}
