// Code generated by twitch-api-gen. DO NOT EDIT.
// Source: https://dev.twitch.tv/docs/api/reference/
// Generated: 2026-04-12T00:00:00Z

package twitch

import "time"

// Pagination is the cursor-based pagination object returned by list endpoints.
type Pagination struct {
	Cursor string `json:"cursor,omitempty"`
}

// helixResponse is the standard Twitch Helix API envelope.
type helixResponse[T any] struct {
	Data       []T        `json:"data"`
	Pagination Pagination `json:"pagination,omitempty"`
	Total      int        `json:"total,omitempty"`
	TotalCost  int        `json:"total_cost,omitempty"`
	MaxCost    int        `json:"max_total_cost,omitempty"`
}

// EventSubSubscription is the response item type for create-eventsub-subscription.
// https://dev.twitch.tv/docs/api/reference#create-eventsub-subscription
type EventSubSubscription struct {
	ID        string            `json:"id"`
	Status    string            `json:"status"`
	Type      string            `json:"type"`
	Version   string            `json:"version"`
	Condition EventSubCondition `json:"condition"`
	CreatedAt time.Time         `json:"created_at"`
	Transport EventSubTransport `json:"transport"`
	Cost      int               `json:"cost"`
}

// ChannelInformation is the response item type for get-channel-information.
// https://dev.twitch.tv/docs/api/reference#get-channel-information
type ChannelInformation struct {
	BroadcasterID               string   `json:"broadcaster_id"`
	BroadcasterLogin            string   `json:"broadcaster_login"`
	BroadcasterName             string   `json:"broadcaster_name"`
	BroadcasterLanguage         string   `json:"broadcaster_language"`
	GameName                    string   `json:"game_name"`
	GameID                      string   `json:"game_id"`
	Title                       string   `json:"title"`
	Delay                       int      `json:"delay"`
	Tags                        []string `json:"tags"`
	ContentClassificationLabels []string `json:"content_classification_labels"`
	IsBrandedContent            bool     `json:"is_branded_content"`
}

// FollowedChannel is the response item type for get-followed-channels.
// https://dev.twitch.tv/docs/api/reference#get-followed-channels
type FollowedChannel struct {
	BroadcasterID    string    `json:"broadcaster_id"`
	BroadcasterLogin string    `json:"broadcaster_login"`
	BroadcasterName  string    `json:"broadcaster_name"`
	FollowedAt       time.Time `json:"followed_at"`
}

// Stream is the response item type for get-followed-streams.
// https://dev.twitch.tv/docs/api/reference#get-followed-streams
type Stream struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	UserLogin    string    `json:"user_login"`
	UserName     string    `json:"user_name"`
	GameID       string    `json:"game_id"`
	GameName     string    `json:"game_name"`
	Type         string    `json:"type"`
	Title        string    `json:"title"`
	ViewerCount  int       `json:"viewer_count"`
	StartedAt    time.Time `json:"started_at"`
	Language     string    `json:"language"`
	ThumbnailURL string    `json:"thumbnail_url"`
	TagIds       []string  `json:"tag_ids"`
	Tags         []string  `json:"tags"`
	IsMature     bool      `json:"is_mature"`
}

// Game is the response item type for get-games.
// https://dev.twitch.tv/docs/api/reference#get-games
type Game struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	BoxArtURL string `json:"box_art_url"`
	IGDBID    string `json:"igdb_id"`
}

// User is the response item type for get-users.
// https://dev.twitch.tv/docs/api/reference#get-users
type User struct {
	ID              string `json:"id"`
	Login           string `json:"login"`
	DisplayName     string `json:"display_name"`
	Type            string `json:"type"`
	BroadcasterType string `json:"broadcaster_type"`
	Description     string `json:"description"`
	ProfileImageURL string `json:"profile_image_url"`
	OfflineImageURL string `json:"offline_image_url"`
	// Deprecated: Twitch marks this field deprecated in the API reference.
	ViewCount int       `json:"view_count"`
	Email     string    `json:"email,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// VideoMutedSegment is a nested object inside a generated response type.
type VideoMutedSegment struct {
	Duration int `json:"duration"`
	Offset   int `json:"offset"`
}

// Video is the response item type for get-videos.
// https://dev.twitch.tv/docs/api/reference#get-videos
type Video struct {
	ID            string              `json:"id"`
	StreamID      string              `json:"stream_id"`
	UserID        string              `json:"user_id"`
	UserLogin     string              `json:"user_login"`
	UserName      string              `json:"user_name"`
	Title         string              `json:"title"`
	Description   string              `json:"description"`
	CreatedAt     time.Time           `json:"created_at"`
	PublishedAt   time.Time           `json:"published_at"`
	URL           string              `json:"url"`
	ThumbnailURL  string              `json:"thumbnail_url"`
	Viewable      string              `json:"viewable"`
	ViewCount     int                 `json:"view_count"`
	Language      string              `json:"language"`
	Type          string              `json:"type"`
	Duration      string              `json:"duration"`
	MutedSegments []VideoMutedSegment `json:"muted_segments"`
}

// DeleteEventSubSubscriptionParams are the query parameters for delete-eventsub-subscription.
type DeleteEventSubSubscriptionParams struct {
	ID string `url:"id,omitempty"`
}

// GetChannelInformationParams are the query parameters for get-channel-information.
type GetChannelInformationParams struct {
	BroadcasterID []string `url:"broadcaster_id"`
}

// GetEventSubSubscriptionsParams are the query parameters for get-eventsub-subscriptions.
type GetEventSubSubscriptionsParams struct {
	Status         string `url:"status,omitempty"`
	Type           string `url:"type,omitempty"`
	UserID         string `url:"user_id,omitempty"`
	SubscriptionID string `url:"subscription_id,omitempty"`
	After          string `url:"after,omitempty"`
}

// GetFollowedChannelsParams are the query parameters for get-followed-channels.
type GetFollowedChannelsParams struct {
	UserID        string `url:"user_id,omitempty"`
	BroadcasterID string `url:"broadcaster_id,omitempty"`
	First         int    `url:"first,omitempty"`
	After         string `url:"after,omitempty"`
}

// GetFollowedStreamsParams are the query parameters for get-followed-streams.
type GetFollowedStreamsParams struct {
	UserID string `url:"user_id,omitempty"`
	First  int    `url:"first,omitempty"`
	After  string `url:"after,omitempty"`
}

// GetGamesParams are the query parameters for get-games.
type GetGamesParams struct {
	ID     []string `url:"id"`
	Name   []string `url:"name"`
	IGDBID []string `url:"igdb_id"`
}

// GetStreamsParams are the query parameters for get-streams.
type GetStreamsParams struct {
	UserID    []string `url:"user_id"`
	UserLogin []string `url:"user_login"`
	GameID    []string `url:"game_id"`
	Type      string   `url:"type,omitempty"`
	Language  []string `url:"language"`
	First     int      `url:"first,omitempty"`
	Before    string   `url:"before,omitempty"`
	After     string   `url:"after,omitempty"`
}

// GetTopGamesParams are the query parameters for get-top-games.
type GetTopGamesParams struct {
	First  int    `url:"first,omitempty"`
	After  string `url:"after,omitempty"`
	Before string `url:"before,omitempty"`
}

// GetUsersParams are the query parameters for get-users.
type GetUsersParams struct {
	ID    []string `url:"id"`
	Login []string `url:"login"`
}

// GetVideosParams are the query parameters for get-videos.
type GetVideosParams struct {
	ID       []string `url:"id"`
	UserID   string   `url:"user_id,omitempty"`
	GameID   string   `url:"game_id,omitempty"`
	Language string   `url:"language,omitempty"`
	Period   string   `url:"period,omitempty"`
	Sort     string   `url:"sort,omitempty"`
	Type     string   `url:"type,omitempty"`
	First    string   `url:"first,omitempty"`
	After    string   `url:"after,omitempty"`
	Before   string   `url:"before,omitempty"`
}

// CreateEventSubSubscriptionBody is the JSON request body for create-eventsub-subscription.
type CreateEventSubSubscriptionBody struct {
	Type      string            `json:"type"`
	Version   string            `json:"version"`
	Condition EventSubCondition `json:"condition"`
	Transport EventSubTransport `json:"transport"`
}
