name: Historical upgrade checks

on:
  schedule:
    - cron: '23 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upgrade:
    uses: ./.github/workflows/upgrade.yml
    with:
      scope: full
